#pragma once

/// One-k Bloch-IAO ALGEBRA from Zhu and Tew, JPCA 128, 8570 (2024),
/// doi:10.1021/acs.jpca.4c04555, Eqs.13-20. No minimal-basis default,
/// overlap integral producer, Wannier optimizer or physical-source certificate.
/// Work in retained orthonormal coordinates Y=C_ret: T=Y^H S12,
/// Z=T S22^-1 T_occ^H, Q=orth(Z), A=(O QQ^H+(I-O)(I-QQ^H))T.
/// O selects ALL occupied bands, including frozen core; I is I_retained,
/// never I_AO outside the admitted retained space. IAOs remain unorthogonalized.

#include <complex>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "vibeqc/periodic_correlation_admitted_reference.hpp"

namespace vibeqc {
inline constexpr std::uint32_t kPeriodicCorrelationBlochIAOContractVersion = 1;

/// Caller-declared provenance, not proof of a physical integral source.
/// Both identities must be lowercase SHA-256-shaped strings. Actual source
/// arrays and atom labels are separately digested by the native constructor.
struct PeriodicCorrelationBlochIAOInputProvenance {
    std::string cross_overlap_identity;
    std::string minimal_basis_identity;
    /// At least the active borrowed S12/S22/atom-map bytes. Other live storage
    /// belonging to their producer must be included too, unless already in
    /// the immutable admitted reference inventory. No unlimited zero value.
    std::uint64_t caller_live_numerical_bytes = 0;
};

struct PeriodicCorrelationBlochIAOOptions {
    /// Strict eigenvalue cutoffs max(abs,rel*lambda_max), no rank truncation.
    /// Depolarized/IAO cutoffs apply to GRAM EIGENVALUES, hence squared
    /// singular values of Z/A in retained coordinates, NOT singular values.
    double minimal_rank_absolute_floor = 0.0, minimal_rank_relative_floor = 0.0;
    double depolarized_rank_absolute_floor = 0.0, depolarized_rank_relative_floor = 0.0;
    double iao_rank_absolute_floor = 0.0, iao_rank_relative_floor = 0.0;
    /// S22-T^H T must be PSD; zero rank is valid. Reject eigenvalues below
    /// -(abs+rel*max_abs_eigenvalue). This is necessary algebraic consistency.
    double schur_negative_absolute_tolerance = 0.0, schur_negative_relative_tolerance = 0.0;
    double validation_absolute_tolerance = 0.0, validation_relative_tolerance = 0.0;
    std::uint64_t jacobi_max_sweeps = 0;
    double jacobi_relative_tolerance = 0.0;
    /// Conservative scalar-loop units charged before each stage, not FLOPs.
    std::uint64_t maximum_work_units = 0;
};

struct PeriodicCorrelationBlochIAOMemoryPlan {
    std::uint64_t n_basis = 0, n_effective = 0, n_occupied = 0, n_minimal = 0;
    std::uint64_t borrowed_input_bytes = 0, output_numerical_bytes = 0;
    std::uint64_t projection_workspace_bytes = 0, matrix_workspace_bytes = 0;
    std::uint64_t scalar_workspace_bytes = 0, peak_owned_numerical_bytes = 0;
    std::uint64_t input_preflight_work_units = 0, projection_work_units = 0;
    std::uint64_t construction_work_units = 0, validation_work_units = 0;
    std::uint64_t maximum_work_units = 0;
};

struct PeriodicCorrelationBlochIAODiagnostics {
    std::uint64_t required_node_memory_bytes = 0, charged_work_units = 0, jacobi_sweeps = 0;
    double maximum_retained_metric_residual = 0.0;
    double maximum_eigensystem_relative_residual = 0.0;
    double maximum_derived_hermitian_defect = 0.0;
    double maximum_derived_hermitization_correction = 0.0;
    double minimum_schur_eigenvalue = 0.0, schur_negative_boundary = 0.0;
    double minimum_minimal_eigenvalue = 0.0, minimal_rank_boundary = 0.0;
    double minimum_depolarized_gram_eigenvalue = 0.0, depolarized_rank_boundary = 0.0;
    double minimum_iao_gram_eigenvalue = 0.0, iao_rank_boundary = 0.0;
    double maximum_depolarized_metric_residual = 0.0, maximum_depolarized_span_residual = 0.0;
    double maximum_ao_iao_metric_residual = 0.0, maximum_covariant_residual = 0.0;
    double maximum_occupied_metric_residual = 0.0, maximum_retained_reconstruction_residual = 0.0;
    double maximum_ao_reconstruction_residual = 0.0, maximum_occupied_projector_residual = 0.0;
};

/// Move-only immutable one-point result. Retains A[e,r], G[r,r], B[r,p],
/// D[r,p], atom labels[r], occupied band indices[p] and the same state owner.
/// AO IAO coefficients are Y*A, generated by a scalar getter, not retained.
/// There is deliberately no assertion that caller-supplied overlaps were
/// calculated with a particular physical basis/phase convention.
class PeriodicCorrelationBlochIAO {
public:
    PeriodicCorrelationBlochIAO(const PeriodicCorrelationBlochIAO&) = delete;
    PeriodicCorrelationBlochIAO& operator=(const PeriodicCorrelationBlochIAO&) = delete;
    PeriodicCorrelationBlochIAO(PeriodicCorrelationBlochIAO&&) noexcept = default;
    PeriodicCorrelationBlochIAO& operator=(PeriodicCorrelationBlochIAO&&) noexcept = default;
    ~PeriodicCorrelationBlochIAO() = default;
    std::uint32_t contract_version() const noexcept { return kPeriodicCorrelationBlochIAOContractVersion; }
    std::size_t point() const noexcept { return point_; }
    const std::shared_ptr<const PeriodicRestrictedMeanFieldState>& state_handle() const noexcept { return state_; }
    const PeriodicRestrictedMeanFieldState& state() const;
    const PeriodicCorrelationBlochIAOMemoryPlan& memory() const noexcept { return memory_; }
    const PeriodicCorrelationBlochIAOOptions& options() const noexcept { return options_; }
    const PeriodicCorrelationBlochIAODiagnostics& diagnostics() const noexcept { return diagnostics_; }
    const PeriodicCorrelationBlochIAOInputProvenance& declared_provenance() const noexcept { return provenance_; }
    const std::string& input_payload_sha256() const noexcept { return input_digest_; }
    const std::string& output_payload_sha256() const noexcept { return output_digest_; }
    const std::string& iao_identity_sha256() const noexcept { return identity_digest_; }
    const std::string& allocation_identity() const noexcept { return allocation_identity_; }
    const std::complex<double>* retained_coefficients_data() const;
    const std::complex<double>* metric_data() const;
    const std::complex<double>* occupied_coefficients_data() const;
    const std::complex<double>* occupied_covariant_data() const;
    std::complex<double> ao_coefficient(std::size_t ao, std::size_t minimal) const;
    std::uint64_t atom_label(std::size_t minimal) const;
    std::uint64_t occupied_band(std::size_t occupied) const;
private:
    PeriodicCorrelationBlochIAO() = default;
    void require_live() const;
    std::size_t point_ = 0;
    std::shared_ptr<const PeriodicRestrictedMeanFieldState> state_;
    PeriodicCorrelationBlochIAOMemoryPlan memory_;
    PeriodicCorrelationBlochIAOOptions options_;
    PeriodicCorrelationBlochIAODiagnostics diagnostics_;
    PeriodicCorrelationBlochIAOInputProvenance provenance_;
    std::string input_digest_, output_digest_, identity_digest_, allocation_identity_;
    std::vector<std::complex<double>> a_, g_, b_, d_;
    std::vector<std::uint64_t> atom_labels_, occupied_indices_;
    friend PeriodicCorrelationBlochIAO make_periodic_correlation_bloch_iao(
        const PeriodicCorrelationAdmittedReference&, std::size_t,
        const std::complex<double>*, std::size_t, const std::complex<double>*, std::size_t,
        const std::uint64_t*, std::size_t, std::size_t,
        const PeriodicCorrelationBlochIAOInputProvenance&, std::uint64_t,
        const PeriodicCorrelationBlochIAOOptions&);
};

PeriodicCorrelationBlochIAOMemoryPlan plan_periodic_correlation_bloch_iao(
    std::uint64_t n_basis, std::uint64_t n_effective, std::uint64_t n_occupied,
    std::uint64_t n_minimal, std::uint64_t jacobi_max_sweeps);

/// Inputs are aligned row-major borrowed views with explicit accessible
/// scalar extents. S22 is exactly Hermitian, all complex lanes finite, atom
/// labels retained unchanged. p<=r<=e is required; no atomic column is dropped.
/// Caller keeps all borrowed inputs, options and provenance unchanged for
/// the complete call. No input pointer is retained by the returned result.
PeriodicCorrelationBlochIAO make_periodic_correlation_bloch_iao(
    const PeriodicCorrelationAdmittedReference& reference, std::size_t point,
    const std::complex<double>* cross_overlap, std::size_t cross_elements,
    const std::complex<double>* minimal_overlap, std::size_t minimal_elements,
    const std::uint64_t* atom_labels, std::size_t atom_label_elements, std::size_t n_minimal,
    const PeriodicCorrelationBlochIAOInputProvenance& provenance,
    std::uint64_t owned_numerical_byte_cap, const PeriodicCorrelationBlochIAOOptions& options);

}  // namespace vibeqc
