// Deterministic SCF restart via randomized orbital rotations.
//
// When the SCF stalls — gradient norm hovering above the convergence
// threshold while the energy is essentially converged (|dE| tiny) — a
// random rotation within the occupied and virtual subspaces produces a
// new density with the *same* idempotency and electron count but a
// different guess, which often escapes the DIIS limit cycle.
//
// The rotation is generated by a pseudorandom number generator seeded
// with a per-run constant so results are reproducible ("deterministic
// restart").

#pragma once

#include <Eigen/Dense>
#include <cstdint>
#include <utility>

namespace vibeqc {

struct SCFRestartOptions {
    bool enabled = true;
    int max_stall_iters = 15;
    std::uint64_t seed = 42;
    int max_restarts = 3;
};

Eigen::MatrixXd random_orthogonal(int n, std::uint64_t seed);

std::pair<Eigen::MatrixXd, Eigen::VectorXd> rotate_orbitals_in_subspaces(
    const Eigen::MatrixXd& C_prev,
    const Eigen::VectorXd& eps_prev,
    int n_occ,
    const Eigen::MatrixXd* F,
    std::uint64_t seed_occ,
    std::uint64_t seed_vir);

}  // namespace vibeqc
