// Elemental parameter tables for the D3 dispersion correction.
//
// Native D3(BJ) data scope:
//   - r2r4 (sqrt(<r^4> / <r^2>)) values for Z = 1..18 (H through Ar).
//     Canonical values from Grimme 2010 (a.u.).
//   - rcov values (bohr) = k2 · R_Pyykko, with k2 = 4/3 and conversion
//     R_Pyykko [Å] × 1.8897261246 bohr/Å, for Z = 1..18.
//   - The complete coordination-dependent C6 reference grid for H-Ar:
//     1,443 active values over the element-pair reference environments.
//     The generated include carries its pinned simple-dftd3 provenance.
//
// Everything numerical here is a published scientific constant. The C6
// include is generated by scripts/extract_d3_c6_reference.py rather than
// hand-transcribed so the native table remains auditable and reproducible.

#include "vibeqc/dispersion.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <limits>
#include <vector>

namespace vibeqc {

namespace {

// ---- r2r4 (a.u.) --------------------------------------------------------
// Zero-indexed at Z=1 (entry 0 is a placeholder so that rcov(Z) and
// r2r4(Z) can be indexed by the 1-based atomic number directly).
// Reference: Grimme J. Chem. Phys. 132, 154104 (2010), Table S1.
constexpr std::array<double, 19> kR2r4 = {
    0.0,        // Z=0 placeholder
    8.0589,     // H
    3.4698,     // He
    29.0974,    // Li
    14.8517,    // Be
    11.8799,    // B
    7.8715,     // C
    5.5588,     // N
    4.7566,     // O
    3.8025,     // F
    3.1036,     // Ne
    26.1552,    // Na
    17.2304,    // Mg
    17.7210,    // Al
    12.7442,    // Si
    9.5361,     // P
    8.1652,     // S
    6.7463,     // Cl
    5.6004,     // Ar
};

// ---- rcov (bohr) --------------------------------------------------------
// k2 = 4/3 applied to the Pyykkö covalent radii; result in bohr.
// D3 radii (Å), Pyykkö and Atsumi, Chem. Eur. J. 15, 186, with the
// published 10% metal adjustment used by simple-dftd3/mctc-lib v0.5.2:
//   H 0.32, He 0.46, Li 1.20, Be 0.94, B 0.77, C 0.75, N 0.71, O 0.63,
//   F 0.64, Ne 0.67, Na 1.40, Mg 1.25, Al 1.13, Si 1.04, P 1.10, S 1.02,
//   Cl 0.99, Ar 0.96.
// Converted offline: rcov_bohr = R_pyykko_Å × 4/3 × 1.8897261246.
constexpr std::array<double, 19> kRcov = {
    0.0,         // Z=0 placeholder
    0.8062831465,  // H
    1.1590320231,  // He
    3.0235617994,  // Li
    2.3684567429,  // Be
    1.9401188213,  // B
    1.8897261246,  // C
    1.7889407313,  // N
    1.5873699447,  // O
    1.6125662930,  // F
    1.6881553380,  // Ne
    3.5274887660,  // Na
    3.1495435410,  // Mg
    2.8471873611,  // Al
    2.6204202261,  // Si
    2.7715983161,  // P
    2.5700275295,  // S
    2.4944384845,  // Cl
    2.4188494395,  // Ar
};

constexpr int kMaxSupportedZ = 18;

// ---- C6 reference grid --------------------------------------------------
//
// Stored as (high-Z, low-Z, c6, CN_high_ref, CN_low_ref) tuples. Lookup
// canonicalises the element order and swaps the reference CNs back to the
// caller's orientation. The complete H-Ar corner contains 1,443 active
// values; unused slots from simple-dftd3's dense 7x7 storage are omitted.
struct C6Ref { int ZA, ZB; double c6, cnA_ref, cnB_ref; };

#include "dispersion_c6_reference.inc"

// ---- r0ab: D3 ab-initio cut-off radii (bohr) ----------------------------
//
// Packed lower triangle, r0ab[k] for k = Z_A*(Z_A-1)/2 + (Z_B-1) with
// Z_B <= Z_A; the matrix is symmetric. 171 entries covering Z = 1..18.
//
// Provenance (CLAUDE.md §1, §8): grimme-lab/gcp src/gcp.f90 subroutine
// setr0ab (LGPL-3.0-or-later), values / autoang with
// autoang = 0.5291772083. Underlying data: Grimme, Antony, Ehrlich &
// Krieg, J. Chem. Phys. 132, 154104 (2010), doi:10.1063/1.3382344.
//
// This is the Z <= 18 corner of the same 94x94 table already committed as
// python/vibeqc/_d3_r0ab.py (auto-generated by
// scripts/extract_d3_r0ab.py). tests/test_dispersion_atm.py asserts the
// two agree for every supported pair, so they cannot silently drift.
// Only the ATM zero-damping function consumes these radii; the two-body
// BJ damping uses a1·sqrt(C8/C6) + a2 instead.
constexpr std::array<double, 171> kR0ab = {
    4.1239493421,
    3.5048750606, 3.2781079245,
    5.4964574331, 4.8626432878, 6.6057266737,
    4.4503050454, 4.7422677331, 5.6317618243, 5.8547495081,
    4.7509604733, 4.5196579945, 5.6648320317, 5.5716685333,
    6.0773592467,
    4.6283172472, 4.2569860619, 6.0344624635, 5.7096185410,
    5.5805502461, 5.4996699676,
    4.4724148412, 4.0304078984, 5.4393877039, 5.2269824864,
    5.2489033096, 5.1141658362, 4.9558067862,
    4.1135558483, 3.8975601512, 4.9879321305, 5.0357422017,
    5.0043727479, 4.8560292463, 4.6952135523, 4.6897333466,
    3.9015285761, 3.7588542530, 4.7405669796, 5.0848750812,
    4.9573185671, 4.6808516337, 4.5136108709, 4.4429351135,
    4.3456142176,
    3.7590432256, 3.6379117804, 4.5712475180, 4.8136993809,
    4.7231814991, 4.5525392292, 4.3796292880, 4.2653008569,
    4.1471929735, 4.0391006386,
    5.6499031952, 4.9883100757, 6.8088722331, 5.8995360175,
    7.1091497158, 6.1387753460, 5.5476690114, 5.1198350146,
    4.8719029459, 4.6938907440, 7.0074824498,
    4.7486928019, 5.1629207705, 5.8679775911, 6.2289152826,
    5.9207009502, 6.0471236285, 5.5909437398, 5.8245138900,
    5.4012152360, 5.1249372752, 6.1548380182, 6.5836168780,
    5.4359861968, 5.1829518675, 6.1937663765, 6.1157206872,
    6.7895970266, 6.2032150072, 5.8413324526, 5.5499366827,
    5.4858749668, 5.2513599536, 6.4101400189, 6.4193996769,
    7.5789356327,
    5.4582849652, 5.0276163793, 7.0889296462, 5.9739912272,
    6.3504246730, 6.2975123413, 5.8564502616, 5.5363306545,
    5.4186007164, 5.2101639238, 7.2053367760, 6.2863629571,
    7.0118288199, 7.1652745820,
    5.3486808495, 4.8259826008, 6.4122187176, 5.8946227295,
    6.0218012984, 5.9044493054, 5.7570506670, 5.4286162649,
    5.2277383769, 5.0882765882, 6.5399642043, 6.2330726801,
    6.6408755798, 6.6930320211, 6.6172540032,
    4.9491927447, 4.6859538943, 5.9207009502, 5.7712236130,
    5.7921995731, 5.6463127155, 5.4904103095, 5.4433561288,
    5.1646215240, 4.9758378832, 6.0652649994, 6.7402751745,
    6.3653535095, 6.3657314547, 6.2701113124, 6.2563163116,
    4.6783949897, 4.5389332011, 5.6293051803, 5.9465901982,
    5.6253367555, 5.4514819511, 5.2821624895, 5.1886210459,
    5.0797728206, 4.8618873974, 5.7776486819, 6.2859850119,
    6.3422988507, 6.1470901410, 6.0312499290, 5.9569836920,
    5.8668437554,
    4.4833752527, 4.4009831933, 5.4348523612, 5.6321397695,
    5.4977802414, 5.2987920795, 5.1156776171, 4.9862313770,
    4.8603756164, 4.7505825281, 5.5779046295, 5.9726684189,
    6.0631863007, 5.9889200636, 5.8547495081, 5.7356967617,
    5.6181557961, 5.5081737352,
};

}  // namespace

double r2r4(int Z) {
    if (Z < 1 || Z > kMaxSupportedZ) {
        return std::numeric_limits<double>::quiet_NaN();
    }
    return kR2r4[static_cast<std::size_t>(Z)];
}

double d3_r0ab(int ZA, int ZB) {
    if (ZA < 1 || ZA > kMaxSupportedZ || ZB < 1 || ZB > kMaxSupportedZ) {
        return std::numeric_limits<double>::quiet_NaN();
    }
    const int hi = std::max(ZA, ZB);
    const int lo = std::min(ZA, ZB);
    const auto k = static_cast<std::size_t>(hi * (hi - 1) / 2 + (lo - 1));
    return kR0ab[k];
}

double rcov(int Z) {
    if (Z < 1 || Z > kMaxSupportedZ) {
        return std::numeric_limits<double>::quiet_NaN();
    }
    return kRcov[static_cast<std::size_t>(Z)];
}

int max_supported_Z() {
    return kMaxSupportedZ;
}

// Private helpers declared (but not in the public header) in dispersion.cpp.

int c6_num_reference(int ZA, int ZB) {
    const int hi = std::max(ZA, ZB);
    const int lo = std::min(ZA, ZB);
    int n = 0;
    for (const auto& e : kC6ReferenceTable) {
        if (e.ZA == hi && e.ZB == lo) ++n;
    }
    return n;
}

bool c6_reference_grid(int ZA, int ZB,
                       std::vector<std::array<double, 3>>& out) {
    out.clear();
    const int hi = std::max(ZA, ZB);
    const int lo = std::min(ZA, ZB);
    const bool caller_is_canonical = ZA >= ZB;
    for (const auto& e : kC6ReferenceTable) {
        if (e.ZA == hi && e.ZB == lo) {
            if (caller_is_canonical) {
                out.push_back({e.c6, e.cnA_ref, e.cnB_ref});
            } else {
                out.push_back({e.c6, e.cnB_ref, e.cnA_ref});
            }
        }
    }
    return !out.empty();
}

}  // namespace vibeqc
