// Internal pybind surface for testing the native periodic-correlation
// resource planner. The production driver will consume the C++ API directly.

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include "vibeqc/periodic_correlation_resource.hpp"

#ifndef VIBEQC_BINDINGS_HAS_PY_ALIAS
namespace py = pybind11;
#endif

void bind_periodic_correlation_resource(py::module_& m) {
    m.attr("_PERIODIC_CORRELATION_STREAMED_RESOURCE_CONTRACT_VERSION") =
        py::int_(
            vibeqc::kPeriodicCorrelationStreamedResourceContractVersion);
    py::enum_<vibeqc::PeriodicCorrelationEstimateStage>(
        m, "_PeriodicCorrelationEstimateStage")
        .value(
            "STATIC_PREFLIGHT",
            vibeqc::PeriodicCorrelationEstimateStage::StaticPreflight)
        .value(
            "PAIR_DOMAIN_CENSUS",
            vibeqc::PeriodicCorrelationEstimateStage::PairDomainCensus)
        .value(
            "TRIPLE_DOMAIN_CENSUS",
            vibeqc::PeriodicCorrelationEstimateStage::TripleDomainCensus);
    py::enum_<vibeqc::PeriodicCorrelationResourcePhase>(
        m, "_PeriodicCorrelationResourcePhase")
        .value(
            "FACTOR_BUILD",
            vibeqc::PeriodicCorrelationResourcePhase::FactorBuild)
        .value(
            "MEAN_FIELD",
            vibeqc::PeriodicCorrelationResourcePhase::MeanField)
        .value(
            "LOCALIZATION",
            vibeqc::PeriodicCorrelationResourcePhase::Localization)
        .value(
            "DOMAIN_BUILD",
            vibeqc::PeriodicCorrelationResourcePhase::DomainBuild)
        .value(
            "FACTOR_STORE_BUILD",
            vibeqc::PeriodicCorrelationResourcePhase::FactorStoreBuild)
        .value(
            "PAIR_SOLVE",
            vibeqc::PeriodicCorrelationResourcePhase::PairSolve)
        .value(
            "TRIPLE_DOMAIN_BUILD",
            vibeqc::PeriodicCorrelationResourcePhase::TripleDomainBuild)
        .value(
            "TRIPLES",
            vibeqc::PeriodicCorrelationResourcePhase::Triples)
        .value(
            "CHECKPOINT",
            vibeqc::PeriodicCorrelationResourcePhase::Checkpoint);
    py::enum_<vibeqc::PeriodicCorrelationAdmissionCode>(
        m, "_PeriodicCorrelationAdmissionCode")
        .value(
            "READY_FOR_PAIR_DOMAIN_CENSUS",
            vibeqc::PeriodicCorrelationAdmissionCode::
                ReadyForPairDomainCensus)
        .value(
            "READY_FOR_TRIPLE_DOMAIN_CENSUS",
            vibeqc::PeriodicCorrelationAdmissionCode::
                ReadyForTripleDomainCensus)
        .value(
            "ADMITTED",
            vibeqc::PeriodicCorrelationAdmissionCode::Admitted)
        .value(
            "MISSING_MEMORY_LIMIT",
            vibeqc::PeriodicCorrelationAdmissionCode::MissingMemoryLimit)
        .value(
            "MISSING_SCRATCH_LIMIT",
            vibeqc::PeriodicCorrelationAdmissionCode::MissingScratchLimit)
        .value(
            "MEMORY_EXCEEDED",
            vibeqc::PeriodicCorrelationAdmissionCode::MemoryExceeded)
        .value(
            "SCRATCH_EXCEEDED",
            vibeqc::PeriodicCorrelationAdmissionCode::ScratchExceeded)
        .value(
            "ARITHMETIC_OVERFLOW",
            vibeqc::PeriodicCorrelationAdmissionCode::ArithmeticOverflow);

    py::class_<vibeqc::PeriodicCorrelationResourceBudget>(
        m, "_PeriodicCorrelationResourceBudget")
        .def(py::init<>())
        .def_readwrite(
            "memory_limit_bytes",
            &vibeqc::PeriodicCorrelationResourceBudget::memory_limit_bytes)
        .def_readwrite(
            "scratch_limit_bytes",
            &vibeqc::PeriodicCorrelationResourceBudget::scratch_limit_bytes)
        .def_readwrite(
            "mpi_ranks",
            &vibeqc::PeriodicCorrelationResourceBudget::mpi_ranks)
        .def_readwrite(
            "workers_per_rank",
            &vibeqc::PeriodicCorrelationResourceBudget::workers_per_rank);
    py::class_<vibeqc::PeriodicCorrelationTranslationPairCounts>(
        m, "_PeriodicCorrelationTranslationPairCounts")
        .def_readonly(
            "cell_count",
            &vibeqc::PeriodicCorrelationTranslationPairCounts::cell_count)
        .def_readonly(
            "self_inverse_translation_count",
            &vibeqc::PeriodicCorrelationTranslationPairCounts::
                self_inverse_translation_count)
        .def_readonly(
            "candidate_count",
            &vibeqc::PeriodicCorrelationTranslationPairCounts::
                candidate_count)
        .def_readonly(
            "placed_pair_count",
            &vibeqc::PeriodicCorrelationTranslationPairCounts::
                placed_pair_count);
    py::class_<vibeqc::PeriodicCorrelationStaticDimensions>(
        m, "_PeriodicCorrelationStaticDimensions")
        .def(py::init<>())
        .def_readwrite(
            "allocation_contract_version",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                allocation_contract_version)
        .def_readwrite(
            "calculation_identity",
            &vibeqc::PeriodicCorrelationStaticDimensions::calculation_identity)
        .def_readwrite(
            "allocation_identity",
            &vibeqc::PeriodicCorrelationStaticDimensions::allocation_identity)
        .def_readwrite(
            "static_inventory_complete",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                static_inventory_complete)
        .def_readwrite(
            "periodic_dimension",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                periodic_dimension)
        .def_readwrite(
            "mesh",
            &vibeqc::PeriodicCorrelationStaticDimensions::mesh)
        .def_readwrite(
            "is_shift",
            &vibeqc::PeriodicCorrelationStaticDimensions::is_shift)
        .def_readwrite(
            "n_kpoints",
            &vibeqc::PeriodicCorrelationStaticDimensions::n_kpoints)
        .def_readwrite(
            "n_basis",
            &vibeqc::PeriodicCorrelationStaticDimensions::n_basis)
        .def_readwrite(
            "n_effective_orbitals",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                n_effective_orbitals)
        .def_readwrite(
            "n_auxiliary",
            &vibeqc::PeriodicCorrelationStaticDimensions::n_auxiliary)
        .def_readwrite(
            "n_home_total_occupied",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                n_home_total_occupied)
        .def_readwrite(
            "n_home_occupied",
            &vibeqc::PeriodicCorrelationStaticDimensions::n_home_occupied)
        .def_readwrite(
            "n_home_virtual",
            &vibeqc::PeriodicCorrelationStaticDimensions::n_home_virtual)
        .def_readwrite(
            "n_spin_channels",
            &vibeqc::PeriodicCorrelationStaticDimensions::n_spin_channels)
        .def_readwrite(
            "triples_requested",
            &vibeqc::PeriodicCorrelationStaticDimensions::triples_requested)
        .def_readwrite(
            "symmetry_reduction_requested",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                symmetry_reduction_requested)
        .def_readwrite(
            "symmetry_mapping_identity",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                symmetry_mapping_identity)
        .def_readwrite(
            "symmetry_representative_count",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                symmetry_representative_count)
        .def_readwrite(
            "symmetry_weight_sum",
            &vibeqc::PeriodicCorrelationStaticDimensions::symmetry_weight_sum)
        .def_readwrite(
            "expected_pair_candidate_count",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                expected_pair_candidate_count)
        .def_readwrite(
            "expected_triple_candidate_count",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                expected_triple_candidate_count)
        .def_readwrite(
            "factor_k_bra_block",
            &vibeqc::PeriodicCorrelationStaticDimensions::factor_k_bra_block)
        .def_readwrite(
            "factor_k_ket_block",
            &vibeqc::PeriodicCorrelationStaticDimensions::factor_k_ket_block)
        .def_readwrite(
            "factor_q_block",
            &vibeqc::PeriodicCorrelationStaticDimensions::factor_q_block)
        .def_readwrite(
            "factor_auxiliary_block",
            &vibeqc::PeriodicCorrelationStaticDimensions::factor_auxiliary_block)
        .def_readwrite(
            "factor_ao_pair_block",
            &vibeqc::PeriodicCorrelationStaticDimensions::factor_ao_pair_block)
        .def_readwrite(
            "external_bytes",
            &vibeqc::PeriodicCorrelationStaticDimensions::external_bytes)
        .def_readwrite(
            "shared_bytes",
            &vibeqc::PeriodicCorrelationStaticDimensions::shared_bytes)
        .def_readwrite(
            "per_rank_bytes",
            &vibeqc::PeriodicCorrelationStaticDimensions::per_rank_bytes)
        .def_readwrite(
            "localization_window_bytes_per_rank",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                localization_window_bytes_per_rank)
        .def_readwrite(
            "domain_ao_support_upper_bound",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                domain_ao_support_upper_bound)
        .def_readwrite(
            "domain_pao_upper_bound",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                domain_pao_upper_bound)
        .def_readwrite(
            "domain_pno_upper_bound",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                domain_pno_upper_bound)
        .def_readwrite(
            "domain_local_occupied_upper_bound",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                domain_local_occupied_upper_bound)
        .def_readwrite(
            "domain_local_auxiliary_upper_bound",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                domain_local_auxiliary_upper_bound)
        .def_readwrite(
            "pair_domain_metadata_upper_bytes",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                pair_domain_metadata_upper_bytes)
        .def_readwrite(
            "triple_virtual_support_upper_bound",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                triple_virtual_support_upper_bound)
        .def_readwrite(
            "triple_union_pno_upper_bound",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                triple_union_pno_upper_bound)
        .def_readwrite(
            "triple_tno_upper_bound",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                triple_tno_upper_bound)
        .def_readwrite(
            "triple_local_occupied_upper_bound",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                triple_local_occupied_upper_bound)
        .def_readwrite(
            "triple_local_auxiliary_upper_bound",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                triple_local_auxiliary_upper_bound)
        .def_readwrite(
            "triple_domain_metadata_upper_bytes",
            &vibeqc::PeriodicCorrelationStaticDimensions::
                triple_domain_metadata_upper_bytes);

    py::class_<vibeqc::PeriodicCorrelationPairDomain>(
        m, "_PeriodicCorrelationPairDomain")
        .def(py::init<>())
        .def_readwrite(
            "n_pno", &vibeqc::PeriodicCorrelationPairDomain::n_pno)
        .def_readwrite(
            "n_local_occupied",
            &vibeqc::PeriodicCorrelationPairDomain::n_local_occupied)
        .def_readwrite(
            "n_extended_virtual",
            &vibeqc::PeriodicCorrelationPairDomain::n_extended_virtual)
        .def_readwrite(
            "n_local_auxiliary",
            &vibeqc::PeriodicCorrelationPairDomain::n_local_auxiliary);
    py::class_<vibeqc::PeriodicCorrelationTripleDomain>(
        m, "_PeriodicCorrelationTripleDomain")
        .def(py::init<>())
        .def_readwrite(
            "n_tno", &vibeqc::PeriodicCorrelationTripleDomain::n_tno)
        .def_readwrite(
            "n_local_occupied",
            &vibeqc::PeriodicCorrelationTripleDomain::n_local_occupied)
        .def_readwrite(
            "n_local_auxiliary",
            &vibeqc::PeriodicCorrelationTripleDomain::n_local_auxiliary);
    py::class_<vibeqc::PeriodicCorrelationFactorDomain>(
        m, "_PeriodicCorrelationFactorDomain")
        .def(py::init<>())
        .def_readwrite(
            "storage_identity",
            &vibeqc::PeriodicCorrelationFactorDomain::storage_identity)
        .def_readwrite(
            "n_auxiliary",
            &vibeqc::PeriodicCorrelationFactorDomain::n_auxiliary)
        .def_readwrite(
            "n_occupied",
            &vibeqc::PeriodicCorrelationFactorDomain::n_occupied)
        .def_readwrite(
            "n_virtual",
            &vibeqc::PeriodicCorrelationFactorDomain::n_virtual)
        .def_readwrite(
            "header_bytes",
            &vibeqc::PeriodicCorrelationFactorDomain::header_bytes);

    py::class_<vibeqc::PeriodicCorrelationDomainCensus>(
        m, "_PeriodicCorrelationDomainCensus")
        .def(py::init<>())
        .def(
            "add_singles_pno_count",
            [](vibeqc::PeriodicCorrelationDomainCensus& census,
               std::uint64_t count) {
                census.singles_pno_counts.push_back(count);
            })
        .def(
            "add_pair_domain",
            [](vibeqc::PeriodicCorrelationDomainCensus& census,
               const vibeqc::PeriodicCorrelationPairDomain& domain) {
                census.pair_domains.push_back(domain);
            })
        .def(
            "add_triple_domain",
            [](vibeqc::PeriodicCorrelationDomainCensus& census,
               const vibeqc::PeriodicCorrelationTripleDomain& domain) {
                census.triple_domains.push_back(domain);
            })
        .def(
            "add_factor_domain",
            [](vibeqc::PeriodicCorrelationDomainCensus& census,
               const vibeqc::PeriodicCorrelationFactorDomain& domain) {
                census.factor_domains.push_back(domain);
            })
        .def_readwrite(
            "calculation_identity",
            &vibeqc::PeriodicCorrelationDomainCensus::calculation_identity)
        .def_readwrite(
            "allocation_identity",
            &vibeqc::PeriodicCorrelationDomainCensus::allocation_identity)
        .def_readwrite(
            "census_identity",
            &vibeqc::PeriodicCorrelationDomainCensus::census_identity)
        .def_readwrite(
            "pair_domain_census_complete",
            &vibeqc::PeriodicCorrelationDomainCensus::
                pair_domain_census_complete)
        .def_readwrite(
            "singles_pno_counts",
            &vibeqc::PeriodicCorrelationDomainCensus::singles_pno_counts)
        .def_readwrite(
            "pair_domains",
            &vibeqc::PeriodicCorrelationDomainCensus::pair_domains)
        .def_readwrite(
            "triple_domains",
            &vibeqc::PeriodicCorrelationDomainCensus::triple_domains)
        .def_readwrite(
            "factor_domains",
            &vibeqc::PeriodicCorrelationDomainCensus::factor_domains)
        .def_readwrite(
            "symmetry_reduction_used",
            &vibeqc::PeriodicCorrelationDomainCensus::symmetry_reduction_used)
        .def_readwrite(
            "symmetry_mapping_verified",
            &vibeqc::PeriodicCorrelationDomainCensus::
                symmetry_mapping_verified)
        .def_readwrite(
            "symmetry_mapping_identity",
            &vibeqc::PeriodicCorrelationDomainCensus::
                symmetry_mapping_identity)
        .def_readwrite(
            "symmetry_full_kpoint_count",
            &vibeqc::PeriodicCorrelationDomainCensus::
                symmetry_full_kpoint_count)
        .def_readwrite(
            "symmetry_representative_count",
            &vibeqc::PeriodicCorrelationDomainCensus::
                symmetry_representative_count)
        .def_readwrite(
            "symmetry_weight_sum",
            &vibeqc::PeriodicCorrelationDomainCensus::symmetry_weight_sum)
        .def_readwrite(
            "triples_requested",
            &vibeqc::PeriodicCorrelationDomainCensus::triples_requested)
        .def_readwrite(
            "triple_domain_census_complete",
            &vibeqc::PeriodicCorrelationDomainCensus::
                triple_domain_census_complete)
        .def_readwrite(
            "pair_candidate_count",
            &vibeqc::PeriodicCorrelationDomainCensus::pair_candidate_count)
        .def_readwrite(
            "strong_pair_count",
            &vibeqc::PeriodicCorrelationDomainCensus::strong_pair_count)
        .def_readwrite(
            "weak_pair_count",
            &vibeqc::PeriodicCorrelationDomainCensus::weak_pair_count)
        .def_readwrite(
            "neglected_pair_count",
            &vibeqc::PeriodicCorrelationDomainCensus::neglected_pair_count)
        .def_readwrite(
            "factor_manifest_verified",
            &vibeqc::PeriodicCorrelationDomainCensus::
                factor_manifest_verified)
        .def_readwrite(
            "factor_manifest_identity",
            &vibeqc::PeriodicCorrelationDomainCensus::
                factor_manifest_identity)
        .def_readwrite(
            "expected_factor_domain_count",
            &vibeqc::PeriodicCorrelationDomainCensus::
                expected_factor_domain_count)
        .def_readwrite(
            "triple_candidate_count",
            &vibeqc::PeriodicCorrelationDomainCensus::triple_candidate_count)
        .def_readwrite(
            "evaluated_triple_count",
            &vibeqc::PeriodicCorrelationDomainCensus::evaluated_triple_count)
        .def_readwrite(
            "screened_triple_count",
            &vibeqc::PeriodicCorrelationDomainCensus::screened_triple_count)
        .def_readwrite(
            "diis_depth",
            &vibeqc::PeriodicCorrelationDomainCensus::diis_depth)
        .def_readwrite(
            "disk_backed_diis",
            &vibeqc::PeriodicCorrelationDomainCensus::disk_backed_diis)
        .def_readwrite(
            "disk_backed_factors",
            &vibeqc::PeriodicCorrelationDomainCensus::disk_backed_factors)
        .def_readwrite(
            "iterative_triples",
            &vibeqc::PeriodicCorrelationDomainCensus::iterative_triples)
        .def_readwrite(
            "disk_backed_triples",
            &vibeqc::PeriodicCorrelationDomainCensus::disk_backed_triples)
        .def_readwrite(
            "amplitude_replicas",
            &vibeqc::PeriodicCorrelationDomainCensus::amplitude_replicas)
        .def_readwrite(
            "factor_store_replicas",
            &vibeqc::PeriodicCorrelationDomainCensus::factor_store_replicas)
        .def_readwrite(
            "triples_amplitude_replicas",
            &vibeqc::PeriodicCorrelationDomainCensus::
                triples_amplitude_replicas)
        .def_readwrite(
            "checkpoint_replicas",
            &vibeqc::PeriodicCorrelationDomainCensus::checkpoint_replicas)
        .def_readwrite(
            "pair_virtual_block",
            &vibeqc::PeriodicCorrelationDomainCensus::pair_virtual_block)
        .def_readwrite(
            "triple_virtual_block",
            &vibeqc::PeriodicCorrelationDomainCensus::triple_virtual_block)
        .def_readwrite(
            "checkpoint_generations",
            &vibeqc::PeriodicCorrelationDomainCensus::checkpoint_generations)
        .def_readwrite(
            "checkpoint_inventory_complete",
            &vibeqc::PeriodicCorrelationDomainCensus::
                checkpoint_inventory_complete)
        .def_readwrite(
            "checkpoint_includes_factor_store",
            &vibeqc::PeriodicCorrelationDomainCensus::
                checkpoint_includes_factor_store)
        .def_readwrite(
            "checkpoint_provenance_bytes",
            &vibeqc::PeriodicCorrelationDomainCensus::
                checkpoint_provenance_bytes)
        .def_readwrite(
            "factor_regeneration_recipe_bytes",
            &vibeqc::PeriodicCorrelationDomainCensus::
                factor_regeneration_recipe_bytes)
        .def_readwrite(
            "pair_checkpoint_payload_bytes",
            &vibeqc::PeriodicCorrelationDomainCensus::
                pair_checkpoint_payload_bytes)
        .def_readwrite(
            "final_checkpoint_payload_bytes",
            &vibeqc::PeriodicCorrelationDomainCensus::
                final_checkpoint_payload_bytes)
        .def_readwrite(
            "pair_domain_metadata_bytes",
            &vibeqc::PeriodicCorrelationDomainCensus::
                pair_domain_metadata_bytes)
        .def_readwrite(
            "triple_domain_metadata_bytes",
            &vibeqc::PeriodicCorrelationDomainCensus::
                triple_domain_metadata_bytes)
        .def_readwrite(
            "retained_extra_bytes",
            &vibeqc::PeriodicCorrelationDomainCensus::retained_extra_bytes)
        .def_readwrite(
            "checkpoint_write_buffer_extra_bytes",
            &vibeqc::PeriodicCorrelationDomainCensus::
                checkpoint_write_buffer_extra_bytes)
        .def_readwrite(
            "scratch_extra_bytes",
            &vibeqc::PeriodicCorrelationDomainCensus::scratch_extra_bytes);

    py::class_<vibeqc::PeriodicCorrelationPhaseEstimate>(
        m, "_PeriodicCorrelationPhaseEstimate")
        .def_readonly(
            "phase", &vibeqc::PeriodicCorrelationPhaseEstimate::phase)
        .def_readonly(
            "retained_bytes",
            &vibeqc::PeriodicCorrelationPhaseEstimate::retained_bytes)
        .def_readonly(
            "concurrent_worker_bytes",
            &vibeqc::PeriodicCorrelationPhaseEstimate::
                concurrent_worker_bytes)
        .def_readonly(
            "active_workers",
            &vibeqc::PeriodicCorrelationPhaseEstimate::active_workers)
        .def_readonly(
            "peak_memory_bytes",
            &vibeqc::PeriodicCorrelationPhaseEstimate::peak_memory_bytes)
        .def_readonly(
            "scratch_bytes",
            &vibeqc::PeriodicCorrelationPhaseEstimate::scratch_bytes);
    py::class_<vibeqc::PeriodicCorrelationResourcePlan>(
        m, "_PeriodicCorrelationResourcePlan")
        .def_readonly(
            "stage", &vibeqc::PeriodicCorrelationResourcePlan::stage)
        .def_readonly(
            "admission", &vibeqc::PeriodicCorrelationResourcePlan::admission)
        .def_readonly(
            "allocation_contract_version",
            &vibeqc::PeriodicCorrelationResourcePlan::
                allocation_contract_version)
        .def_readonly(
            "calculation_identity",
            &vibeqc::PeriodicCorrelationResourcePlan::calculation_identity)
        .def_readonly(
            "allocation_identity",
            &vibeqc::PeriodicCorrelationResourcePlan::allocation_identity)
        .def_readonly(
            "census_identity",
            &vibeqc::PeriodicCorrelationResourcePlan::census_identity)
        .def_readonly(
            "pair_domain_census_complete",
            &vibeqc::PeriodicCorrelationResourcePlan::
                pair_domain_census_complete)
        .def_readonly(
            "triple_domain_census_complete",
            &vibeqc::PeriodicCorrelationResourcePlan::
                triple_domain_census_complete)
        .def_readonly(
            "modeled_peak_memory_bytes",
            &vibeqc::PeriodicCorrelationResourcePlan::
                modeled_peak_memory_bytes)
        .def_readonly(
            "required_memory_bytes",
            &vibeqc::PeriodicCorrelationResourcePlan::required_memory_bytes)
        .def_readonly(
            "modeled_scratch_bytes",
            &vibeqc::PeriodicCorrelationResourcePlan::modeled_scratch_bytes)
        .def_readonly(
            "required_scratch_bytes",
            &vibeqc::PeriodicCorrelationResourcePlan::required_scratch_bytes)
        .def_readonly(
            "amplitude_bytes",
            &vibeqc::PeriodicCorrelationResourcePlan::amplitude_bytes)
        .def_readonly(
            "factor_store_bytes",
            &vibeqc::PeriodicCorrelationResourcePlan::factor_store_bytes)
        .def_readonly(
            "triples_amplitude_bytes",
            &vibeqc::PeriodicCorrelationResourcePlan::triples_amplitude_bytes)
        .def_readonly(
            "diis_scratch_bytes",
            &vibeqc::PeriodicCorrelationResourcePlan::diis_scratch_bytes)
        .def_readonly(
            "checkpoint_scratch_bytes",
            &vibeqc::PeriodicCorrelationResourcePlan::
                checkpoint_scratch_bytes)
        .def_readonly(
            "unique_factor_domains",
            &vibeqc::PeriodicCorrelationResourcePlan::unique_factor_domains)
        .def_readonly(
            "active_factor_build_workers",
            &vibeqc::PeriodicCorrelationResourcePlan::
                active_factor_build_workers)
        .def_readonly(
            "active_mean_field_workers",
            &vibeqc::PeriodicCorrelationResourcePlan::
                active_mean_field_workers)
        .def_readonly(
            "active_domain_build_workers",
            &vibeqc::PeriodicCorrelationResourcePlan::
                active_domain_build_workers)
        .def_readonly(
            "active_factor_store_build_workers",
            &vibeqc::PeriodicCorrelationResourcePlan::
                active_factor_store_build_workers)
        .def_readonly(
            "active_pair_workers",
            &vibeqc::PeriodicCorrelationResourcePlan::active_pair_workers)
        .def_readonly(
            "active_triple_domain_build_workers",
            &vibeqc::PeriodicCorrelationResourcePlan::
                active_triple_domain_build_workers)
        .def_readonly(
            "active_triple_workers",
            &vibeqc::PeriodicCorrelationResourcePlan::active_triple_workers)
        .def_readonly(
            "phases", &vibeqc::PeriodicCorrelationResourcePlan::phases)
        .def_readonly(
            "failure_detail",
            &vibeqc::PeriodicCorrelationResourcePlan::failure_detail);

    m.def(
        "_plan_periodic_correlation_static_resources",
        &vibeqc::plan_periodic_correlation_static_resources,
        py::arg("dimensions"),
        py::arg("budget"));
    m.def(
        "_plan_periodic_correlation_domain_resources",
        &vibeqc::plan_periodic_correlation_domain_resources,
        py::arg("dimensions"),
        py::arg("census"),
        py::arg("budget"));
    m.def(
        "_estimate_periodic_dense_gdf_cache_bytes",
        &vibeqc::estimate_periodic_dense_gdf_cache_bytes,
        py::arg("n_kpairs"),
        py::arg("n_auxiliary"),
        py::arg("n_basis"));
    m.def(
        "_estimate_periodic_streamed_factor_tile_bytes",
        &vibeqc::estimate_periodic_streamed_factor_tile_bytes,
        py::arg("k_bra_block"),
        py::arg("k_ket_block"),
        py::arg("auxiliary_block"),
        py::arg("ao_pair_block"));
    m.def(
        "_estimate_periodic_correlation_translation_pair_counts",
        &vibeqc::estimate_periodic_correlation_translation_pair_counts,
        py::arg("mesh"),
        py::arg("n_home_occupied"));
    m.def(
        "_periodic_occupied_triple_count",
        &vibeqc::periodic_occupied_triple_count,
        py::arg("n_occupied"));
    m.def(
        "_periodic_correlation_bytes_to_mib_ceil",
        &vibeqc::periodic_correlation_bytes_to_mib_ceil,
        py::arg("bytes"));
}
