"""Crystallographic Information File (CIF) writer.

CIF (IUCr standard, ``.cif`` extension) is the de-facto interchange
format for crystallographic data: every crystallography toolkit
(pymatgen, ASE, VESTA, Materials Project, Crystallography Open
Database, RIETAN, GSAS-II) reads it natively. POSCAR + XSF already
cover the VASP / VESTA / XCrySDen audience that lands first in
vibe-qc's periodic output family; CIF reaches the broader
crystallography community + materials databases.

This writer emits a minimal-but-complete CIF 1.1 document carrying:

* Cell parameters (``_cell_length_a/b/c`` in Å,
  ``_cell_angle_alpha/beta/gamma`` in degrees, ``_cell_volume`` in
  Å^3).
* Space group (``_symmetry_space_group_name_H-M = "P 1"`` -- vibe-qc
  doesn't currently reduce to a higher symmetry on output; everything
  is in P1 with explicit symmetry-equivalent positions).
* The single ``x,y,z`` symmetry operation in
  ``_symmetry_equiv_pos_as_xyz``.
* Per-atom records in the ``_atom_site_*`` loop: label, symbol,
  fractional coordinates.

The output is text-only, no semicolons / multi-line strings, no
fancy ``_atom_site_aniso_U_iso`` extensions -- what every CIF
reader treats as the lowest-common-denominator interpretation.
A vibe-qc provenance comment block opens the file so downstream
users know which run produced the structure.

Public API
----------

``write_cif(stem, system, *, comment=None)`` -> ``Path``
    Write ``{stem}.cif``. Returns the on-disk path.

``format_cif(system, *, comment=None)`` -> ``str``
    Render the same content as a string. Used by the dispatcher
    adapter and by callers that want to embed CIF text in a larger
    artefact (e.g. an HTML report).
"""

from __future__ import annotations

import math
import os
from pathlib import Path
from typing import Any

import numpy as np

from .xyz import BOHR_TO_ANGSTROM, _symbol
from .._text_safety import scrub_output_text
from .._stem_paths import stem_sibling


__all__ = ["write_cif", "format_cif"]


def write_cif(
    stem: os.PathLike | str,
    system: Any,
    *,
    comment: str | None = None,
) -> Path:
    """Write ``{stem}.cif`` from a :class:`PeriodicSystem`.

    Parameters
    ----------
    stem
        Path stem; ``.cif`` is appended.
    system
        Anything with ``.lattice`` (3x3 array, columns = lattice
        vectors in bohr) and ``.unit_cell`` (iterable of atoms with
        ``.Z`` / ``.xyz`` in bohr).
    comment
        Optional first-line provenance string. Defaults to a
        vibe-qc-branded provenance line.
    """
    target = stem_sibling(stem, ".cif")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        format_cif(system, comment=comment), encoding="utf-8",
    )
    return target


def format_cif(
    system: Any,
    *,
    comment: str | None = None,
) -> str:
    """Render the CIF-formatted string for ``system``."""
    lattice_bohr = np.asarray(system.lattice, dtype=float)
    lattice_A = lattice_bohr * BOHR_TO_ANGSTROM   # columns = vectors

    # Cell parameters (a, b, c, alpha, beta, gamma) from the column-
    # vector lattice. a = |column 0|, b = |column 1|, c = |column 2|;
    # alpha = angle(b, c), beta = angle(a, c), gamma = angle(a, b).
    a_vec = lattice_A[:, 0]
    b_vec = lattice_A[:, 1]
    c_vec = lattice_A[:, 2]
    a = float(np.linalg.norm(a_vec))
    b = float(np.linalg.norm(b_vec))
    c = float(np.linalg.norm(c_vec))

    def _angle_deg(u: np.ndarray, v: np.ndarray) -> float:
        denom = float(np.linalg.norm(u) * np.linalg.norm(v))
        if denom == 0.0:
            return 90.0
        cos = max(-1.0, min(1.0,
                              float(np.dot(u, v)) / denom))
        return math.degrees(math.acos(cos))

    alpha = _angle_deg(b_vec, c_vec)
    beta = _angle_deg(a_vec, c_vec)
    gamma = _angle_deg(a_vec, b_vec)
    volume = float(abs(np.linalg.det(lattice_A)))

    # Fractional coordinates: frac = inv(lattice_A) @ cart_A^T,
    # transposed back to one row per atom.
    atoms = list(system.unit_cell)
    cart_A = np.array([list(a.xyz) for a in atoms], dtype=float) \
        * BOHR_TO_ANGSTROM
    if cart_A.size == 0:
        frac = np.empty((0, 3), dtype=float)
    else:
        frac = (np.linalg.inv(lattice_A) @ cart_A.T).T

    # The CIF header carries the comment on a `# ...` line; scrub bidi /
    # zero-width / control chars from the user value (see _text_safety).
    header_comment = scrub_output_text(comment or "vibe-qc periodic structure")

    lines: list[str] = [
        f"# {header_comment}",
        "# Generated by vibe-qc (vibeqc.output.formats.cif). Space",
        "# group is fixed to P 1; explicit symmetry operations are",
        "# the identity. Cell parameters in Å / degrees.",
        "",
        "data_vibeqc",
        "_audit_creation_method        'vibe-qc'",
        f"_cell_length_a               {a:.10f}",
        f"_cell_length_b               {b:.10f}",
        f"_cell_length_c               {c:.10f}",
        f"_cell_angle_alpha            {alpha:.6f}",
        f"_cell_angle_beta             {beta:.6f}",
        f"_cell_angle_gamma            {gamma:.6f}",
        f"_cell_volume                 {volume:.10f}",
        "_symmetry_space_group_name_H-M  'P 1'",
        "_symmetry_Int_Tables_number  1",
        "",
        "loop_",
        "_symmetry_equiv_pos_site_id",
        "_symmetry_equiv_pos_as_xyz",
        "1 'x, y, z'",
        "",
        "loop_",
        "_atom_site_label",
        "_atom_site_type_symbol",
        "_atom_site_fract_x",
        "_atom_site_fract_y",
        "_atom_site_fract_z",
        "_atom_site_occupancy",
    ]

    # Per-atom labels: append a 1-based index per element so multiple
    # atoms of the same element get unique site labels (Mg1 / O1 /
    # Mg2 / O2). The order of atoms in the unit cell is preserved.
    per_element_count: dict[str, int] = {}
    for atom_idx, atom in enumerate(atoms):
        sym = _symbol(int(atom.Z))
        per_element_count[sym] = per_element_count.get(sym, 0) + 1
        label = f"{sym}{per_element_count[sym]}"
        fx, fy, fz = frac[atom_idx]
        lines.append(
            f"{label:<8s} {sym:<3s} "
            f"{fx:.10f} {fy:.10f} {fz:.10f}  1.0"
        )

    lines.append("")
    return "\n".join(lines)
