"""POSCAR writer -- VASP 5 lattice + atoms, direct (fractional) coords.

POSCAR is the de-facto interchange format for periodic structures
across crystal-chemistry tooling (VASP itself, pymatgen, ASE, p4vasp,
VESTA, ...). vibe-qc already has a POSCAR *reader* in
:mod:`vibeqc.poscar` that uses the native ``Crystal`` type; this
writer is the symmetric direction for the output module, taking a
:class:`vibeqc.PeriodicSystem` directly so it works without needing
to materialise a ``Crystal`` object (which lives in the C++ core).

File layout (VASP 5):

.. code-block:: text

    <comment line>
    1.0                    <- scale factor
    ax ay az               <- lattice vector a (Å)
    bx by bz               <- lattice vector b (Å)
    cx cy cz               <- lattice vector c (Å)
    El1 El2 ...            <- element symbols (VASP 5)
    n1  n2  ...            <- atom counts per species (in the same order)
    Direct                 <- coords mode
    fx fy fz               <- fractional coords, one per atom
    ...

The element-symbol line orders species by first occurrence so the
file round-trips :func:`vibeqc.poscar.read_poscar`.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import numpy as np

from .xyz import BOHR_TO_ANGSTROM, _symbol
from .._text_safety import scrub_output_text
from .._stem_paths import stem_sibling


__all__ = ["write_poscar", "format_poscar"]


def write_poscar(
    stem: os.PathLike | str,
    system: Any,
    *,
    comment: str | None = None,
    suffix: str = ".POSCAR",
) -> Path:
    """Write ``{stem}.POSCAR`` (or whatever suffix is requested) from
    a :class:`PeriodicSystem`.

    Parameters
    ----------
    stem
        Path stem; the configured ``suffix`` is appended.
    system
        Anything with ``.lattice`` (3x3 array, columns = vectors,
        bohr) and ``.unit_cell`` (iterable of atoms with ``.Z`` /
        ``.xyz`` in bohr).
    comment
        First-line comment. Defaults to a vibe-qc provenance string.
    suffix
        Default ``".POSCAR"``. Some workflows prefer the bare name
        ``"POSCAR"`` (no extension) -- pass ``suffix=""`` to get
        ``{stem}`` with no suffix appended at all.
    """
    s = Path(os.fspath(stem))
    target = stem_sibling(s, suffix) if suffix else s.with_name(
        s.name + "_POSCAR",
    )
    if suffix == "":
        # Match VASP's convention of a bare-name POSCAR file by writing
        # to ``{stem}.POSCAR`` even when suffix="" -- the alternate
        # branch above uses ``_POSCAR`` only when the stem already
        # carries another suffix that would conflict.
        target = s.parent / "POSCAR"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(format_poscar(system, comment=comment),
                      encoding="utf-8")
    return target


def format_poscar(system: Any, *, comment: str | None = None) -> str:
    """Return the POSCAR-formatted string for ``system``."""
    # POSCAR line 1 is a free-text comment; scrub bidi / zero-width /
    # control chars from the user value (see vibeqc.output._text_safety).
    head = scrub_output_text(comment or "generated by vibe-qc (PeriodicSystem)")
    lattice = np.asarray(system.lattice, dtype=float)  # columns = vectors
    lattice_A = lattice * BOHR_TO_ANGSTROM

    atoms = list(system.unit_cell)
    z_list = [int(a.Z) for a in atoms]
    xyz_bohr = np.array([list(a.xyz) for a in atoms], dtype=float)  # (N, 3)

    # Group atoms by Z, preserving first-occurrence order.
    seen: list[int] = []
    for z in z_list:
        if z not in seen:
            seen.append(z)
    counts = [z_list.count(z) for z in seen]
    syms = [_symbol(z) for z in seen]

    # Reorder atoms so the per-species blocks are contiguous.
    order = [i for z in seen for i, zz in enumerate(z_list) if zz == z]
    xyz_grouped = xyz_bohr[order]

    # Cartesian (bohr) -> fractional. The lattice has *columns* as
    # vectors, so frac = inv(lattice) @ cart_columns; transpose at the
    # end to get one row per atom.
    inv_lat_A = np.linalg.inv(lattice_A)
    cart_A = xyz_grouped * BOHR_TO_ANGSTROM
    frac = (inv_lat_A @ cart_A.T).T  # (N, 3)

    lines: list[str] = [head, "1.0"]
    # POSCAR convention: each line is a lattice vector (rows = vectors).
    # Our lattice_A has columns = vectors, so write the columns out.
    for i in range(3):
        v = lattice_A[:, i]
        lines.append(f"  {v[0]:.16f}  {v[1]:.16f}  {v[2]:.16f}")
    lines.append("  " + "  ".join(syms))
    lines.append("  " + "  ".join(str(c) for c in counts))
    lines.append("Direct")
    for r in frac:
        lines.append(f"  {r[0]:.16f}  {r[1]:.16f}  {r[2]:.16f}")
    return "\n".join(lines) + "\n"
