"""run_job wiring for MS/XMS-CASPT2 (caspt2_options.multistate).

Engine-level validation (machine-precision invariants + OpenMolcas parity)
lives in tests/test_ms_caspt2.py; this file pins the public composition:
option validation, dispatch, labels, root surfacing, the .out multi-state
block, and the citation routes.

The CASCI-on-HF reference path (no casscf_options) is directly comparable
to the recorded OpenMolcas constants (same HF orbitals, CIonly multi-root
reference); the run_job energies are pinned against _OM_MS values here.
"""

from __future__ import annotations

import numpy as np
import pytest
from vibeqc import Atom, Molecule
from vibeqc.runner import run_job
from vibeqc.solvers import CASPT2Options, CASSCFOptions

LIH = Molecule([Atom(3, [0.0, 0.0, 0.0]), Atom(1, [0.0, 0.0, 3.0])])

# Recorded OpenMolcas MS/XMS-CASPT2 roots for LiH/STO-3G CAS(2,2) R=3.0
# (CIonly SA2 reference on HF orbitals, IPEA=0, Frozen=0); same constants
# as tests/test_ms_caspt2.py::_OM_MS, regenerated by
# examples/regression/core/runner_openmolcas.py.
_OM_LIH_MS = [-7.87549608, -7.74216873]
_OM_LIH_XMS = [-7.87715367, -7.74081346]
# Recorded OpenMolcas full &RASSCF (ci_only=False) SA2-CASSCF composition,
# same system (run_caspt2(..., nroots=2, multistate=..., ci_only=False),
# 2026-06-10): the standard SA-CASSCF -> MS/XMS-CASPT2 workflow, reachable
# in vibe-qc because the spin-pure SA-CASSCF averages the same two singlet
# roots OpenMolcas's CSF-based RASSCF averages.
_OM_LIH_CASSCF_MS = [-7.87378264, -7.74506130]
_OM_LIH_CASSCF_XMS = [-7.87656489, -7.74500383]
_OM_TOL = 5e-6


def _run(tmp_path, name, **kw):
    return run_job(
        LIH,
        basis="sto-3g",
        method="caspt2",
        active_space=(2, 2),
        output=tmp_path / name,
        write_molden_file=False,
        write_xyz_file=False,
        write_population_file=False,
        **kw,
    )


class TestRunJobMultistate:
    def test_ms_on_casci_reference_matches_openmolcas(self, tmp_path):
        res = _run(
            tmp_path,
            "ms",
            citations=False,
            caspt2_options=CASPT2Options(multistate="ms", nroots=2),
        )
        assert res.method.endswith("_ms2")
        assert res.converged
        assert res.root_energies is not None and len(res.root_energies) == 2
        assert np.abs(np.asarray(res.root_energies) - _OM_LIH_MS).max() < _OM_TOL
        assert abs(res.energy - _OM_LIH_MS[0]) < _OM_TOL
        ms = res.multistate
        assert ms is not None and ms["mode"] == "ms" and ms["nroots"] == 2
        # SS diagonal of the asymmetric Heff = ref + E2 (consistency)
        assert np.allclose(
            np.asarray(ms["ss_energies"]),
            np.asarray(ms["ref_energies"]) + np.asarray(ms["e2_corr"]),
            atol=1e-12,
        )

    def test_xms_on_casci_reference_matches_openmolcas(self, tmp_path):
        res = _run(
            tmp_path,
            "xms",
            citations=False,
            caspt2_options=CASPT2Options(multistate="xms", nroots=2),
        )
        assert res.method.endswith("_xms2")
        assert np.abs(np.asarray(res.root_energies) - _OM_LIH_XMS).max() < _OM_TOL
        u = np.asarray(res.multistate["xms_rotation"])
        assert np.allclose(u.T @ u, np.eye(2), atol=1e-12)

    @pytest.mark.parametrize(
        "mode,ref",
        [("ms", _OM_LIH_CASSCF_MS), ("xms", _OM_LIH_CASSCF_XMS)],
    )
    def test_sa_casscf_composition_matches_openmolcas(self, tmp_path, mode, ref):
        # The standard SA-CASSCF -> MS/XMS-CASPT2 composition vs OpenMolcas
        # full &RASSCF + &CASPT2 MULTistate/XMULtistate.  nroots inherits
        # casscf_options.nroots, and CASSCFOptions.spin_pure=None resolves
        # to True for multi-state compositions, so the SA orbitals average
        # the same two singlets as OpenMolcas's CSF-based RASSCF.
        res = _run(
            tmp_path,
            f"{mode}_casscf",
            citations=False,
            caspt2_options=CASPT2Options(multistate=mode),
            casscf_options=CASSCFOptions(nroots=2),
        )
        assert res.method.endswith(f"_{mode}2_casscf")
        assert np.abs(np.asarray(res.root_energies) - ref).max() < _OM_TOL
        # multi-state ground root must lie below the SA-CASSCF reference
        assert res.energy < res.multistate["ref_energies"][0]

    def test_sa_casscf_spin_pure_override(self, tmp_path):
        # spin_pure=False forces the historical spin-mixed SA averaging even
        # under a multi-state composition: the model space downstream is
        # still spin-filtered (the job runs), but the orbitals differ from
        # the OM-pinned singlet-averaged ones.
        res = _run(
            tmp_path,
            "ms_casscf_mixed",
            citations=False,
            caspt2_options=CASPT2Options(multistate="ms"),
            casscf_options=CASSCFOptions(nroots=2, spin_pure=False),
        )
        assert res.method.endswith("_ms2_casscf")
        diff = np.abs(np.asarray(res.root_energies) - _OM_LIH_CASSCF_MS).max()
        assert diff > 1e-4  # spin-mixed SA orbitals: a genuinely different reference

    def test_out_block_and_citations(self, tmp_path):
        res = _run(
            tmp_path,
            "msout",
            citations=True,
            caspt2_options=CASPT2Options(multistate="xms", nroots=2),
        )
        assert res.multistate is not None
        out_text = (tmp_path / "msout.out").read_text()
        assert "XMS-CASPT2 (2 states):" in out_text
        assert "effective Hamiltonian (symmetrized, Ha):" in out_text
        assert "mixing (column k = multi-state root k):" in out_text
        assert "XMS model-space rotation U" in out_text
        bib = (tmp_path / "msout.bibtex").read_text()
        for key in (
            "finley_ms_caspt2_1998",
            "granovsky_xmcqdpt2_2011",
            "shiozaki_xms_caspt2_2011",
        ):
            assert key in bib, f"{key} missing from .bibtex"
        refs = (tmp_path / "msout.references").read_text()
        assert "multi-state CASPT2" in refs

    def test_ms_mode_cites_finley_only(self, tmp_path):
        res = _run(
            tmp_path,
            "mscite",
            citations=True,
            caspt2_options=CASPT2Options(multistate="ms", nroots=2),
        )
        assert res.multistate["mode"] == "ms"
        bib = (tmp_path / "mscite.bibtex").read_text()
        assert "finley_ms_caspt2_1998" in bib
        assert "granovsky_xmcqdpt2_2011" not in bib
        assert "shiozaki_xms_caspt2_2011" not in bib
        # CASCI-referenced MS run carries no gradient -> no gradient papers
        assert res.gradient is None
        assert "stalring_sa_mcscf_gradient_2001" not in bib

    def test_ms_gradient_cites_sa_lagrangian_papers(self, tmp_path):
        # SA-CASSCF-referenced MS run computes the relaxed gradient and
        # must cite the gradient formalism (Stalring 2001 SA-MCSCF
        # z-vector + Celani-Werner 2003 CASPT2 gradient Lagrangian).
        res = _run(
            tmp_path,
            "msgradcite",
            citations=True,
            caspt2_options=CASPT2Options(
                multistate="ms", nroots=2, compute_corr_grad=True
            ),
            casscf_options=CASSCFOptions(nroots=2, weights=[0.5, 0.5]),
        )
        assert res.gradient is not None
        bib = (tmp_path / "msgradcite.bibtex").read_text()
        assert "stalring_sa_mcscf_gradient_2001" in bib
        assert "celani_werner_2003" in bib

    def test_single_state_gradient_cites_caspt2_lagrangian(self, tmp_path):
        res = _run(
            tmp_path,
            "ssgradcite",
            citations=True,
            caspt2_options=CASPT2Options(compute_corr_grad=True),
            casscf_options=CASSCFOptions(),
        )
        assert res.gradient is not None
        bib = (tmp_path / "ssgradcite.bibtex").read_text()
        assert "celani_werner_2003" in bib
        assert "stalring_sa_mcscf_gradient_2001" not in bib

    def test_invalid_multistate_options(self, tmp_path):
        with pytest.raises(ValueError, match="model states"):
            _run(
                tmp_path,
                "noroots",
                citations=False,
                caspt2_options=CASPT2Options(multistate="ms"),
            )
        with pytest.raises(ValueError, match="multistate"):
            _run(
                tmp_path,
                "badmode",
                citations=False,
                caspt2_options=CASPT2Options(multistate="bogus", nroots=2),
            )
        with pytest.raises(ValueError, match="ipea"):
            _run(
                tmp_path,
                "ipea",
                citations=False,
                caspt2_options=CASPT2Options(
                    multistate="ms", nroots=2, ipea=0.25
                ),
            )
        with pytest.raises(ValueError, match="variant"):
            _run(
                tmp_path,
                "scvar",
                citations=False,
                caspt2_options=CASPT2Options(
                    multistate="ms", nroots=2, variant="sc"
                ),
            )
