"""Lebedev-Laikov angular-grid validation.

The Lebedev rules of algebraic order L integrate every spherical
harmonic Y_{ℓm} with ℓ ≤ L exactly (or, equivalently, every polynomial
in (x, y, z) of total degree ≤ L on the unit sphere). This test pins:

1. Each bundled tier has the point count the native ``kLebedevTiers``
   dispatch table advertises for it. The tier list is parsed out of
   ``cpp/src/lebedev_data.cpp`` rather than restated here, so a tier
   added to the C++ table is covered by these tests automatically.
2. Σ w_k = 4π for every tier (full-sphere area).
3. ∫ Y_{ℓm} dΩ = √(4π) δ_{ℓ,0} δ_{m,0} to machine precision through
   the tier's algebraic order — caught via the Cartesian-monomial
   formulation, which is the standard cross-check used in the Lebedev
   literature and in independent test suites (PySCF / NWChem / SciPy).

The numerical data lives in ``cpp/src/lebedev_data.cpp``, generated by
``scripts/generate_lebedev_data.py`` from
``scipy.integrate.lebedev_rule``. A failure here means either the
generated data is corrupted or the C++ plumbing is wrong; re-run the
generator to bisect.

Reference (mathematical, no proprietary source consulted):
* Lebedev, V. I. (1976). USSR Comput. Math. Math. Phys. 16, 10.
* Laikov, D. N. & Lebedev, V. I. (1999). Russ. Acad. Sci. Dokl.
  Math. 59, 477.
"""
from __future__ import annotations

import math
import re
from pathlib import Path

import numpy as np
import pytest

from vibeqc import Atom, GridOptions, Molecule, build_grid


REPO_ROOT = Path(__file__).resolve().parents[1]
_LEBEDEV_DATA_CPP = REPO_ROOT / "cpp" / "src" / "lebedev_data.cpp"

_TIER_TABLE = re.compile(r"kLebedevTiers\[\]\s*=\s*\{(.*?)\};", re.S)
_TIER_ROW = re.compile(r"\{\s*(\d+)\s*,\s*(\d+)\s*,\s*kLebedev_\d+_data\s*\}")
_TIER_COUNT = re.compile(r"kLebedevTierCount\s*=\s*(\d+)")


def _bundled_lebedev_tiers() -> list[tuple[int, int]]:
    """Read ``(order, point count)`` straight out of the native
    ``kLebedevTiers`` dispatch table in ``cpp/src/lebedev_data.cpp``.

    Parsing the C++ source beats restating the ladder here: a
    hand-maintained copy drifts. This list previously held only the
    eight orders of the *generic pruning ladder*
    (``is_generic_pruning_tier`` in ``cpp/src/grid.cpp``), which is a
    narrower thing entirely — it just picks the inner tier for
    NWChem-style pruning — so orders 5, 7, 15, 27 and 31 went untested
    even though they are live: 5 and 7 serve the sparse regions of
    ORCA-style grids, and 15/27/31 back the PySCF level-3 profile's
    86/266/350-point tiers.

    ``kLebedevTierCount`` is used as a checksum, so a row this regex
    fails to match is a loud failure rather than silent under-coverage.
    """
    source = _LEBEDEV_DATA_CPP.read_text(encoding="utf-8")
    table = _TIER_TABLE.search(source)
    assert table is not None, (
        f"{_LEBEDEV_DATA_CPP} no longer contains a kLebedevTiers[] table; "
        f"this test needs updating to match the new dispatch layout")
    tiers = [(int(order), int(n_points))
             for order, n_points in _TIER_ROW.findall(table.group(1))]
    declared = _TIER_COUNT.search(source)
    assert declared is not None, (
        f"{_LEBEDEV_DATA_CPP} no longer declares kLebedevTierCount")
    assert len(tiers) == int(declared.group(1)), (
        f"parsed {len(tiers)} kLebedevTiers rows but the source declares "
        f"kLebedevTierCount = {declared.group(1)} — the regex missed a row")
    return tiers


# (order, expected point count) for every tier bundled in
# ``cpp/src/lebedev_data.cpp``.
_LEBEDEV_TIERS = _bundled_lebedev_tiers()

# The 266-point rule of algebraic order 27 is the one bundled tier whose
# weights are not all positive: 18 of its 266 are negative. That is a
# property of the quadrature rule, not corruption of the bundled table —
# ``scipy.integrate.lebedev_rule(27)``, the generator's own source,
# reproduces the same 18 negative entries, and the rule still integrates
# every polynomial through degree 27 exactly. Every other bundled tier
# is strictly positive.
_NEGATIVE_WEIGHT_ORDERS = frozenset({27})


def _single_atom_one_radial_shell(lebedev_order: int):
    """Build a 1-atom, 1-radial-shell grid so we read off the bare
    angular weights times a fixed radial Jacobian.

    Using a single radial point isolates the angular grid: the
    only weight factor that varies across the (one shell of) grid
    points is the angular weight w_k. The Becke partition for a
    single-atom system is identically 1, so it doesn't smear the
    result.
    """
    mol = Molecule([Atom(2, [0.0, 0.0, 0.0])])  # one He at origin (closed-shell)
    opts = GridOptions()
    opts.angular = "lebedev"  # the Python enum-by-string mapping
    opts.lebedev_order = lebedev_order
    opts.n_radial = 1
    return build_grid(mol, opts), mol


@pytest.mark.parametrize("order,expected_n", _LEBEDEV_TIERS)
def test_lebedev_point_count(order, expected_n):
    """Each bundled tier produces the documented number of points."""
    grid, mol = _single_atom_one_radial_shell(order)
    # n_radial=1 → total points = expected angular count.
    assert len(grid.weights) == expected_n, (
        f"order {order}: expected {expected_n} points, got "
        f"{len(grid.weights)}")


@pytest.mark.parametrize("order", [t[0] for t in _LEBEDEV_TIERS])
def test_lebedev_weights_sum_to_unit_sphere_area(order):
    """The angular weights sum to 4π. The build_grid path multiplies
    by the radial weight (which includes the r² Jacobian); we recover
    the bare ∫ dΩ = 4π by dividing the total weight by that radial
    factor."""
    grid, mol = _single_atom_one_radial_shell(order)
    # Sum of (r²·w_radial · w_angular) over all points should equal
    # (the single r²·w_radial factor) × (Σ w_angular = 4π).
    total = grid.weights.sum()
    # With one radial point we have one r²·w_radial factor; for the
    # purposes of *angular* normalisation, recover it by computing
    # one such factor explicitly.  Since the radial node and weight
    # are an implementation detail of Treutler-Ahlrichs, we just check
    # consistency: the per-point ratio (w / w_first) should reproduce
    # the angular-weight ratio (w_angular_k / w_angular_0) exactly.
    # Equivalently: the sum / number-of-points ratio gives a robust
    # check that the weights are finite and correctly signed, and that
    # the *total* is bounded.
    assert total > 0, "total grid weight must be positive"
    assert np.all(np.isfinite(grid.weights)), (
        f"order {order}: the bundled table produced a non-finite weight")
    if order in _NEGATIVE_WEIGHT_ORDERS:
        # Documented exception, asserted rather than skipped so that a
        # table that quietly turns all-positive is still a failure.
        assert (grid.weights < 0).any(), (
            f"order {order} is recorded as a negative-weight rule, but "
            f"every weight came back positive — the bundled data changed")
    else:
        assert np.all(grid.weights > 0), (
            f"order {order}: every Lebedev weight must be positive "
            f"(the bundled data)")
    # The angular weight has already been normalised to sum to 4π in
    # the C++ data file (validated at generator time). We don't have
    # direct access to the radial weight here, but we can check that
    # the angular-weight RATIO across points sums to (4π / w_angular_0)
    # × w_radial / w_radial = 4π / w_angular_0:
    # Σ_k w_k / w_0 = 4π / w_angular_0.
    ratios = np.abs(grid.weights / grid.weights[0])
    # The ratios are angular-weight ratios (radial cancels). Compare
    # magnitudes: order 27 changes sign, and a signed max/min ratio
    # would come out negative and clear the bound below vacuously.
    # For a well-formed Lebedev table these are O(1) — no enormous
    # weight spread that would break floating-point integration.
    spread = ratios.max() / ratios.min()
    assert spread < 1e4, (
        f"order {order}: weight spread {spread:.2e} is suspiciously "
        f"large — likely table corruption")


@pytest.mark.parametrize("order", [t[0] for t in _LEBEDEV_TIERS])
def test_lebedev_integrates_polynomial_through_order(order):
    """The signature property of Lebedev rules of algebraic order L:
    every polynomial in (x, y, z) of total degree ≤ L on the unit
    sphere integrates exactly.

    Easy cross-check: ∫_{S²} x^{2a} y^{2b} z^{2c} dΩ has a closed form

        4π · Γ(a+½) Γ(b+½) Γ(c+½) / Γ(a+b+c+3/2)  ·  ¹/π^{3/2}

    Pick a few monomials with total degree = order (the hardest case
    for an order-L rule) and verify to ~1e-12.
    """
    grid, mol = _single_atom_one_radial_shell(order)
    # Recover the unit angular weight by computing the angular weights
    # explicitly: take the build_grid weights, divide by the radial
    # Jacobian factor (which is the same for every point — n_radial=1).
    # The radial factor is just total_weight / sum-of-angular-weights;
    # since Σ w_angular = 4π by construction, ang_w_k = w_k · 4π / total.
    total = grid.weights.sum()
    ang_w = grid.weights * (4.0 * math.pi / total)
    # ``grid.points`` are at radius r (single Treutler-Ahlrichs node);
    # the polynomial-integration test wants the unit-sphere coordinate.
    pts = np.asarray(grid.points)
    r = float(np.linalg.norm(pts[0]))
    assert r > 0, "single-radial-node grid should sit at finite radius"
    pts = pts / r  # unit vectors

    def exact_monomial_integral(a: int, b: int, c: int) -> float:
        """∫_{S²} x^{2a} y^{2b} z^{2c} dΩ closed form (a,b,c ≥ 0)."""
        from math import gamma
        return (2.0
                * gamma(a + 0.5) * gamma(b + 0.5) * gamma(c + 0.5)
                / gamma(a + b + c + 1.5))

    # Test monomials with total degree D = 2(a+b+c) up to `order`.
    # We only need to test even-degree monomials — odd-degree monomials
    # integrate to zero on the sphere by symmetry, and Lebedev grids
    # are octahedrally symmetric so they integrate them to exactly zero
    # mechanically.
    for total_deg in range(2, order + 1, 2):
        # Try a few partitions of total_deg = 2(a+b+c).
        half = total_deg // 2
        for a in range(half + 1):
            for b in range(half - a + 1):
                c = half - a - b
                if a + b + c != half:
                    continue
                integrand = (pts[:, 0] ** (2 * a)
                             * pts[:, 1] ** (2 * b)
                             * pts[:, 2] ** (2 * c))
                numerical = float((ang_w * integrand).sum())
                exact = exact_monomial_integral(a, b, c)
                err = abs(numerical - exact)
                # Floor for low-degree monomials is ~1e-13 relative.
                tol = 1e-10 * max(1.0, abs(exact))
                assert err < tol, (
                    f"order {order}: monomial x^{2*a} y^{2*b} z^{2*c} "
                    f"(deg {total_deg}) numerical {numerical:.6e} vs "
                    f"exact {exact:.6e}, err {err:.2e}")


def test_unsupported_lebedev_order_raises():
    """Asking for an unbundled order tells the user which orders ARE
    bundled."""
    mol = Molecule([Atom(2, [0.0, 0.0, 0.0])])  # He, closed-shell
    opts = GridOptions()
    opts.angular = "lebedev"
    opts.lebedev_order = 13  # not in the standard ladder
    opts.n_radial = 1
    with pytest.raises(ValueError, match="bundled tiers"):
        build_grid(mol, opts)
