"""Multi-state CASPT2 (MS / XMS): engine invariants and external parity.

Layer 1 (this file, no external programs): machine-precision invariants of
the explicit determinant engine, following the CASPT2 direct-solver oracle
methodology: every new matrix-element path is checked against an independent
explicit computation before any external comparison:

* ``nroots=1`` multi-state == the validated single-state ``caspt2()``
  (identical code path through ``_ic_caspt2_solve``).
* The model space is spin-pure (the determinant CI's M_s sector contains
  higher-S roots a CSF code never sees; the ⟨S²⟩ filter must skip them).
* The explicit reference block ⟨Φ_i|H|Φ_j⟩ equals diag(E_CASCI) (MS) /
  Uᵀ diag(E) U (XMS); multi-root reference machinery vs CASCI eigenvalues.
* The diagonal coupling ⟨Φ_k|H|Ψ_k⁽¹⁾⟩ equals the solver's E2; the
  first-order-wavefunction reconstruction vs the V·C energy contraction.
* The XMS rotation diagonalizes the model-space SA Fock.

Layer 2: recorded OpenMolcas ``&CASPT2`` ``MULTistate`` / ``XMULtistate``
references (regenerated by ``examples/regression/core/runner_openmolcas.py``;
the tests run without OpenMolcas installed).
"""

from __future__ import annotations

import numpy as np
import pytest
from vibeqc import Atom, BasisSet, Molecule
from vibeqc.solvers import (
    build_hamiltonian_mo,
    casci,
    caspt2,
    casscf,
    get_hf_orbital_provider,
)
from vibeqc.solvers._mrpt import _dot, _ic_caspt2_solve, _semicanonical_prep
from vibeqc.solvers._ms_caspt2 import (
    _s2_expectation,
    _spin_pure_roots,
    ms_caspt2,
)

H2 = Molecule([Atom(1, [0.0, 0.0, 0.0]), Atom(1, [0.0, 0.0, 1.4])])
LIH = Molecule([Atom(3, [0.0, 0.0, 0.0]), Atom(1, [0.0, 0.0, 3.0])])
LIH_STRETCH = Molecule([Atom(3, [0.0, 0.0, 0.0]), Atom(1, [0.0, 0.0, 6.0])])


def _ham(mol, basis_name):
    b = BasisSet(mol, basis_name)
    c = get_hf_orbital_provider(mol, b, method="rhf")
    return build_hamiltonian_mo(mol, b, c)


def _ms(mol, basis, n_core, n_act, n_elec, **kw):
    H = _ham(mol, basis)
    n_virt = H.norb - n_core - n_act
    return ms_caspt2(
        H.h1e,
        H.h2e,
        n_core,
        n_virt,
        nuclear_repulsion=H.nuclear_repulsion,
        ms2=0,
        n_act_elec=n_elec,
        **kw,
    )


class TestMSCASPT2Invariants:
    """Machine-precision internal-consistency layer (no external refs)."""

    @pytest.mark.parametrize("mode", ["ms", "xms"])
    def test_single_state_reduces_to_ss_caspt2(self, mode):
        # nroots=1: the multi-state driver must reproduce the validated
        # single-state caspt2() exactly (same _ic_caspt2_solve path; the
        # 1x1 effective Hamiltonian is the SS total energy).
        H = _ham(LIH, "sto-3g")
        n_core, n_act = 1, 2
        n_virt = H.norb - n_core - n_act
        cas = casci(
            H.h1e,
            H.h2e,
            2,
            2,
            n_core,
            nuclear_repulsion=H.nuclear_repulsion,
            ms2=0,
        )
        ss = caspt2(cas, H.h1e, H.h2e, n_core=n_core, n_virt=n_virt)
        ms = _ms(LIH, "sto-3g", n_core, n_act, 2, nroots=1, mode=mode)
        assert abs(ms.e_total - ss.e_total) < 1e-12
        assert ms.nroots == 1 and len(ms.energies) == 1

    def test_model_space_is_spin_pure(self):
        # The M_s=0 determinant sector of LiH CAS(2,2) has the triplet as
        # its second root; the spin filter must skip it and pick the two
        # singlets (what OpenMolcas's CSF-based RASSCF Spin=1 sees).
        H = _ham(LIH, "sto-3g")
        n_act, n_core = 2, 1
        res = casci(
            H.h1e,
            H.h2e,
            2,
            n_act,
            n_core,
            nuclear_repulsion=0.0,
            ms2=0,
            nroots=3,
        )
        s2_raw = [
            _s2_expectation(res.ci_coeffs_all[:, k], res.determinants, n_act, 0)
            for k in range(3)
        ]
        assert abs(s2_raw[1] - 2.0) < 1e-8  # raw root 1 IS the triplet
        ci_cols, e_elec, s2s, _ = _spin_pure_roots(H.h1e, H.h2e, n_core, n_act, 2, 0, 2)
        assert max(abs(s) for s in s2s) < 1e-8  # both selected are singlets
        assert abs(e_elec[0] - res.e_totals[0]) < 1e-12
        assert abs(e_elec[1] - res.e_totals[2]) < 1e-12  # skipped the triplet

    @pytest.mark.parametrize("mode", ["ms", "xms"])
    def test_reference_block_oracle(self, mode):
        # The explicitly contracted ⟨Φ_i|H|Φ_j⟩ block (determinant-space
        # H application on each model state) must equal the production
        # assembly's Uᵀ diag(E_CASCI) U: for MS (U=1) the model states
        # diagonalize H in the model space; for XMS, undoing the rotation
        # must recover the diagonal CASCI block.  This pins the multi-root
        # reference machinery against the CASCI eigenvalues through a
        # completely independent contraction path.
        ms = _ms(LIH_STRETCH, "sto-3g", 1, 2, 2, nroots=2, mode=mode)
        u = ms.xms_rotation
        ref = np.asarray(ms.ref_hamiltonian)
        assert np.allclose(ref, ref.T, atol=1e-10)
        assert np.allclose(np.diag(ref), ms.ref_energies, atol=1e-12)
        back = u @ ref @ u.T  # undo the XMS rotation (identity for ms)
        off = back - np.diag(np.diag(back))
        assert np.abs(off).max() < 1e-10
        if mode == "xms":
            # strong-mixing case: the rotated reference block itself is
            # genuinely non-diagonal before undoing the rotation.
            assert abs(ref[0, 1]) > 1e-3

    def test_diagonal_coupling_equals_e2(self):
        # ⟨Φ|H|Ψ⁽¹⁾⟩ must equal E2 = V·C at σ=0: the first-order
        # wavefunction reconstruction (M @ T @ Q @ c) contracted against
        # H|0⟩ in the determinant basis is an independent path to the
        # energy computed inside the solver in the orthonormal basis.
        H = _ham(LIH, "sto-3g")
        n_core, n_act = 1, 2
        P = _semicanonical_prep(H.h1e, H.h2e, n_core, n_act, 2, 0)
        e_corr, nb, psi1, w, _clagdx = _ic_caspt2_solve(
            P, n_core, n_act, return_wavefunction=True
        )
        assert nb > 0 and len(psi1) > 0
        assert abs(_dot(w, psi1) - e_corr) < 1e-12

    def test_xms_rotation_diagonalizes_model_fock(self):
        xms = _ms(LIH_STRETCH, "sto-3g", 1, 2, 2, nroots=2, mode="xms")
        u, f = xms.xms_rotation, xms.model_fock
        assert np.allclose(u.T @ u, np.eye(2), atol=1e-12)
        rotated = u.T @ f @ u
        off = rotated - np.diag(np.diag(rotated))
        assert np.abs(off).max() < 1e-10
        # stretched LiH is the strong-mixing regime: the rotation must be
        # far from the identity (the case XMS exists for).
        assert abs(u[0, 1]) > 0.3

    @pytest.mark.parametrize("mode", ["ms", "xms"])
    def test_heff_assembly_and_diagonalization(self, mode):
        ms = _ms(LIH_STRETCH, "sto-3g", 1, 2, 2, nroots=2, mode=mode)
        heff = np.asarray(ms.heff)
        asym = np.asarray(ms.heff_asym)
        assert np.allclose(heff, 0.5 * (asym + asym.T), atol=1e-14)
        w, v = np.linalg.eigh(heff)
        assert np.allclose(w, ms.energies, atol=1e-12)
        assert np.allclose(np.abs(ms.mixing.T @ ms.mixing), np.eye(2), atol=1e-12)
        # diagonal of the asymmetric Heff = reference + E2 (the SS totals)
        assert np.allclose(
            np.diag(asym),
            np.asarray(ms.ref_energies) + np.asarray(ms.e2_corr),
            atol=1e-12,
        )
        # multi-state mixing is variational in the model space: the lowest
        # MS root lies at or below the lowest SS diagonal.
        assert ms.energies[0] <= ms.ss_energies[0] + 1e-12

    def test_h2_symmetry_blocked_coupling(self):
        # H2 CAS(2,2): the two lowest singlets are ¹Σg and ¹Σu, different
        # spatial symmetry, so the MS coupling vanishes and MS == SS.
        ms = _ms(H2, "6-31g", 0, 2, 2, nroots=2, mode="ms")
        off = ms.heff_asym - np.diag(np.diag(ms.heff_asym))
        assert np.abs(off).max() < 1e-10
        assert np.allclose(ms.energies, sorted(ms.ss_energies), atol=1e-10)

    def test_imaginary_shift_smoke(self):
        # σ≠0 must run through the multi-state path (shift-corrected
        # diagonal, shifted amplitudes in the couplings) and stay close to
        # the unshifted result for this intruder-free case.
        ms0 = _ms(LIH, "sto-3g", 1, 2, 2, nroots=2, mode="ms")
        msi = _ms(LIH, "sto-3g", 1, 2, 2, nroots=2, mode="ms", imaginary=0.1)
        assert np.all(np.isfinite(msi.energies))
        assert abs(msi.energies[0] - ms0.energies[0]) < 5e-3
        # the imaginary shift raises (weakens) the correlation energy
        assert msi.e2_corr[0] > ms0.e2_corr[0]

    def test_invalid_inputs_raise(self):
        H = _ham(LIH, "sto-3g")
        n_virt = H.norb - 3
        with pytest.raises(ValueError, match="mode"):
            ms_caspt2(
                H.h1e,
                H.h2e,
                1,
                n_virt,
                nroots=2,
                mode="bogus",
                ms2=0,
                n_act_elec=2,
            )
        with pytest.raises(ValueError, match="nroots"):
            ms_caspt2(
                H.h1e,
                H.h2e,
                1,
                n_virt,
                nroots=0,
                ms2=0,
                n_act_elec=2,
            )
        with pytest.raises(ValueError, match="spin-pure"):
            # CAS(2,2) has only 3 singlets; asking for 4 must fail clearly.
            ms_caspt2(
                H.h1e,
                H.h2e,
                1,
                n_virt,
                nroots=4,
                ms2=0,
                n_act_elec=2,
            )


# ── Layer 2: OpenMolcas parity ───────────────────────────────────────────────
# Recorded from live OpenMolcas runs (2026-06-10, local build) via
# examples/regression/core/runner_openmolcas.py::run_caspt2(nroots=2,
# multistate=...): &SCF → &RASSCF CIonly, CIRoot = 2 2 1 (SA2 equal weights,
# HF orbitals, apples-to-apples with vibe-qc's spin-filtered CASCI model
# space on the same RHF basis) → &CASPT2 IPEAshift=0, Frozen=0, with
# MULTistate=all / XMULtistate=all.  Regenerate with the _MS_CASES table in
# that runner.
#
# key: (system, basis, n_core, n_act, n_elec, mode, imaginary)
#   -> (rasscf roots, MS/XMS-CASPT2 roots)
_OM_MS = {
    ("LiH_R3", "sto-3g", 1, 2, 2, "ms", 0.0): (
        [-7.86250449, -7.70734389],
        [-7.87549608, -7.74216873],
    ),
    ("LiH_R3", "sto-3g", 1, 2, 2, "xms", 0.0): (
        [-7.86250449, -7.70734389],
        [-7.87715367, -7.74081346],
    ),
    ("LiH_R6", "sto-3g", 1, 2, 2, "ms", 0.0): (
        [-7.71920432, -7.62393106],
        [-7.78082029, -7.67877841],
    ),
    ("LiH_R6", "sto-3g", 1, 2, 2, "xms", 0.0): (
        [-7.71920432, -7.62393106],
        [-7.80527437, -7.69258259],
    ),
    ("H2", "6-31g", 0, 2, 2, "ms", 0.0): (
        [-1.13239765, -0.56650913],
        [-1.14670322, -0.58554515],
    ),
    ("LiH_R6", "sto-3g", 1, 2, 2, "ms", 0.1): (
        [-7.71920432, -7.62393106],
        [-7.78061675, -7.67864908],
    ),
    ("LiH_R6", "sto-3g", 1, 2, 2, "xms", 0.1): (
        [-7.71920432, -7.62393106],
        [-7.80487300, -7.68998599],
    ),
}
# OpenMolcas per-root SS-CASPT2 lines from the same MS runs (printed for
# MULTistate only; XMS prints none: rotated references).
_OM_MS_SS = {
    ("LiH_R3", "sto-3g", 1, 2, 2, "ms", 0.0): [-7.87523227, -7.74243254],
    ("LiH_R6", "sto-3g", 1, 2, 2, "ms", 0.0): [-7.78023127, -7.67936743],
    ("LiH_R6", "sto-3g", 1, 2, 2, "ms", 0.1): [-7.78013544, -7.67913039],
}
_MOLS = {"H2": H2, "LiH_R3": LIH, "LiH_R6": LIH_STRETCH}

# σ = 0: same method, same model space, tight gate (matches the existing
# single-state OM gate).  σ ≠ 0: vibe-qc applies the imaginary shift to the
# full nondiagonal H₀ (the basis-independent Forsberg-Malmqvist complex
# shift; same convention on the explicit and direct paths, M5), while
# OpenMolcas adds σ²/Δ to the diagonal of its case-block-diagonal H₀
# representation (sgmdia), a representation-dependent variant.  The two
# agree to <1e-8 without intruders (H2O/cc-pVDZ, M5) but diverge near the
# intruders the shift exists for (stretched LiH root 2): observed 1.3e-5
# (ms) / 1.7e-4 (xms) here.  That is convention-level arbitrariness of the
# regularizer, not an implementation error; gate accordingly.
_OM_TOL = 5e-6
_OM_TOL_SHIFTED = 5e-4


class TestMSCASPT2OpenMolcasParity:
    @pytest.mark.parametrize("key", list(_OM_MS))
    def test_ms_xms_vs_openmolcas(self, key):
        system, basis, n_core, n_act, n_elec, mode, imag = key
        ras_ref, ms_ref = _OM_MS[key]
        nroots = len(ms_ref)
        res = _ms(
            _MOLS[system],
            basis,
            n_core,
            n_act,
            n_elec,
            nroots=nroots,
            mode=mode,
            imaginary=imag,
        )
        tol = _OM_TOL if imag == 0.0 else _OM_TOL_SHIFTED
        # model-space reference roots (spin-filtered CASCI on HF orbitals
        # vs OpenMolcas CSF-based RASSCF CIonly roots); for XMS undo the
        # model-space rotation first (ref_energies are the rotated states'
        # diagonal ⟨ĩ|H|ĩ⟩, not the CASCI eigenvalues).
        u = res.xms_rotation
        casci_roots = np.diag(u @ np.asarray(res.ref_hamiltonian) @ u.T)
        assert np.abs(casci_roots - ras_ref).max() < _OM_TOL
        # the multi-state eigenvalues
        assert np.abs(np.asarray(res.energies) - ms_ref).max() < tol
        if key in _OM_MS_SS:
            assert np.abs(np.asarray(res.ss_energies) - _OM_MS_SS[key]).max() < tol

    def test_ms_differs_from_ss_where_coupled(self):
        # At the stretched-LiH avoided crossing the MS rotation is real
        # physics: the recorded OM MS roots differ from the OM SS roots by
        # ~0.6 mHa, and XMS differs from MS by ~25 mHa (strong mixing).
        key_ms = ("LiH_R6", "sto-3g", 1, 2, 2, "ms", 0.0)
        key_xms = ("LiH_R6", "sto-3g", 1, 2, 2, "xms", 0.0)
        _, ms_roots = _OM_MS[key_ms]
        _, xms_roots = _OM_MS[key_xms]
        ss_roots = _OM_MS_SS[key_ms]
        assert abs(ms_roots[0] - ss_roots[0]) > 1e-4
        assert abs(xms_roots[0] - ms_roots[0]) > 1e-3


# OpenMolcas full &RASSCF (ci_only=False), CIRoot = 2 2 1, LiH/STO-3G R=3.0
# CAS(2,2): the SA2 reference the spin-pure SA-CASSCF must reproduce
# (recorded 2026-06-10 from the same runner runs as the composition
# constants in tests/test_runner_ms_caspt2.py).
_OM_SA2_CASSCF_LIH = [-7.85516481, -7.72558848]


class TestSpinPureSACASSCF:
    """⟨S²⟩-filtered state-averaged CASSCF root selection (M10)."""

    def test_spin_pure_sa_casscf_matches_openmolcas(self):
        # With the filter, vibe-qc averages the two lowest singlets and
        # must land in OpenMolcas's singlet-averaged RASSCF solution
        # (LiH is a safe unique-minimum parity system).
        H = _ham(LIH, "sto-3g")
        sc = casscf(
            H.h1e,
            H.h2e,
            n_active_elec=2,
            n_active_orb=2,
            n_core=1,
            nuclear_repulsion=H.nuclear_repulsion,
            ms2=0,
            nroots=2,
            spin_pure=True,
        )
        assert sc.converged
        s2 = [
            _s2_expectation(sc.cas.ci_coeffs_all[:, k], sc.cas.determinants, 2, 0)
            for k in range(2)
        ]
        assert max(abs(s) for s in s2) < 1e-8
        assert np.abs(np.asarray(sc.e_totals) - _OM_SA2_CASSCF_LIH).max() < 5e-6

    def test_default_sa_casscf_is_spin_pure(self):
        # Since 2026-06-11, spin_pure=None resolves to True for SA runs
        # (nroots > 1): the default average is the two lowest singlets,
        # landing in OpenMolcas's singlet-averaged RASSCF solution.
        H = _ham(LIH, "sto-3g")
        sc = casscf(
            H.h1e,
            H.h2e,
            n_active_elec=2,
            n_active_orb=2,
            n_core=1,
            nuclear_repulsion=H.nuclear_repulsion,
            ms2=0,
            nroots=2,
        )
        assert sc.converged
        s2 = [
            _s2_expectation(sc.cas.ci_coeffs_all[:, k], sc.cas.determinants, 2, 0)
            for k in range(2)
        ]
        assert max(abs(s) for s in s2) < 1e-8
        assert np.abs(np.asarray(sc.e_totals) - _OM_SA2_CASSCF_LIH).max() < 5e-6

    def test_spin_pure_false_keeps_ms_sector_roots(self):
        # The deliberate mixed-spin ensemble opt-out (the pre-2026-06-11
        # default): the raw M_s=0 average includes the triplet as root 1.
        H = _ham(LIH, "sto-3g")
        sc = casscf(
            H.h1e,
            H.h2e,
            n_active_elec=2,
            n_active_orb=2,
            n_core=1,
            nuclear_repulsion=H.nuclear_repulsion,
            ms2=0,
            nroots=2,
            spin_pure=False,
        )
        assert sc.converged
        s2_root1 = _s2_expectation(
            sc.cas.ci_coeffs_all[:, 1], sc.cas.determinants, 2, 0
        )
        assert abs(s2_root1 - 2.0) < 1e-6
