"""Kerker preconditioner: formula provenance and parameter estimation.

The Kerker filter damps small-|G| charge-density modes that cause charge
sloshing in metallic and small-gap periodic SCF. These tests pin it
against the defining publication rather than against internally-chosen
numbers.

Reference: Kerker, *Phys. Rev. B* 23, 3082 (1981),
doi:10.1103/PhysRevB.23.3082.
"""

from __future__ import annotations

import math

import numpy as np
import pytest

from vibeqc.kerker import kerker_k0_thomas_fermi, kerker_kernel
from vibeqc.periodic_runner import citation_scf_accelerator


def test_kerker_kernel_matches_the_published_limits():
    """The filter must reproduce Kerker's two limiting cases.

    # Eq. (9) of Kerker (1981), p. 3083, gives the mixed Coulomb
    # potential with the denominator (|G|^2 + lambda^2); the density
    # residual therefore carries the factor
    #     f(G) = |G|^2 / (|G|^2 + lambda^2)
    # whose limits the paper states explicitly:
    #   Eq. (10), lambda^2 << |G|^2: the new potential is essentially
    #             generated by the OUTPUT density        -> f -> 1
    #   Eq. (11), lambda^2 >> |G|^2: "only a small amount of output
    #             information is mixed"                  -> f -> 0
    """
    k0 = 0.86

    short_wavelength = np.array([100.0 * k0**2])   # |G|^2 >> lambda^2
    assert kerker_kernel(short_wavelength, k0=k0)[0] == pytest.approx(1.0, abs=0.02)

    long_wavelength = np.array([0.01 * k0**2])     # |G|^2 << lambda^2
    assert kerker_kernel(long_wavelength, k0=k0)[0] == pytest.approx(0.0, abs=0.02)

    # At |G| = lambda the filter sits at exactly one half.
    assert kerker_kernel(np.array([k0**2]), k0=k0)[0] == pytest.approx(0.5)

    # G = 0 is removed outright: the cell's total charge must not be
    # mixed, or the SCF would not conserve electron count.
    assert kerker_kernel(np.array([0.0]), k0=k0)[0] == 0.0

    # Monotone in |G|: damping must strengthen toward long wavelength.
    g2 = np.array([0.01, 0.1, 1.0, 10.0, 100.0]) * k0**2
    vals = kerker_kernel(g2, k0=k0)
    assert np.all(np.diff(vals) > 0.0)


def test_kerker_k0_thomas_fermi_reproduces_the_papers_own_example():
    """Eq. (8) must reproduce the screening length the paper quotes.

    The filter needs a screening wave-vector k0, and the module offered
    only a hardcoded guess (1.0 here, 1.5 on the GDF driver) with no
    physical basis.

    # Eq. (8) of Kerker (1981), p. 3083:
    #   lambda ~ (4 k_F / pi)^{1/2},   k_F = (3 pi^2 n)^{1/3}

    Published target: the Ca(001) seven-layer film example is quoted at
    r_s = 3.3 a.u. with "a screening length of 2 pi / lambda = 7.3 a.u."
    (p. 3084). Feeding n = 3 / (4 pi r_s^3) through Eq. (8) must land
    there. That round trip is what validates the formula -- an
    internally-chosen number would validate nothing.
    """
    r_s = 3.3
    volume_per_electron = 4.0 * math.pi * r_s**3 / 3.0
    k0 = kerker_k0_thomas_fermi(1.0, volume_per_electron)
    screening_length = 2.0 * math.pi / k0
    assert screening_length == pytest.approx(7.3, abs=0.01), (
        f"Eq. (8) at r_s = 3.3 must give the paper's 7.3 a.u. screening "
        f"length; got {screening_length:.3f}"
    )


def test_kerker_k0_thomas_fermi_scales_and_validates():
    """Denser gas screens harder; degenerate inputs are refused."""
    v = 4.0 * math.pi * 3.3**3 / 3.0
    k0 = kerker_k0_thomas_fermi(1.0, v)

    # n^(1/6) scaling: k0 ~ k_F^(1/2) ~ n^(1/6).
    k0_dense = kerker_k0_thomas_fermi(1.0, v / 64.0)
    assert k0_dense == pytest.approx(k0 * 64.0 ** (1.0 / 6.0), rel=1e-12)

    # Only the ratio matters, not how it is expressed.
    assert kerker_k0_thomas_fermi(8.0, 8.0 * v) == pytest.approx(k0, rel=1e-12)

    for bad in ((0.0, 10.0), (-1.0, 10.0), (1.0, 0.0), (1.0, -10.0)):
        with pytest.raises(ValueError):
            kerker_k0_thomas_fermi(*bad)


def test_citation_accelerator_names_what_the_run_actually_used():
    """The citation plan must name the accelerator, not the default.

    Regression for PERIODIC-CITES-DIIS-IT-DID-NOT-USE. `assemble` defaults
    `scf_accelerator` to "diis" and the periodic runner never passed it,
    so an Anderson+Kerker run cited Pulay's DIIS papers -- and cited
    NOTHING for the two methods it actually ran. Measured on H2/STO-3G
    (2,1,1): 0 Anderson/Kerker entries and 4 Pulay/DIIS entries in
    `.references`, on the surface users copy into a paper.

    The mapping mirrors `_validate_density_mixer_dispatch`: None / "" /
    "none" / "diis" all take the default Fock-DIIS route, and Kerker is
    only reachable with Anderson or Broyden.
    """
    assert citation_scf_accelerator(None, False) == "diis"
    assert citation_scf_accelerator("", False) == "diis"
    assert citation_scf_accelerator("none", False) == "diis"
    assert citation_scf_accelerator("diis", False) == "diis"

    assert citation_scf_accelerator("anderson", False) == "anderson"
    assert citation_scf_accelerator("broyden", False) == "broyden"
    assert citation_scf_accelerator("anderson", True) == "anderson_kerker"
    assert citation_scf_accelerator("broyden", True) == "broyden_kerker"

    # Case and whitespace are normalised the same way the validator does.
    assert citation_scf_accelerator("  Anderson  ", True) == "anderson_kerker"


def test_every_accelerator_key_resolves_to_a_live_route():
    """A key with no route is a silently dead citation.

    `assemble` looks the accelerator up in `routes.methods` and a miss is
    SILENT, so a typo or a missing composed key would reproduce the very
    bug this fixes -- no citation, no error. Pin that every key the
    resolver can emit resolves, and that the composed keys really carry
    the Kerker paper on top of their mixer.
    """
    from vibeqc.output.citations.registry import load_default_database

    routes = load_default_database()._routes["methods"]
    for mixer in (None, "diis", "anderson", "broyden"):
        for kerker in (False, True):
            if kerker and mixer in (None, "diis"):
                continue  # rejected upstream by the validator
            key = citation_scf_accelerator(mixer, kerker)
            assert key in routes, f"accelerator key {key!r} has no route"
            assert routes[key], f"accelerator key {key!r} routes to nothing"

    assert "kerker_1981" in routes["anderson_kerker"]
    assert "anderson_mixing_1965" in routes["anderson_kerker"]
    assert "kerker_1981" in routes["broyden_kerker"]
    assert "broyden_1965" in routes["broyden_kerker"]
    # The plain mixer keys must NOT drag Kerker in.
    assert "kerker_1981" not in routes["anderson"]
    assert "kerker_1981" not in routes["broyden"]
