"""X23 — crystalline benzene Pbca (orthorhombic 4-molecule cell).

Benzene crystallises in space group Pbca with a = 7.398, b = 9.435,
c = 6.778 Å at 138 K (Bacon, Curry, Wilson, *Proc. R. Soc. A* **1964**,
279, 98 — neutron diffraction). Z = 4 (4 C6H6 = 48 atoms / cell).

X23 / X23-revised lattice-energy reference for benzene is **51.7
kJ/mol per formula unit** (Dolgonos-Hoja-Boese 2019, scaled for ZPE
and thermal corrections). One of the canonical "pure-dispersion"
molecular crystals — the lattice cohesion is essentially all
quadrupole + London. Tests cross-code agreement on a system where
the molecular SCF energies of the isolated rings are easy and the
periodic Coulomb sum is the interesting thing.
"""
from __future__ import annotations

from ...core.spec import AtomFrac, PeriodicSpec

# Benzene in Pbca, atoms in the asymmetric unit (1/4 of a molecule)
# expanded by Pbca symmetry to 4 molecules / 48 atoms / cell. Cartesian
# fractions calculated from the canonical Bacon-Curry-Wilson 138 K
# parameters (with 12 C + 12 H per quarter, then × 4 by symmetry).
#
# Asymmetric unit (1/2 molecule, atoms in C6H6):
_ASU_C = (
    (-0.0571,  0.1397,  0.0050),
    (-0.1378,  0.0473,  0.1264),
    (-0.0810, -0.0916,  0.1208),
)
_ASU_H = (
    (-0.0989,  0.2452,  0.0099),
    (-0.2441,  0.0824,  0.2245),
    (-0.1448, -0.1632,  0.2147),
)

# Pbca generators (8 symmetry positions): (x,y,z), (-x+1/2,-y,z+1/2),
# (-x,y+1/2,-z+1/2), (x+1/2,-y+1/2,-z), (-x,-y,-z), (x+1/2,y,-z+1/2),
# (x,-y+1/2,z+1/2), (-x+1/2,y+1/2,z). Apply to the 6-atom asymmetric
# unit (3 unique C + 3 unique H, with the second half of the ring
# generated by inversion).
_PBCA_OPS = (
    (lambda x, y, z: ( x,         y,         z       )),
    (lambda x, y, z: (-x + 0.5,  -y,         z + 0.5)),
    (lambda x, y, z: (-x,         y + 0.5,  -z + 0.5)),
    (lambda x, y, z: ( x + 0.5,  -y + 0.5,  -z      )),
    (lambda x, y, z: (-x,        -y,        -z      )),
    (lambda x, y, z: ( x + 0.5,   y,        -z + 0.5)),
    (lambda x, y, z: ( x,        -y + 0.5,   z + 0.5)),
    (lambda x, y, z: (-x + 0.5,   y + 0.5,   z      )),
)


def _wrap(t):
    return tuple((c % 1.0) for c in t)


_C_ALL = tuple(
    AtomFrac(symbol="C", z=6, frac=_wrap(op(*xyz)))
    for xyz in _ASU_C
    for op in _PBCA_OPS
)
_H_ALL = tuple(
    AtomFrac(symbol="H", z=1, frac=_wrap(op(*xyz)))
    for xyz in _ASU_H
    for op in _PBCA_OPS
)

SPEC = PeriodicSpec(
    id="x23_benzene_crystal",
    family="molecular_crystal",
    lattice_ang=(
        (7.398, 0.000, 0.000),
        (0.000, 9.435, 0.000),
        (0.000, 0.000, 6.778),
    ),
    space_group="Pbca",
    atoms=_C_ALL + _H_ALL,
    default_kmesh=(1, 1, 1),
    default_spacing_bohr=0.4,
    default_cutoff_bohr=12.0,
    default_nuclear_cutoff_bohr=25.0,
    default_omega=0.5,
    default_conv_tol_energy=1e-7,
    default_max_iter=60,
    default_initial_guess="SAD",
    default_damping=0.7,
    notes=(
        "Crystalline benzene at 138 K, Pbca with Z=4 (48 atoms / cell). "
        "Canonical 'pure dispersion' molecular crystal in X23. Lattice "
        "energy magnitude 51.7 kJ/mol per formula unit "
        "(Dolgonos-Hoja-Boese 2019). Bare DFT (LDA, PBE, B3LYP without "
        "dispersion correction) underbinds by 30-50 % — strict "
        "numerical match against published energies needs a "
        "dispersion correction (D3/D4) which vibe-qc doesn't ship in "
        "v0.7.x. Cross-code parity vs PySCF.pbc at matching settings "
        "is the meaningful test for now."
    ),
    citation=(
        "Bacon, Curry, Wilson, *Proc. R. Soc. A* **1964**, 279, 98 "
        "(benzene crystal structure at 138 K). "
        "Reilly, Tkatchenko, *J. Chem. Phys.* **2013**, 139, 024705 "
        "(X23 origin, DOI 10.1063/1.4812819). "
        "Dolgonos, Hoja, Boese, *Phys. Chem. Chem. Phys.* **2019**, "
        "21, 24333 (revised X23, DOI 10.1039/C9CP04488D)."
    ),
)
