#!/usr/bin/env python3
"""MSINDO validation: vibe-qc's MSINDO engine vs reference MSINDO.

MSINDO (Modified Symmetrically Orthogonalised INDO; Ahlswede & Jug, *J. Comput.
Chem.* **20**, 563 & 572 (1999); © Mulliken Center for Theoretical Chemistry,
University of Bonn) is a semiempirical INDO-family SCF-MO method over **Slater**
orbitals.  vibe-qc carries an independent re-implementation (it imports no MSINDO
code) — a Python reference engine
(``vibeqc.semiempirical.methods.msindo``) and a C++ port
(``vibeqc._vibeqc_core.semiempirical.indo``) — both validated out-of-process
against a reference MSINDO build (CLAUDE.md § 10).

This script runs the closed-shell reference set and reports the deviation of
vibe-qc's MSINDO total energy from reference MSINDO.  The reference energies are
stored in ``examples/regression/msindo/molecular_reference.json`` (generated by a
local MSINDO 2025 build).  Everything should agree to well under 1 µHa.

Coverage:
  * s shell      H₂  (1s only)
  * s/p shell    HF, N₂, CO, CH₄, H₂O  (2nd-row main group, C/N/O/F)
  * s/p/d shell  H₂S, SiH₄, PH₃        (3rd row Si/P/S: 3d polarization
                                        function + a Ne 1s2s2p frozen core)

Run:

    .venv/bin/python examples/semiempirical/10_msindo_validate.py
"""

from __future__ import annotations

import json
from pathlib import Path

from vibeqc.semiempirical.methods import msindo

_SYMBOL_Z = {"H": 1, "He": 2, "C": 6, "N": 7, "O": 8, "F": 9,
             "Al": 13, "Si": 14, "P": 15, "S": 16, "Cl": 17}
_REF = json.loads(
    (Path(__file__).resolve().parents[2]
     / "examples/regression/msindo/molecular_reference.json").read_text()
)


def main() -> None:
    print("=" * 74)
    print(" MSINDO validation — vibe-qc engine vs reference MSINDO (RHF+UHF, a.u.)")
    print("=" * 74)
    print(f"\n{'molecule':<8}{'vibe-qc total':>18}{'reference':>18}"
          f"{'Δ (Ha)':>12}  conv")
    print("-" * 74)
    worst = 0.0
    for mol in _REF["molecules"]:
        Z = [_SYMBOL_Z[s] for s, *_ in mol["geometry"]]
        xyz = [[x, y, z] for _, x, y, z in mol["geometry"]]
        r = msindo.run_msindo(
            Z, xyz,
            charge=mol.get("charge", 0),
            multiplicity=mol.get("multiplicity", 1),
        )
        ref = mol["reference"]["total_energy"]
        d = r.total_energy - ref
        worst = max(worst, abs(d))
        flag = "OK" if abs(d) < 1e-6 else "**OFF**"
        print(f"{mol['name']:<8}{r.total_energy:>18.10f}{ref:>18.10f}"
              f"{d:>+12.2e}  {r.converged}/{r.n_iter:<3} {flag}")
    print("-" * 74)
    print(f"\nLargest deviation: {worst:.2e} Ha "
          f"({'PASS' if worst < 1e-6 else 'FAIL'} at the 1 µHa parity gate)\n")

    # Mulliken-style atomic charges from the (orthogonal) MSINDO density:
    #   q_A = CZ_A − Σ_{μ∈A} P_μμ.  Demonstrated on H₂S.
    print("Atomic charges (H₂S, orthogonal MSINDO density):")
    Z = [16, 1, 1]
    xyz = [[0, 0, 0], [0.9627, 0, 0.9264], [-0.9627, 0, 0.9264]]
    res = msindo.run_msindo(Z, xyz)
    blocks, _ = msindo._atom_blocks(Z)
    for (sym, z), (lo, hi) in zip([("S", 16), ("H", 1), ("H", 1)], blocks):
        pop = float(res.density.diagonal()[lo:hi].sum())
        q = msindo.eff_core_charge(z) - pop
        print(f"   {sym:<2} valence pop = {pop:6.3f}   charge = {q:+.3f}")


if __name__ == "__main__":
    main()
