"""Emit a ``PeriodicSpec`` / ``MoleculeSpec`` Python module from a fetched ``TestSystem``.

The output module is drop-in compatible with
``examples/regression/systems/<periodic|molecules>/<id>.py``: it
exports a top-level ``SPEC`` of the right type so
``examples.regression.run_suite._load_periodic_spec`` /
``_load_molecule_spec`` finds it.

We use ``examples/regression/systems/periodic/mgo_rocksalt.py`` as the
template for periodic SPECs and the ``h2o.py`` molecular spec as the
template for molecules.
"""
from __future__ import annotations

from pathlib import Path
from typing import Sequence

from examples.regression.core.spec import (
    AtomCart,
    AtomFrac,
    MoleculeSpec,
    PeriodicSpec,
    Provenance,
    TestSystem,
)


# ---- Pretty-printing tuples / Provenance ------------------------------------

def _fmt_float(x: float, ndigits: int = 8) -> str:
    """Format a float for emission.

    Always uses :func:`repr` -- it emits the shortest decimal that
    round-trips to the same IEEE-754 double, so re-importing the
    emitted SPEC reconstructs ``x`` exactly. ``ndigits`` is kept on
    the signature for back-compat with callers that used to round
    visually; we ignore it.
    """
    return repr(float(x))


def _fmt_lattice(lat: Sequence[Sequence[float]]) -> str:
    rows = []
    for row in lat:
        rows.append("        ({}, {}, {}),".format(
            _fmt_float(row[0]),
            _fmt_float(row[1]),
            _fmt_float(row[2]),
        ))
    return "\n".join(rows)


def _fmt_provenance(p: Provenance) -> str:
    return (
        "Provenance(\n"
        f"        source_db={p.source_db!r},\n"
        f"        source_id={p.source_id!r},\n"
        f"        source_url={p.source_url!r},\n"
        f"        original_reference={p.original_reference!r},\n"
        f"        license={p.license!r},\n"
        f"        fetched_at={p.fetched_at!r},\n"
        f"        fetcher_version={p.fetcher_version!r},\n"
        f"        notes={p.notes!r},\n"
        "    )"
    )


def _fmt_atomfrac_block(atoms: Sequence[AtomFrac]) -> str:
    lines = []
    for at in atoms:
        f0, f1, f2 = at.frac
        lines.append(
            f"        AtomFrac(symbol={at.symbol!r}, z={at.z}, "
            f"frac=({_fmt_float(f0)}, {_fmt_float(f1)}, {_fmt_float(f2)})),"
        )
    return "\n".join(lines)


def _fmt_atomcart_block(atoms: Sequence[AtomCart]) -> str:
    lines = []
    for at in atoms:
        x, y, z = at.xyz_ang
        lines.append(
            f"        AtomCart(symbol={at.symbol!r}, z={at.z}, "
            f"xyz_ang=({_fmt_float(x)}, {_fmt_float(y)}, {_fmt_float(z)})),"
        )
    return "\n".join(lines)


# ---- Module-text builders ---------------------------------------------------

def _format_periodic(spec: PeriodicSpec) -> str:
    assert spec.provenance is not None, (
        "emit_spec_module: provenance is required for emitted SPECs"
    )
    prov = _fmt_provenance(spec.provenance)
    lat = _fmt_lattice(spec.lattice_ang)
    atoms = _fmt_atomfrac_block(spec.atoms)
    mag = (
        "None"
        if spec.magnetic_moments is None
        else f"({', '.join(_fmt_float(m, 4) for m in spec.magnetic_moments)},)"
    )
    rec = "None" if spec.recommended_basis is None else repr(spec.recommended_basis)
    return f'''"""{spec.id} -- fetched {spec.family} ({spec.provenance.source_db}/{spec.provenance.source_id}).

Auto-generated by ``vibeqc.fetch`` (fetcher version {spec.provenance.fetcher_version}).
Do not edit by hand -- re-run the fetcher to regenerate.
"""
from __future__ import annotations

from examples.regression.core.spec import (
    AtomFrac,
    PeriodicSpec,
    Provenance,
)


SPEC = PeriodicSpec(
    id={spec.id!r},
    family={spec.family!r},
    lattice_ang=(
{lat}
    ),
    space_group={spec.space_group!r},
    atoms=(
{atoms}
    ),
    default_kmesh={tuple(spec.default_kmesh)!r},
    default_spacing_bohr={_fmt_float(spec.default_spacing_bohr, 4)},
    default_cutoff_bohr={_fmt_float(spec.default_cutoff_bohr, 4)},
    default_nuclear_cutoff_bohr={_fmt_float(spec.default_nuclear_cutoff_bohr, 4)},
    default_omega={_fmt_float(spec.default_omega, 4)},
    default_conv_tol_energy={spec.default_conv_tol_energy!r},
    default_max_iter={spec.default_max_iter},
    default_initial_guess={spec.default_initial_guess!r},
    default_damping={_fmt_float(spec.default_damping, 4)},
    default_use_periodic_becke={spec.default_use_periodic_becke!r},
    notes={spec.notes!r},
    citation={spec.citation!r},
    recommended_basis={rec},
    magnetic_moments={mag},
    is_open_shell={spec.is_open_shell!r},
    provenance={prov},
)
'''


def _format_molecule(spec: MoleculeSpec) -> str:
    assert spec.provenance is not None, (
        "emit_spec_module: provenance is required for emitted SPECs"
    )
    prov = _fmt_provenance(spec.provenance)
    atoms = _fmt_atomcart_block(spec.atoms)
    rec = "None" if spec.recommended_basis is None else repr(spec.recommended_basis)
    return f'''"""{spec.id} -- fetched {spec.family} ({spec.provenance.source_db}/{spec.provenance.source_id}).

Auto-generated by ``vibeqc.fetch`` (fetcher version {spec.provenance.fetcher_version}).
Do not edit by hand -- re-run the fetcher to regenerate.
"""
from __future__ import annotations

from examples.regression.core.spec import (
    AtomCart,
    MoleculeSpec,
    Provenance,
)


SPEC = MoleculeSpec(
    id={spec.id!r},
    family={spec.family!r},
    atoms=(
{atoms}
    ),
    charge={spec.charge},
    multiplicity={spec.multiplicity},
    default_conv_tol_energy={spec.default_conv_tol_energy!r},
    default_max_iter={spec.default_max_iter},
    notes={spec.notes!r},
    citation={spec.citation!r},
    recommended_basis={rec},
    provenance={prov},
)
'''


# ---- Public API -------------------------------------------------------------

def emit_spec_module(
    spec: TestSystem,
    out_dir: Path,
    *,
    overwrite: bool = True,
) -> Path:
    """Write a Python module that exports ``SPEC`` for ``spec``.

    ``out_dir`` is the directory under which the module lives -- usually
    ``examples/regression/systems/periodic/`` or
    ``examples/regression/systems/molecules/``. The filename is
    ``<spec.id>.py``.

    Returns the absolute path to the written file.
    """
    out_dir = Path(out_dir).expanduser()
    out_dir.mkdir(parents=True, exist_ok=True)
    if isinstance(spec, PeriodicSpec):
        text = _format_periodic(spec)
    elif isinstance(spec, MoleculeSpec):
        text = _format_molecule(spec)
    else:
        raise TypeError(
            f"emit_spec_module: unsupported TestSystem type {type(spec).__name__}"
        )
    path = out_dir / f"{spec.id}.py"
    if path.exists() and not overwrite:
        raise FileExistsError(f"refusing to overwrite {path}")
    path.write_text(text, encoding="utf-8")
    return path
