"""Emit a standalone executable vibe-qc input script from a fetched ``TestSystem``.

The output script mirrors the style of
``examples/input-mgo-pob-tzvp.py``: it builds the system in-line, runs
the appropriate SCF driver, prints HOMO/LUMO + gap, and writes the
runtime manifest.

Two flavours:

  * Periodic -> ``input-<id>-<basis>.py`` with ``vq.PeriodicSystem`` +
    ``vq.run_rhf_periodic_scf`` / ``vq.run_rks_periodic_scf``.
  * Molecular -> ``input-<id>-<basis>.py`` with ``vq.run_job(mol, basis,
    method, output=...)`` (the high-level molecular runner).

The generated script is human-readable, line-commented, and pulls the
same defaults the fetcher chose for the SPEC. SCF defaults (initial
guess, damping, k-mesh) are repeated inline so the user can tweak
without round-tripping through the SPEC.
"""
from __future__ import annotations

from pathlib import Path
from typing import Sequence

from examples.regression.core.spec import MoleculeSpec, PeriodicSpec, TestSystem


# ---- Periodic --------------------------------------------------------------

def _fmt_frac_block(atoms, label: str) -> str:
    """Format ``[(fx,fy,fz), ...]`` as a Python literal for one species."""
    rows = [f"{label}_FRAC = ["]
    for at in atoms:
        f0, f1, f2 = at.frac
        rows.append(f"    ({f0:.8f}, {f1:.8f}, {f2:.8f}),")
    rows.append("]")
    return "\n".join(rows)


def _format_periodic_script(
    spec: PeriodicSpec,
    *,
    basis: str,
    method: str,            # "rhf" | "rks-lda" | ...
    out_stem: str,
    provenance_block: str,
) -> str:
    # Group atoms by symbol so the generated script reads naturally.
    by_symbol: dict[str, list] = {}
    for at in spec.atoms:
        by_symbol.setdefault(at.symbol, []).append(at)

    # Lattice as a 3x3 list-of-lists (Å). The script multiplies by Å->Bohr.
    lat_lines = []
    for row in spec.lattice_ang:
        lat_lines.append(
            f"    [{row[0]:.8f}, {row[1]:.8f}, {row[2]:.8f}],"
        )

    # Build the per-species frac blocks.
    species_blocks = []
    for sym, ats in by_symbol.items():
        species_blocks.append(_fmt_frac_block(ats, sym.upper()))

    # And the unit_cell construction loop, one per species.
    cell_loop_lines = []
    for sym, ats in by_symbol.items():
        z = ats[0].z
        cell_loop_lines.append(
            f"    for fx, fy, fz in {sym.upper()}_FRAC:\n"
            f"        unit_cell.append(vq.Atom({z}, [fx*lat_bohr[0,0], fy*lat_bohr[1,1], fz*lat_bohr[2,2]]))"
        )
    cell_loop = "\n".join(cell_loop_lines)

    # SCF driver dispatch by method.
    if method == "rhf":
        scf_block = "\n".join([
            "    opts = vq.PeriodicRHFOptions()",
        ])
        run_call = "vq.run_rhf_periodic_scf(system, basis, kpts, opts, progress=plog)"
    elif method.startswith("rks-"):
        xc = method.split("-", 1)[1].upper()  # "lda" -> "LDA"
        scf_block = "\n".join([
            "    opts = vq.PeriodicKSOptions()",
            f"    opts.functional = {xc!r}",
            f"    opts.use_periodic_becke = {bool(spec.default_use_periodic_becke)}",
        ])
        run_call = "vq.run_rks_periodic_scf(system, basis, kpts, opts, progress=plog)"
    else:
        raise ValueError(
            f"emit_input: unsupported method {method!r} "
            "(supported: rhf, rks-lda, rks-pbe, rks-blyp, rks-b3lyp)"
        )

    initial_guess_block = (
        f"    opts.initial_guess = vq.InitialGuess.{spec.default_initial_guess.upper()}"
    )

    species_join = "\n\n".join(species_blocks)
    cutoff = spec.default_cutoff_bohr
    nuclear_cutoff = spec.default_nuclear_cutoff_bohr
    conv_tol = spec.default_conv_tol_energy
    damping = spec.default_damping
    max_iter = spec.default_max_iter
    kmesh = list(spec.default_kmesh)
    banner_str = f"{spec.id}  /  {method.upper()}  /  {basis}  /  EWALD_3D"

    return f'''"""{spec.id} ({spec.family}) -- auto-generated by ``vibeqc.fetch``.

Method:   {method}
Basis:    {basis}

{provenance_block}

Run:
    .venv/bin/python {out_stem}.py

# TODO: k-mesh convergence -- the {kmesh} mesh below is a heuristic
# seed (see examples/input-k-mesh-convergence.py for the convergence
# template).
"""
from __future__ import annotations

import os
import time
from pathlib import Path

import numpy as np

import vibeqc as vq
from vibeqc.progress import ProgressLogger

HERE = Path(__file__).resolve().parent
OUT_STEM = HERE / "{out_stem}"

ANGSTROM_TO_BOHR = 1.0 / 0.529177210903
HARTREE_TO_EV = 27.211386245988

LATTICE_ANG = np.array([
{chr(10).join(lat_lines)}
])

{species_join}


t_start = time.perf_counter()
plog = ProgressLogger(log_path=OUT_STEM.with_suffix(".out"), verbose=True)

with vq.perf_log(OUT_STEM.with_suffix(".perf")):
    plog.banner({banner_str!r})

    # ---- 1. Build the cell -------------------------------------------------
    lat_bohr = LATTICE_ANG * ANGSTROM_TO_BOHR
    unit_cell = []
{cell_loop}

    system = vq.PeriodicSystem(dim=3, lattice=lat_bohr, unit_cell=unit_cell)
    basis = vq.BasisSet(system.unit_cell_molecule(), {basis!r})
    vq.attach_symmetry(system, symprec=1e-4)
    plog.info(f"cell:       {{len(system.unit_cell)}} atoms")
    plog.info(
        f"spacegroup: {{system.symmetry.international_symbol}} "
        f"(SG {{system.symmetry.number}}, "
        f"point group {{system.symmetry.point_group}})"
    )
    plog.info(f"basis:      {basis} ({{basis.nbasis}} bf per cell)")

    # ---- 2. SCF ------------------------------------------------------------
{scf_block}
    opts.lattice_opts.coulomb_method = vq.CoulombMethod.EWALD_3D
    opts.lattice_opts.cutoff_bohr = {cutoff}
    opts.lattice_opts.nuclear_cutoff_bohr = {nuclear_cutoff}
    opts.conv_tol_energy = {conv_tol}
    opts.max_iter = {max_iter}
    opts.damping = {damping}
{initial_guess_block}

    kpts = vq.KPoints.monkhorst_pack(system, {kmesh}, symmetry=True)
    plog.info(
        f"k-mesh:     {kmesh[0]}x{kmesh[1]}x{kmesh[2]} -> {{len(kpts)}} IBZ points"
    )

    result = {run_call}
    plog.info(f"E/cell = {{result.energy:.8f}} Ha   ({{result.n_iter}} iters)")

    # ---- 3. HOMO-LUMO gap --------------------------------------------------
    n_occ = sum(int(at.Z) for at in system.unit_cell) // 2
    homo = max(float(eps[n_occ - 1]) for eps in result.mo_energies)
    lumo = min(float(eps[n_occ])     for eps in result.mo_energies)
    plog.info(
        f"HOMO max = {{homo*HARTREE_TO_EV:.3f}} eV   "
        f"LUMO min = {{lumo*HARTREE_TO_EV:.3f}} eV"
    )
    plog.info(f"Gap     = {{(lumo - homo) * HARTREE_TO_EV:.3f}} eV")

    # ---- 4. Runtime manifest ----------------------------------------------
    with plog.stage("write_system_manifest"):
        vq.write_system_manifest(
            OUT_STEM.with_suffix(".system"),
            wall_seconds=time.perf_counter() - t_start,
            basename=OUT_STEM.name,
            record_hostname=os.environ.get(
                "VIBEQC_NO_HOSTNAME", "",
            ).strip().lower() not in ("1", "true", "yes", "on"),
        )

    plog.banner("Done")
'''


# ---- Molecular -------------------------------------------------------------

def _format_molecule_script(
    spec: MoleculeSpec,
    *,
    basis: str,
    method: str,
    out_stem: str,
    provenance_block: str,
) -> str:
    atom_lines = []
    for at in spec.atoms:
        x, y, z = at.xyz_ang
        atom_lines.append(
            f"    vq.Atom({at.z}, [{x:.8f}, {y:.8f}, {z:.8f}]),  # {at.symbol}"
        )
    atom_block = "\n".join(atom_lines)

    # The molecular SCF wrappers attach a bundled basis' ECP sidecar
    # automatically (vibeqc.ecp_metadata.attach_inline_ecp_options_from_
    # basis_sidecar), so the generated script needs no ECP wiring of its
    # own. A basis that would need an ECP vibe-qc does not ship is refused
    # by run_job with a message naming the elements.
    _ecp_import_block = ""
    _ecp_config_block = ""
    _ecp_run_kwarg = ""

    return f'''"""{spec.id} -- auto-generated by ``vibeqc.fetch``.

Method:   {method}
Basis:    {basis}

{provenance_block}

Run:
    .venv/bin/python {out_stem}.py
"""
from __future__ import annotations

from pathlib import Path

import vibeqc as vq
{_ecp_import_block}
HERE = Path(__file__).resolve().parent
OUT_STEM = HERE / "{out_stem}"

ANGSTROM_TO_BOHR = 1.0 / 0.529177210903

# Geometry given in Å; convert to Bohr inline.
mol = vq.Molecule([
{atom_block}
])
# Convert positions to Bohr (vibe-qc internals are atomic units).
for atom in mol.atoms:
    atom.position = [c * ANGSTROM_TO_BOHR for c in atom.position]

{_ecp_config_block}
result = vq.run_job(
    mol,
    basis={basis!r},
    method={method!r},
    charge={spec.charge},
    multiplicity={spec.multiplicity},
    output=OUT_STEM,{_ecp_run_kwarg}
)
print(f"E = {{result.energy:.8f}} Ha")
'''


# ---- Public API -------------------------------------------------------------

def emit_input_script(
    spec: TestSystem,
    out_dir: Path,
    *,
    basis: str,
    method: str,
    overwrite: bool = True,
) -> Path:
    """Write an executable input script for ``spec`` at ``basis`` / ``method``.

    Output filename: ``input-<spec.id>-<basis>.py``. ``method`` is one
    of ``"rhf"``, ``"rks-lda"``, ``"rks-pbe"``, ``"rks-blyp"``,
    ``"rks-b3lyp"`` (periodic) or any vibe-qc ``run_job`` method
    (molecular).
    """
    out_dir = Path(out_dir).expanduser()
    out_dir.mkdir(parents=True, exist_ok=True)
    out_stem = f"input-{spec.id}-{basis}"
    if spec.provenance is None:
        prov_block = "Provenance: not recorded (hand-curated SPEC)."
    else:
        p = spec.provenance
        prov_block = (
            f"Provenance:\n"
            f"  source:    {p.source_db} / {p.source_id}\n"
            f"  url:       {p.source_url}\n"
            f"  reference: {p.original_reference or '(none)'}\n"
            f"  license:   {p.license or '(unknown)'}\n"
            f"  fetched:   {p.fetched_at}\n"
            f"  fetcher:   v{p.fetcher_version}"
        )
    if isinstance(spec, PeriodicSpec):
        text = _format_periodic_script(
            spec, basis=basis, method=method,
            out_stem=f"output-{spec.id}-{basis}",
            provenance_block=prov_block,
        )
    elif isinstance(spec, MoleculeSpec):
        text = _format_molecule_script(
            spec, basis=basis, method=method,
            out_stem=f"output-{spec.id}-{basis}",
            provenance_block=prov_block,
        )
    else:
        raise TypeError(
            f"emit_input_script: unsupported TestSystem type {type(spec).__name__}"
        )
    path = out_dir / f"{out_stem}.py"
    if path.exists() and not overwrite:
        raise FileExistsError(f"refusing to overwrite {path}")
    path.write_text(text, encoding="utf-8")
    return path
