"""Phase D4b-2b — pilot molecular-C6 validation for native D4.

Runs the end-to-end ``vibeqc.molecular_c6`` pipeline (RHF →
coupled imaginary-frequency CPHF polarizability α(iω) →
Casimir-Polder integral) on a pilot set of closed-shell H / C / N / O
molecules and compares the resulting homo-molecular C6 dispersion
coefficients against literature dipole-oscillator-strength-
distribution (DOSD) values.

This is the validation artefact for milestone D4b-2 of
``handovers/HANDOVER_D4_NATIVE.md`` — it exercises the whole reference-C6
machinery that the native D4 model (Phase D4b-4 onwards) will consume.

What to expect
--------------
The response level here is **coupled CPHF** — Hartree-Fock, no
electron correlation. CPHF systematically *under*-estimates molecular
polarizabilities (the missing correlation is dominantly a
polarizability-*increasing* effect), and since C6 ∝ α² the C6 values
come out ~15-30 % below the DOSD references. That is expected and not
a bug: the Casimir-Polder quadrature itself is exact (validated
analytically against the closed-form London formula in
``tests/test_dispersion_d4_refdata.py``). The production D4 reference
C6 dataset is generated by Phase D4b-4 (reference-data generation
over the D4b-3 reference-system catalogue), optionally at a
correlated response level; this pilot validates the *pipeline* and
the *trend* across the light elements.

Run:
    .venv/bin/python examples/molecular/d4_pilot_c6.py

Output:
    examples/molecular/d4_pilot_c6.report.md   — the comparison table

Reference C6 values: dipole-oscillator-strength-distribution data,
as collated in Grimme, Antony, Ehrlich, Krieg, *J. Chem. Phys.*
**132**, 154104 (2010) (the D3 paper) Table-of-molecular-C6 and the
underlying Meath-group DOSD compilations.
"""

from __future__ import annotations

from pathlib import Path

import vibeqc as vq
from vibeqc.dispersion_d4_refdata import molecular_c6

ANGSTROM = 1.8897259886


def _mol(atoms_angstrom):
    """Build a Molecule from [(Z, [x,y,z] Å), ...]."""
    return vq.Molecule([
        vq.Atom(Z, [c * ANGSTROM for c in xyz]) for Z, xyz in atoms_angstrom
    ], charge=0, multiplicity=1)


# ---------------------------------------------------------------------
# Pilot reference set — closed-shell H/C/N/O molecules at experimental
# geometries. O2 (triplet) is deliberately excluded: the coupled-
# response path is RHF-only. Element coverage: H (H2, all hydrides),
# C (CH4 sp³, C2H4 sp², C2H2 sp, CO, CO2), N (N2, NH3), O (H2O, CO,
# CO2) — a spread of coordination environments.
# ---------------------------------------------------------------------

PILOT_SYSTEMS = {
    # name: (atoms in Å, literature homo-molecular C6 in a.u.)
    "H2":   ([(1, [0.0, 0.0, 0.0]), (1, [0.0, 0.0, 0.741])],            12.1),
    "N2":   ([(7, [0.0, 0.0, 0.0]), (7, [0.0, 0.0, 1.098])],            73.4),
    "CO":   ([(6, [0.0, 0.0, 0.0]), (8, [0.0, 0.0, 1.128])],            81.4),
    "H2O":  ([(8, [0.0, 0.0, 0.0]),
              (1, [0.0,  0.7575, 0.5871]),
              (1, [0.0, -0.7575, 0.5871])],                             45.3),
    "NH3":  ([(7, [0.0, 0.0, 0.1128]),
              (1, [0.0,        0.9377, -0.2632]),
              (1, [0.8121,    -0.4689, -0.2632]),
              (1, [-0.8121,   -0.4689, -0.2632])],                      89.1),
    "CH4":  ([(6, [0.0, 0.0, 0.0]),
              (1, [0.6276,  0.6276,  0.6276]),
              (1, [-0.6276, -0.6276, 0.6276]),
              (1, [-0.6276,  0.6276, -0.6276]),
              (1, [0.6276,  -0.6276, -0.6276])],                       129.7),
    "C2H2": ([(6, [0.0, 0.0,  0.6015]), (6, [0.0, 0.0, -0.6015]),
              (1, [0.0, 0.0,  1.6625]), (1, [0.0, 0.0, -1.6625])],     204.1),
    "C2H4": ([(6, [0.0, 0.0,  0.6695]), (6, [0.0, 0.0, -0.6695]),
              (1, [0.0,  0.9289,  1.2321]), (1, [0.0, -0.9289,  1.2321]),
              (1, [0.0,  0.9289, -1.2321]), (1, [0.0, -0.9289, -1.2321])],
                                                                       300.2),
    "CO2":  ([(6, [0.0, 0.0, 0.0]),
              (8, [0.0, 0.0,  1.162]), (8, [0.0, 0.0, -1.162])],       158.7),
}

ORBITAL_BASIS = "aug-cc-pvdz"   # diffuse functions — essential for α
N_FREQ = 23                     # imaginary-frequency quadrature points


def main() -> None:
    here = Path(__file__).resolve().parent
    rows = []
    print(f"D4b-2b pilot molecular-C6 validation — {ORBITAL_BASIS}, "
          f"{N_FREQ}-point grid, coupled CPHF\n")
    print(f"  {'system':6s} {'C6 vibe-qc':>12s} {'C6 lit (DOSD)':>14s} "
          f"{'ratio':>8s}  {'dev %':>8s}")
    for name, (atoms, c6_lit) in PILOT_SYSTEMS.items():
        mol = _mol(atoms)
        basis = vq.BasisSet(mol, ORBITAL_BASIS)
        c6 = molecular_c6(mol, basis, n_freq=N_FREQ)
        ratio = c6 / c6_lit
        dev = 100.0 * (c6 - c6_lit) / c6_lit
        rows.append((name, c6, c6_lit, ratio, dev))
        print(f"  {name:6s} {c6:12.3f} {c6_lit:14.1f} "
              f"{ratio:8.3f}  {dev:+8.1f}")

    # Mean absolute relative deviation — the headline pilot metric.
    mard = sum(abs(r[4]) for r in rows) / len(rows)
    mean_ratio = sum(r[3] for r in rows) / len(rows)
    print(f"\n  mean ratio (vibe-qc / lit): {mean_ratio:.3f}")
    print(f"  mean abs relative deviation: {mard:.1f} %")

    report = here / "d4_pilot_c6.report.md"
    lines = [
        "# D4b-2b — pilot molecular-C6 validation",
        "",
        f"Pipeline: `vibeqc.molecular_c6` — RHF → coupled imaginary-",
        f"frequency CPHF α(iω) → Casimir-Polder. Basis `{ORBITAL_BASIS}`,",
        f"{N_FREQ}-point imaginary-frequency grid.",
        "",
        "Literature C6: DOSD values (Grimme et al. JCP 132, 154104 (2010)",
        "and the underlying Meath-group dipole-oscillator-strength data).",
        "",
        "| System | C6 vibe-qc (a.u.) | C6 lit (a.u.) | ratio | dev % |",
        "|--------|------------------:|--------------:|------:|------:|",
    ]
    for name, c6, c6_lit, ratio, dev in rows:
        lines.append(f"| {name} | {c6:.3f} | {c6_lit:.1f} | "
                     f"{ratio:.3f} | {dev:+.1f} |")
    lines += [
        "",
        f"**Mean ratio (vibe-qc / lit): {mean_ratio:.3f}**",
        f"**Mean absolute relative deviation: {mard:.1f} %**",
        "",
        "The coupled-CPHF level systematically under-estimates C6 "
        "(no electron correlation; C6 ∝ α²). The *trend* across the "
        "light elements and the *pipeline* are what this pilot "
        "validates — the production D4 reference C6 dataset is "
        "generated by Phase D4b-4 (reference-data generation), "
        "optionally at a correlated response level.",
    ]
    report.write_text("\n".join(lines) + "\n")
    print(f"\n  report written to {report}")


if __name__ == "__main__":
    main()
