"""GaP — RHF on pob-tzvp (Γ-only).

This input is generated by ``examples/basisset_dev/_generator.py``
and is intentionally self-contained: lattice vectors and fractional
coordinates are baked in, no external CIF / Materials Project / ASE
fetch at runtime. Edit ``vibe_basis.io.structures`` (in the
``vibe-basis`` package) and re-run the generator rather than
tweaking this file directly.

Compound metadata:
    formula:        GaP
    space group:    F-43m
    crystal system: cubic
    a, b, c (Å):    5.4480, 5.4480, 5.4480
    α, β, γ (deg):  90.00, 90.00, 90.00
    n_atoms in cell: 8
    multiplicity:   1
    structure src:  PT2013 Ref. 79
    appears in:     PT2013-T8, VO2019-T6

    Acceptance gate (when REQUIREMENTS-PERIODIC R2 multi-k lands): SCF energy at converged Pack-Monkhorst grid agrees with the cited PT2013 reference to 1 mHa.

Today's status: Γ-point only because vibe-qc multi-k periodic SCF
(REQUIREMENTS-PERIODIC R2) is not yet wired for production-size
basis sets. The generator emits the multi-k variant alongside this
Γ-point version once R2 lands. The functional registry alias
``"PW1PW"`` (R4) is the second prerequisite for direct comparison
against PT2013 SI Table 1.
"""

import numpy as np

import vibeqc as vq


def main() -> None:
    lattice = np.array([
        [10.2952271859, 0.0000000000, 0.0000000000],
        [0.0000000000, 10.2952271859, 0.0000000000],
        [0.0000000000, 0.0000000000, 10.2952271859],
    ])  # bohr

    unit_cell = [
        vq.Atom(31, [  0.0000000000,   0.0000000000,   0.0000000000]),  # Z31 frac=(0.000,0.000,0.000)
        vq.Atom(31, [  5.1476135929,   5.1476135929,   0.0000000000]),  # Z31 frac=(0.500,0.500,0.000)
        vq.Atom(31, [  5.1476135929,   0.0000000000,   5.1476135929]),  # Z31 frac=(0.500,0.000,0.500)
        vq.Atom(31, [  0.0000000000,   5.1476135929,   5.1476135929]),  # Z31 frac=(0.000,0.500,0.500)
        vq.Atom(15, [  2.5738067965,   2.5738067965,   2.5738067965]),  # P frac=(0.250,0.250,0.250)
        vq.Atom(15, [  7.7214203894,   7.7214203894,   2.5738067965]),  # P frac=(0.750,0.750,0.250)
        vq.Atom(15, [  7.7214203894,   2.5738067965,   7.7214203894]),  # P frac=(0.750,0.250,0.750)
        vq.Atom(15, [  2.5738067965,   7.7214203894,   7.7214203894]),  # P frac=(0.250,0.750,0.750)
    ]

    sysp = vq.PeriodicSystem(dim=3, lattice=lattice, unit_cell=unit_cell)
    basis = vq.BasisSet(sysp.unit_cell_molecule(), "pob-tzvp")

    opts = vq.PeriodicSCFOptions()
    opts.lattice_opts.coulomb_method = vq.CoulombMethod.EWALD_3D
    # Cutoffs sized for the conventional cubic cell: lattice constant
    # plus a generous margin for Coulomb tail screening. Tighten if
    # the SCF doesn't converge cleanly.
    opts.lattice_opts.cutoff_bohr = max(15.0, 3.0 * float(np.linalg.norm(lattice[0])))
    opts.lattice_opts.nuclear_cutoff_bohr = opts.lattice_opts.cutoff_bohr * 1.5
    opts.max_iter = 60

    print(f"  cell:       {lattice[0][0]:.4f} bohr (= 5.4480 Å)")
    print(f"  basis:      pob-tzvp ({basis.nshells} shells, {basis.nbasis} fns)")
    print(f"  electrons:  {sysp.unit_cell_molecule().n_electrons()} per cell")

    result = vq.run_rhf_periodic_gamma_scf(
        sysp, basis, opts, omega=0.5, spacing_bohr=0.5, progress=True,
    )

    print()
    print(f"  E (RHF, Γ-only) = {result.energy:.8f} Ha per unit cell")
    print(f"  converged   = {result.converged}  ({result.n_iter} iters)")


if __name__ == "__main__":
    main()
