#!/usr/bin/env python3
"""Generate the Cartesian → spherical transform table for the C++
pair-FT kernel.

The Python kernel in ``vibeqc._aopair_ft.cart_to_sph_matrix`` builds
each matrix by least-squares fitting random unit-sphere samples to
the real spherical harmonics — fine on first call (cached), but the
C++ kernel needs the same matrices without a random-seeded fit at
runtime. This script computes the matrices once via the Python
implementation (which itself uses the libint real-Y_lm convention via
``vibeqc.aux_basis._real_sph_harm``) and emits them as a C++ static
table at ``cpp/include/vibeqc/cart_to_sph_data.hpp``.

Usage:
    .venv/bin/python scripts/codegen_cart_to_sph.py

Re-run after touching either the libint conventions in
``vibeqc.aux_basis._real_sph_harm`` or
``vibeqc._aopair_ft.cart_to_sph_matrix``; the generated header is
committed so contributors don't need to regenerate just to build.

The output is *not* a human-edited file. If you find yourself
hand-tweaking the table, regenerate via this script instead.
"""

from __future__ import annotations

import pathlib
import textwrap

import numpy as np


# Max L the table covers, and the hard ceiling on libint's build-time
# max_am: scripts/_libint_max_am.sh refuses a spec above this, because
# ao_pair_fourier_transform_bloch throws on any shell past kMaxL and a
# higher libint would emit integrals the periodic stack cannot consume.
# libint's own max_am is configurable (default 5 at derivative order 0;
# see scripts/build_libint.sh), so the two are no longer locked together
# — this value is the ceiling, not a mirror.
#
# Past L = 6 the cart_to_sph numerical fit gets rank-revealing and needs
# a larger sample set — do not bump without re-validating the fit
# precision, and bump VIBEQC_LIBINT_MAX_AM_CEILING in lockstep.
MAX_L = 6


def main() -> None:
    from vibeqc._aopair_ft import (
        cart_to_sph_matrix,
        cartesian_components_for_l,
    )

    repo_root = pathlib.Path(__file__).resolve().parent.parent
    out_path = repo_root / "cpp" / "include" / "vibeqc" / "cart_to_sph_data.hpp"

    lines: list[str] = []
    lines.append("// AUTOGENERATED — do not hand-edit.")
    lines.append("//")
    lines.append("// Generated by scripts/codegen_cart_to_sph.py — re-run after")
    lines.append("// changing the libint real-Y_lm convention used by")
    lines.append("// vibeqc._aopair_ft.cart_to_sph_matrix. The Python kernel is")
    lines.append("// the source of truth for the convention; this table is the")
    lines.append("// C++ kernel's mechanical mirror.")
    lines.append("//")
    lines.append("// Coverage: L = 0 .. {}. This is also the ceiling on libint's".format(MAX_L))
    lines.append("// build-time max_am (scripts/_libint_max_am.sh): building")
    lines.append("// libint higher would emit integrals the periodic AO-pair FT")
    lines.append("// cannot transform, since it throws on any shell past kMaxL.")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <array>")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append("namespace vibeqc::cart_to_sph_data {")
    lines.append("")
    lines.append(f"inline constexpr int kMaxL = {MAX_L};")
    lines.append("")
    lines.append("// Per-L Cartesian components (i, j, k) with i + j + k = L,")
    lines.append("// in the order ``vibeqc._aopair_ft.cartesian_components_for_l``")
    lines.append("// emits — x-power decreases first, then y, then z. Matches")
    lines.append("// libint's Cartesian-shell ordering.")
    lines.append("struct CartIdx { int i; int j; int k; };")
    lines.append("")

    cart_blocks: list[str] = []
    sph_blocks: list[str] = []

    for L in range(MAX_L + 1):
        cart = cartesian_components_for_l(L)
        C = cart_to_sph_matrix(L)
        assert C.shape == (2 * L + 1, (L + 1) * (L + 2) // 2), (
            f"cart_to_sph_matrix(L={L}) returned shape {C.shape}; "
            f"expected ({2*L+1}, {(L+1)*(L+2)//2})"
        )

        cart_entries = ", ".join(f"{{{i},{j},{k}}}" for (i, j, k) in cart)
        cart_blocks.append(
            f"inline constexpr std::array<CartIdx, {len(cart)}> "
            f"kCart{L} = {{{{ {cart_entries} }}}};\n"
        )

        # Emit C[m, a] row-major with full hex-float precision so the
        # rebuilt header is bit-identical to the original Python fit.
        flat = [float(x) for x in C.flatten()]
        body_entries = ",\n    ".join(f"{x:.17e}" for x in flat)
        sph_blocks.append(
            f"inline constexpr std::array<double, {C.size}> "
            f"kSph{L} = {{\n    {body_entries}\n}};\n"
        )

    lines.append("// --- Cartesian-component ordering per L ---")
    for block in cart_blocks:
        lines.append(block)

    lines.append("// --- Cart -> sph transform matrices ---")
    lines.append("// Row-major (n_sph, n_cart) = ((2L+1), (L+1)(L+2)/2).")
    lines.append("// Indexing: kSphL[m * n_cart + a] with m in [0, 2L] and")
    lines.append("// a iterating the kCartL ordering.")
    for block in sph_blocks:
        lines.append(block)

    # Pointer dispatch by L — keeps the kernel-side API uniform.
    lines.append("// --- Per-L dispatch ---")
    lines.append("inline constexpr std::size_t n_cart_for_l(int L) noexcept {")
    lines.append("    return static_cast<std::size_t>((L + 1) * (L + 2) / 2);")
    lines.append("}")
    lines.append("inline constexpr std::size_t n_sph_for_l(int L) noexcept {")
    lines.append("    return static_cast<std::size_t>(2 * L + 1);")
    lines.append("}")
    lines.append("")
    lines.append("inline const double* sph_table_for_l(int L) noexcept {")
    lines.append("    switch (L) {")
    for L in range(MAX_L + 1):
        lines.append(f"        case {L}: return kSph{L}.data();")
    lines.append("        default: return nullptr;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("inline const CartIdx* cart_table_for_l(int L) noexcept {")
    lines.append("    switch (L) {")
    for L in range(MAX_L + 1):
        lines.append(f"        case {L}: return kCart{L}.data();")
    lines.append("        default: return nullptr;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace vibeqc::cart_to_sph_data")
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path}  ({len(lines)} lines, L = 0..{MAX_L})")


if __name__ == "__main__":
    main()
