#!/usr/bin/env python3
"""Generate the native D3(BJ) parameter registry from simple-dftd3.

The input is ``assets/parameters.toml`` from the audited simple-dftd3
revision recorded below.  The generated C++ include contains numerical
scientific constants and functional labels only.  No implementation code
is copied.

Usage:
    python scripts/extract_d3bj_parameters.py path/to/parameters.toml
"""
from __future__ import annotations

import hashlib
import sys
import tomllib
from pathlib import Path


_SOURCE_REVISION = "cc9c1f634ea06ba8c283f174aa43faa08b3b98ab"
_SOURCE_SHA256 = "486db6f37c4feff263183c5f45800569220e07cb4ce870e90838415008217a8d"
_EXPECTED_ENTRIES = 156
_REPO = Path(__file__).resolve().parent.parent
_OUT = _REPO / "cpp" / "src" / "dispersion_params_data.inc"


def _entries(data: dict) -> list[tuple[str, float, float, float, float]]:
    rows = []
    for name, methods in data.get("parameter", {}).items():
        bj = methods.get("d3", {}).get("bj")
        if bj is None:
            continue
        rows.append((
            name,
            float(bj.get("s6", 1.0)),
            float(bj["s8"]),
            float(bj["a1"]),
            float(bj["a2"]),
        ))
    if len(rows) != _EXPECTED_ENTRIES:
        raise SystemExit(
            f"expected {_EXPECTED_ENTRIES} D3(BJ) parameter sets, got {len(rows)}"
        )
    normalized = [name.lower().replace("-", "") for name, *_ in rows]
    if len(set(normalized)) != len(normalized):
        raise SystemExit("functional-name normalization produced a collision")
    return rows


def _render(rows: list[tuple[str, float, float, float, float]]) -> str:
    lines = [
        "// Auto-generated by scripts/extract_d3bj_parameters.py; do not edit.",
        "//",
        "// Numerical D3(BJ) damping parameters extracted from simple-dftd3",
        f"// revision {_SOURCE_REVISION}, assets/parameters.toml",
        "// (LGPL-3.0-or-later). The DOI attached to each fit remains in the",
        "// pinned upstream source; vibe-qc's D3 citations cover the model.",
    ]
    for name, s6, s8, a1, a2 in rows:
        key = name.lower().replace("-", "")
        lines.append(
            f'    {{"{key}", {{{s6:.10g}, {s8:.10g}, {a1:.10g}, {a2:.10g}, 0.0}}}},'
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    source = Path(sys.argv[1])
    raw = source.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != _SOURCE_SHA256:
        raise SystemExit(
            f"unexpected parameters.toml sha256 {digest}; expected "
            f"{_SOURCE_SHA256} from simple-dftd3 {_SOURCE_REVISION}"
        )
    rows = _entries(tomllib.loads(raw.decode()))
    _OUT.write_text(_render(rows))
    print(f"wrote {_OUT} ({len(rows)} D3(BJ) parameter sets)")


if __name__ == "__main__":
    main()
