#!/usr/bin/env python3
"""Generate the native H-Ar D3 C6 reference grid from simple-dftd3.

The input is ``src/dftd3/reference.f90`` from the audited simple-dftd3
revision recorded below.  The generated C++ include contains numerical
scientific constants only: the active H-Ar corner of ``reference_cn`` and
``reference_c6``.  No Fortran implementation code is copied.

Usage:
    python scripts/extract_d3_c6_reference.py path/to/reference.f90

Fetch the pinned source, for example::

    curl -L -o reference.f90 \
      https://raw.githubusercontent.com/dftd3/simple-dftd3/\
cc9c1f634ea06ba8c283f174aa43faa08b3b98ab/src/dftd3/reference.f90
"""
from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path


_SOURCE_REVISION = "cc9c1f634ea06ba8c283f174aa43faa08b3b98ab"
_SOURCE_SHA256 = "76368b2d3aa682216e82292b4170edf704b8e88838b32d033722f18710217c0b"
_MAX_Z = 18
_MAX_REF = 7
_EXPECTED_FLAT_VALUES = 262_444
_EXPECTED_ACTIVE_VALUES = 1_443
_REPO = Path(__file__).resolve().parent.parent
_OUT = _REPO / "cpp" / "src" / "dispersion_c6_reference.inc"


def _between(text: str, start: str, end: str) -> str:
    try:
        i = text.index(start)
        j = text.index(end, i)
    except ValueError as exc:
        raise SystemExit(f"simple-dftd3 reference marker missing: {exc}") from exc
    return text[i:j]


def _parse_counts(text: str) -> list[int]:
    block = _between(
        text,
        "integer, parameter :: number_of_references",
        "real(wp), parameter :: reference_cn",
    ).split("=", 1)[1]
    uncommented = "\n".join(line.split("!", 1)[0] for line in block.splitlines())
    values = [int(value) for value in re.findall(r"\b\d+\b", uncommented)]
    if len(values) < _MAX_Z:
        raise SystemExit(f"expected at least {_MAX_Z} reference counts, got {len(values)}")
    return values[:_MAX_Z]


def _parse_reference_cn(text: str, counts: list[int]) -> list[list[float]]:
    block = _between(
        text,
        "real(wp), parameter :: reference_cn",
        "real(wp), allocatable :: reference_c6",
    )
    values = [
        float(value)
        for value in re.findall(r"([+-]?\d+\.\d+)_wp", block)
    ]
    if len(values) < _MAX_Z * _MAX_REF:
        raise SystemExit("reference_cn table is shorter than the H-Ar corner")
    return [
        values[z * _MAX_REF:z * _MAX_REF + counts[z]]
        for z in range(_MAX_Z)
    ]


def _parse_flat_c6(text: str) -> list[float]:
    block = _between(text, "c6ab_view(1:2000)", "end subroutine copy_c6")
    values = [
        float(value)
        for value in re.findall(r"([+-]?\d+(?:\.\d*)?)_wp", block)
    ]
    if len(values) != _EXPECTED_FLAT_VALUES:
        raise SystemExit(
            f"expected {_EXPECTED_FLAT_VALUES} flattened C6 values, got {len(values)}"
        )
    return values


def _active_rows(
    counts: list[int],
    reference_cn: list[list[float]],
    flat_c6: list[float],
) -> list[tuple[int, int, float, float, float]]:
    rows: list[tuple[int, int, float, float, float]] = []
    for high_z in range(1, _MAX_Z + 1):
        for low_z in range(1, high_z + 1):
            pair = low_z + high_z * (high_z - 1) // 2
            for low_ref in range(counts[low_z - 1]):
                for high_ref in range(counts[high_z - 1]):
                    offset = high_ref + _MAX_REF * low_ref + _MAX_REF**2 * (pair - 1)
                    rows.append((
                        high_z,
                        low_z,
                        flat_c6[offset],
                        reference_cn[high_z - 1][high_ref],
                        reference_cn[low_z - 1][low_ref],
                    ))
    if len(rows) != _EXPECTED_ACTIVE_VALUES:
        raise SystemExit(
            f"expected {_EXPECTED_ACTIVE_VALUES} active H-Ar values, got {len(rows)}"
        )
    return rows


def _render(rows: list[tuple[int, int, float, float, float]]) -> str:
    lines = [
        "// Auto-generated by scripts/extract_d3_c6_reference.py; do not edit.",
        "//",
        "// Numerical H-Ar D3 reference constants extracted from simple-dftd3",
        f"// revision {_SOURCE_REVISION},",
        "// src/dftd3/reference.f90 (LGPL-3.0-or-later). Underlying method:",
        "// Grimme et al., J. Chem. Phys. 132, 154104 (2010),",
        "// doi:10.1063/1.3382344.",
        f"constexpr std::array<C6Ref, {_EXPECTED_ACTIVE_VALUES}> kC6ReferenceTable = {{{{",
    ]
    for high_z, low_z, c6, high_cn, low_cn in rows:
        lines.append(
            f"    {{{high_z:2d}, {low_z:2d}, {c6:.10g}, "
            f"{high_cn:.10g}, {low_cn:.10g}}},"
        )
    lines.extend(["}};", ""])
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    source = Path(sys.argv[1])
    raw = source.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != _SOURCE_SHA256:
        raise SystemExit(
            f"unexpected reference.f90 sha256 {digest}; expected {_SOURCE_SHA256} "
            f"from simple-dftd3 {_SOURCE_REVISION}"
        )
    text = raw.decode()
    counts = _parse_counts(text)
    reference_cn = _parse_reference_cn(text, counts)
    flat_c6 = _parse_flat_c6(text)
    rows = _active_rows(counts, reference_cn, flat_c6)
    _OUT.write_text(_render(rows))
    print(f"wrote {_OUT} ({len(rows)} active H-Ar C6 references)")


if __name__ == "__main__":
    main()
