#!/usr/bin/env python3
"""Extract the DFT-D3 r0ab cutoff-radii table into python/vibeqc/_d3_r0ab.py.

One-shot maintainer-side data extraction (committed output), mirroring
scripts/extract_gcp_data.py. The r0ab radii are the DFT-D3 ab-initio
cut-off radii (Grimme, Antony, Ehrlich, Krieg, J. Chem. Phys. 132,
154104 (2010), doi:10.1063/1.3382344). They are needed by the
composite-3c short-range bond (SRB) correction and the damped gCP term.

Source of the literal values: grimme-lab/gcp src/gcp.f90, subroutine
setr0ab (LGPL-3.0-or-later) — a 4465-element packed lower triangle of
the symmetric 94x94 matrix, unpacked as r(i,j)=r(j,i)=packed[k]/autoang
(bohr), exactly as the Fortran does.

Usage:
    python scripts/extract_d3_r0ab.py path/to/gcp.f90

Fetch the source first, e.g.:
    curl -L -o gcp.f90 \\
      https://raw.githubusercontent.com/grimme-lab/gcp/main/src/gcp.f90
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

_AUTOANG = 0.5291772083
_REPO = Path(__file__).resolve().parent.parent
_OUT = _REPO / "python" / "vibeqc" / "_d3_r0ab.py"


def parse_setr0ab(src_text: str) -> list[float]:
    """Return the 4465 packed r0ab values from the setr0ab subroutine."""
    m = re.search(r"subroutine setr0ab\b.*?end subroutine setr0ab",
                  src_text, re.S)
    if not m:
        raise SystemExit("setr0ab subroutine not found in source")
    vals: list[float] = []
    for block in re.findall(r"=\(/(.*?)/\)", m.group(0), re.S):
        vals.extend(float(x) for x in re.findall(r"\d+\.\d+", block))
    if len(vals) != 4465:
        raise SystemExit(f"expected 4465 packed values, got {len(vals)}")
    return vals


def render_module(vals: list[float]) -> str:
    lines = [
        '"""DFT-D3 ab-initio cutoff radii r0ab(Z_a, Z_b), in bohr.',
        "",
        "Used by the composite-3c short-range bond (SRB) correction and the",
        "damped geometric-counterpoise (gCP) term — the single 94x94 table",
        "from Grimme's DFT-D3, shared by both corrections.",
        "",
        "Provenance / license (CLAUDE.md s1, s8):",
        "* Source: grimme-lab/gcp src/gcp.f90, subroutine setr0ab",
        "  (LGPL-3.0-or-later). Lower triangle of the symmetric 94x94 matrix,",
        "  4465 packed entries, r(i,j)=r(j,i)=packed[k]/autoang (bohr).",
        "* Underlying data: Grimme, Antony, Ehrlich, Krieg, J. Chem. Phys.",
        "  132, 154104 (2010), doi:10.1063/1.3382344.",
        "* autoang = 0.5291772083 (matches setr0ab).",
        "",
        "Auto-generated by scripts/extract_d3_r0ab.py — do not hand-edit the",
        'packed tuple."""',
        "from __future__ import annotations",
        "",
        "_AUTOANG = 0.5291772083",
        "MAX_ELEM = 94",
        "",
        "# Packed lower triangle (k=0..4464) exactly as gcp.f90 setr0ab.",
        "_R0AB_PACKED = (",
    ]
    for i in range(0, len(vals), 8):
        lines.append("    " + ", ".join(f"{v:.4f}" for v in vals[i:i + 8]) + ",")
    lines += [
        ")",
        "",
        "_R0AB = None  # lazily built symmetric (MAX_ELEM+1) table, 1-indexed by Z",
        "",
        "",
        "def _build():",
        "    global _R0AB",
        "    n = MAX_ELEM",
        "    r = [[0.0] * (n + 1) for _ in range(n + 1)]",
        "    k = 0",
        "    for i in range(1, n + 1):",
        "        for j in range(1, i + 1):",
        "            v = _R0AB_PACKED[k] / _AUTOANG",
        "            r[i][j] = v",
        "            r[j][i] = v",
        "            k += 1",
        "    _R0AB = r",
        "",
        "",
        "def r0ab(z_a: int, z_b: int) -> float:",
        '    """Return the D3 cutoff radius r0ab(z_a, z_b) in bohr."""',
        "    if _R0AB is None:",
        "        _build()",
        "    return _R0AB[int(z_a)][int(z_b)]",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    vals = parse_setr0ab(Path(sys.argv[1]).read_text())
    _OUT.write_text(render_module(vals))
    print(f"wrote {_OUT} ({len(vals)} packed values)")


if __name__ == "__main__":
    main()
