#!/usr/bin/env python3
"""Generate ``cpp/src/lebedev_data.cpp`` from ``scipy.integrate.lebedev_rule``.

The Lebedev-Laikov angular grids are mathematical constants from

  Lebedev, V. I., "Quadratures on a sphere", USSR Comput. Math. Math. Phys.
  16, 10 (1976).
  Laikov, D. N. & Lebedev, V. I., "A quadrature formula for the sphere of
  the 131st algebraic order of accuracy", Russ. Acad. Sci. Dokl. Math.
  59, 477 (1999).

We use scipy as a numerically-vetted source (BSD-3, vetted by independent
test suites against the original Lebedev tables). The output is a pure
C++ data file checked into the repo — no runtime Python dependency for
the C++ core.

Weight convention: scipy normalises ``Σ w_k = 4π`` (full-sphere area).
This matches the convention vibe-qc's existing product-grid angular
weights use (``w = w_θ · Δφ`` with ``∫ dΩ = 4π``), so a Lebedev grid
plugs in as a drop-in replacement.

Standard tier ladder (matches the PySCF / ORCA / Q-Chem default ladder):

  order   pts   typical use
  -----   ---   ----------------------------------------------------
    5      14   ORCA inner-core region
    7      26   ORCA inner region
   11      50   sparse / NWChem first region
   15      86   PySCF NWChem second region
   17     110   coarse SCF
   23     194   light hybrid / lite tier (NWChem ``xc lite``)
   27     266   PySCF level-3 NWChem shoulder (H-Ne)
   29     302   default for first-row XC (PySCF level 3, period 1-2)
   31     350   PySCF level-3 NWChem shoulder (Na+)
   35     434   default for heavier elements (PySCF level 3, period 3+)
   41     590   tight (PySCF level 5)
   47     770   very tight
   53     974   extra-tight (rarely needed)

Re-run after a scipy upgrade to verify the data still matches; commit
diff = bug in scipy or data corruption.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from scipy.integrate import lebedev_rule


# The full ladder the C++ code will expose. Adding more orders is
# straight-forward — just extend this list.
STANDARD_ORDERS = [5, 7, 11, 15, 17, 23, 27, 29, 31, 35, 41, 47, 53]


def _format_block(order: int) -> tuple[str, int]:
    """Return ``(C++ snippet, n_pts)`` for one Lebedev order."""
    pts, wts = lebedev_rule(order)
    n_pts = len(wts)
    assert pts.shape == (3, n_pts), f"unexpected pts shape: {pts.shape}"
    # Validate weight sum to 4π — the published normalisation.
    if not np.isclose(wts.sum(), 4.0 * np.pi, atol=1e-12):
        raise ValueError(
            f"order {order}: weights sum to {wts.sum():.16e}, "
            f"expected 4π = {4.0 * np.pi:.16e}")
    # Validate unit-vector points.
    norms = np.linalg.norm(pts, axis=0)
    if not np.allclose(norms, 1.0, atol=1e-12):
        raise ValueError(
            f"order {order}: max norm deviation {np.abs(norms - 1).max():.2e}")

    lines = [
        f"// --- Lebedev order {order} ({n_pts} points) ---",
        f"static const double kLebedev_{order}_data[] = {{",
    ]
    # Interleaved (x, y, z, w) for memory locality.
    for i in range(n_pts):
        lines.append(
            f"    {pts[0, i]:+.17e}, {pts[1, i]:+.17e}, "
            f"{pts[2, i]:+.17e}, {wts[i]:+.17e},")
    lines.append("};")
    return "\n".join(lines), n_pts


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    out_path = repo_root / "cpp" / "src" / "lebedev_data.cpp"

    blocks = []
    sizes: list[tuple[int, int]] = []  # (order, n_pts)
    for order in STANDARD_ORDERS:
        block, n_pts = _format_block(order)
        blocks.append(block)
        sizes.append((order, n_pts))

    # Build the dispatch table.
    table_lines = [
        "// Public dispatch table — keep ordered by ``order``.",
        "static const LebedevTier kLebedevTiers[] = {",
    ]
    for order, n_pts in sizes:
        table_lines.append(
            f"    {{ {order}, {n_pts}, kLebedev_{order}_data }},")
    table_lines.append("};")
    table_lines.append(
        f"static constexpr std::size_t kLebedevTierCount = "
        f"{len(sizes)};")

    header = f"""// Generated by ``scripts/generate_lebedev_data.py`` — do NOT edit by hand.
//
// Lebedev-Laikov spherical-quadrature grids
//   Lebedev, V. I. (1976), USSR Comput. Math. Math. Phys. 16, 10.
//   Laikov, D. N. & Lebedev, V. I. (1999), Russ. Acad. Sci. Dokl. Math. 59, 477.
//
// Numerical values produced via ``scipy.integrate.lebedev_rule``
// (BSD-3-Clause, independently tested against the published tables).
// Weights normalised so Σ w_k = 4π (full-sphere area), matching the
// convention vibe-qc's product-grid angular weights already use.
//
// Layout: each row is (x, y, z, w) for one point — interleaved so the
// row-stride is 4 doubles. Points are unit vectors on the sphere.

#include "vibeqc/lebedev_data.hpp"

#include <cstddef>

namespace vibeqc {{

{chr(10).join(blocks)}

{chr(10).join(table_lines)}

const LebedevTier* lebedev_tiers() noexcept {{
    return kLebedevTiers;
}}
std::size_t lebedev_tier_count() noexcept {{
    return kLebedevTierCount;
}}

}}  // namespace vibeqc
"""
    out_path.write_text(header, encoding="utf-8")
    print(f"wrote {out_path}: {len(sizes)} tiers, "
          f"{sum(n for _, n in sizes)} total points")
    return 0


if __name__ == "__main__":
    sys.exit(main())
