"""Sphinx configuration for the vibe-qc documentation.

Build locally with ``make html`` (from the docs/ directory) or
``sphinx-build -b html docs/ docs/_build/html`` from the repo root.

Naming convention
-----------------
* The human-facing brand is **vibe-qc** (with hyphen, matching the
  domain ``vibe-qc.com``). Use this in docs prose, titles, page
  headers, etc.
* The Python package on disk is ``vibeqc`` (no hyphen) because Python
  identifiers can't carry dashes; ``import vibeqc`` is what users type
  in code. Use ``vibeqc`` inside code snippets only.
"""

from __future__ import annotations

import datetime
import os
import sys
from pathlib import Path

# Make the vibe-qc Python package importable when Sphinx runs autodoc.
# The compiled extension module must already be installed
# (``pip install -e .``) for the Python API reference to build without
# ImportErrors.
_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT / "python"))

# Local Sphinx extensions live in docs/_ext/. The vibeqc-cite
# directive that renders citations from
# python/vibeqc/output/citations/database.toml is the load-bearing
# entry today (no autodoc import dependency — reads TOML directly).
sys.path.insert(0, str(_REPO_ROOT / "docs" / "_ext"))


# --- Project metadata ------------------------------------------------------

project = "vibe-qc"
author = "Michael F. Peintinger"
copyright = f"{datetime.date.today().year}, {author}"


# Pull version from the installed distribution if vibe-qc is pip-
# installed in this Python; otherwise fall back to parsing
# ``pyproject.toml`` from the source tree. The CI docs build runs in
# a python:3.13-slim container with only Sphinx + extensions
# installed (we don't build the full C++ stack just to render docs),
# so importlib.metadata.version("vibe-qc") will fail and the
# pyproject.toml fallback is what's actually used in production.
def _read_release() -> str:
    try:
        from importlib.metadata import PackageNotFoundError
        from importlib.metadata import version as _pkg_version

        try:
            return _pkg_version("vibe-qc")
        except PackageNotFoundError:
            try:
                # Pre-rename distribution name; kept for local builds
                # that predate the 0.2 metadata change.
                return _pkg_version("vibeqc")
            except PackageNotFoundError:
                pass
    except ImportError:
        pass
    # Fall back to parsing pyproject.toml directly from the source
    # tree (works in the CI container where vibe-qc isn't installed).
    try:
        import tomllib

        with open(_REPO_ROOT / "pyproject.toml", "rb") as f:
            return tomllib.load(f)["project"]["version"]
    except Exception:
        return "0.0.1"


release = _read_release()
version = ".".join(release.split(".")[:2])

# ``is_dev`` is True when the version string contains ``.dev``, i.e. we are
# building from the ``main`` branch.  Used by ``sphinx.ext.ifconfig`` to
# show/hide the Experimental toctree section; on the ``release`` branch the
# version is a plain tag like ``0.14.0`` and the section is hidden.
is_dev = ".dev" in release


# --- Extensions ------------------------------------------------------------

extensions = [
    # Markdown with roles and directives
    "myst_parser",
    # Autogenerate API reference from docstrings
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",  # NumPy / Google style docstrings
    # Cross-link to Python + NumPy docs
    "sphinx.ext.intersphinx",
    # In-page rendering of LaTeX
    "sphinx.ext.mathjax",
    # Add [source] links next to autogenerated class/function headings
    "sphinx.ext.viewcode",
    # Copy-button on fenced code blocks
    "sphinx_copybutton",
    # Grid cards / dropdowns / tabs (used on the support page)
    "sphinx_design",
    # Local extension — renders citations from the bundled database
    # so docs/citing.md + functionals.md § Citations stay in lockstep
    # with database.toml (no drift; AGENTS.md rule 8 is enforced via
    # CI test_citations.py).
    "vibeqc_cite",
    # Emit redirect stubs for renamed/moved pages so old URLs keep working.
    # The ``redirects`` map lives just below; keep it in sync on every rename.
    "sphinx_reredirects",
    # Conditional content — used to show/hide the Experimental section
    # based on whether this is a dev build (``main`` branch) or a
    # release build (``release`` branch).
    "sphinx.ext.ifconfig",
]

# Also look for .md (MyST) files, not just .rst.
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# --- Redirects (sphinx_reredirects) ----------------------------------------
# When a page is renamed or moved, add its OLD source path here so the old
# published URL keeps resolving: sphinx_reredirects writes a tiny meta-refresh
# stub at the old location pointing at the new one. Targets are relative to the
# old page's directory. The tutorial pages were renamed from numbered prefixes
# (``NN_name``) to descriptive names; these entries keep the historical
# ``/tutorial/NN_name.html`` URLs (papers, bookmarks, old links) alive.
redirects = {
    # experimental.md was moved to experimental/index.md when the
    # Experimental section got its own nav landing page.
    "experimental": "experimental/index.html",
    "tutorial/01_molecular_hf": "molecular_hf.html",
    "tutorial/02_molecular_dft": "molecular_dft.html",
    "tutorial/03_open_shell": "open_shell.html",
    "tutorial/04_periodic_hf": "periodic_hf.html",
    "tutorial/05_periodic_dft": "periodic_dft.html",
    "tutorial/06_madelung_with_ewald": "madelung_with_ewald.html",
    "tutorial/07_post_scf_properties": "post_scf_properties.html",
    "tutorial/08_geometry_optimization": "geometry_optimization.html",
    "tutorial/09_vibrational_frequencies": "vibrational_frequencies.html",
    "tutorial/10_thermodynamics": "thermodynamics.html",
    "tutorial/11_orbital_visualization": "orbital_visualization.html",
    "tutorial/12_band_structure": "band_structure.html",
    "tutorial/13_basis_convergence": "basis_convergence.html",
    "tutorial/14_dispersion": "dispersion.html",
    "tutorial/15_functional_comparison": "functional_comparison.html",
    "tutorial/16_pob_tzvp": "pob_tzvp.html",
    "tutorial/17_peierls": "peierls.html",
    "tutorial/18_parallel_execution": "parallel_execution.html",
    "tutorial/19_neb_reaction_path": "neb_reaction_path.html",
    "tutorial/20_natural_orbitals": "natural_orbitals.html",
    "tutorial/21_pdos": "pdos.html",
    "tutorial/22_periodic_orbital_cubes": "periodic_orbital_cubes.html",
    "tutorial/23_tight_cell_dft": "tight_cell_dft.html",
    "tutorial/24_periodic_scf_convergence": "periodic_scf_convergence.html",
    "tutorial/25_symmetry_storage": "symmetry_storage.html",
    "tutorial/26_cross_validation": "cross_validation.html",
    "tutorial/27_moltui_terminal_viewer": "moltui_terminal_viewer.html",
    "tutorial/28_lih_pob_tzvp_solid_state": "lih_pob_tzvp_solid_state.html",
    "tutorial/29_reference_outputs": "reference_outputs.html",
    "tutorial/30_external_data_fetcher": "external_data_fetcher.html",
    "tutorial/30_h8_chain_ccm_ancestor": "h8_chain_ccm_ancestor.html",
    "tutorial/31_rijcosx_glycine": "rijcosx_glycine.html",
    "tutorial/32_pt_cluster_lanl2dz": "pt_cluster_lanl2dz.html",
    "tutorial/33_mgo_from_materials_project": "mgo_from_materials_project.html",
    "tutorial/34_lih_multi_k": "lih_multi_k.html",
    "tutorial/35_open_shell_mg_cation": "open_shell_mg_cation.html",
    "tutorial/36_initial_guess_walkthrough": "initial_guess_walkthrough.html",
    "tutorial/37_double_hybrid_b2plyp": "double_hybrid_b2plyp.html",
    "tutorial/38_ri_mp2_aux_verification": "ri_mp2_aux_verification.html",
    "tutorial/39_solvation_water": "solvation_water.html",
    "tutorial/40_auto_citations": "auto_citations.html",
    "tutorial/41_ediis_diis_hybrid": "ediis_diis_hybrid.html",
    "tutorial/42_fermi_dirac_smearing": "fermi_dirac_smearing.html",
    "tutorial/43_xsf_bxsf_visualization": "xsf_bxsf_visualization.html",
    "tutorial/44_range_separated_wb97x": "range_separated_wb97x.html",
    "tutorial/45_vibe_view_walkthrough": "vibe_view_walkthrough.html",
    "tutorial/46_semiempirical_dftb": "semiempirical_dftb.html",
    "tutorial/47_qvf_file_format": "qvf_file_format.html",
    "tutorial/48_vq_queue_remote_job": "vq_queue_remote_job.html",
    "tutorial/49_mace_mlip": "mace_mlip.html",
    "tutorial/50_msindo": "msindo.html",
    "tutorial/51_dlpno_local_correlation": "dlpno_local_correlation.html",
    "tutorial/52_kpoints_brillouin_bloch": "kpoints_brillouin_bloch.html",
}

# Let MyST handle these optional features. All of them pay for themselves
# for a scientific-documentation project.
myst_enable_extensions = [
    "amsmath",  # $$...$$ LaTeX blocks
    "deflist",  # term / definition lists
    "colon_fence",  # ``` ::: ``` fenced admonitions
    "linkify",  # auto-link bare URLs
    "substitution",
    "tasklist",
    "dollarmath",  # $inline$ and $$display$$ math
]
myst_heading_anchors = 3  # auto-generate anchors up to h3


# Make the package version + release codename available as
# ``{{release}}`` / ``{{version}}`` / ``{{codename}}`` substitutions in
# markdown pages. The codename catalogue (RELEASE_CODENAMES) is
# canonical in ``vibeqc.banner`` so the runtime banner and the docs
# site share one source of truth — when a new release codename is
# assigned, only ``python/vibeqc/banner.py`` needs the edit.
# Load python/vibeqc/banner.py as a standalone module, bypassing
# vibeqc/__init__.py — we only need RELEASE_CODENAMES + the lookup
# helper, and importing the full ``vibeqc`` package requires the
# compiled C++ extension that the CI docs build doesn't have. This
# also keeps banner.py as the single source of truth for the
# codename catalogue (the runtime banner reads the same dict).
def _load_banner_module():
    import importlib.util

    banner_path = _REPO_ROOT / "python" / "vibeqc" / "banner.py"
    if not banner_path.is_file():
        return None
    spec = importlib.util.spec_from_file_location(
        "_vqc_banner_for_docs",
        banner_path,
    )
    if spec is None or spec.loader is None:
        return None
    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except Exception:
        return None
    return mod


_banner = _load_banner_module()
if _banner is not None:
    RELEASE_CODENAMES = getattr(_banner, "RELEASE_CODENAMES", {})
    _codename_lookup = getattr(_banner, "codename_for_version", lambda rel: None)
else:
    RELEASE_CODENAMES = {}

    def _codename_lookup(rel):  # type: ignore[no-redef]
        return None


codename = _codename_lookup(release) or "(unnamed)"


# Only vibe-basis remains in this checkout. External companion release
# pages are linked from the docs instead of guessing their versions.
_SIBLING_PYPROJECTS = {
    "vibebasis_version": "vibe-basis/pyproject.toml",
}


def _read_sibling_version(relative_path: str) -> str:
    try:
        import tomllib

        with open(_REPO_ROOT / relative_path, "rb") as f:
            return tomllib.load(f)["project"]["version"]
    except Exception:
        # Match _read_release's posture: a missing sibling must not fail the
        # docs build. The placeholder is visible rather than silently wrong.
        return "(unknown)"


_sibling_versions = {
    name: _read_sibling_version(path) for name, path in _SIBLING_PYPROJECTS.items()
}

myst_substitutions = {
    "release": release,
    "version": version,
    "codename": codename,
    **_sibling_versions,
}

autosummary_generate = True  # build api/*.rst stubs on demand
autodoc_default_options = {
    "members": True,
    "undoc-members": False,
    "show-inheritance": True,
}
autodoc_member_order = "bysource"
autodoc_typehints = "description"  # render type hints in the descr., not sig

napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    # ASE migrated from wiki.fysik.dtu.dk to ase-lib.org and no
    # longer publishes a Sphinx objects.inv.  ASE cross-references
    # in docstrings will render as plain text.
}


# --- HTML output -----------------------------------------------------------

html_theme = "furo"
# The publication script removes _sources; keep the public source footer link, but
# do not offer per-page source downloads whose targets are not deployed.
html_show_sourcelink = False
html_title = "vibe-qc documentation"
html_static_path = ["_static"]
html_css_files = ["custom.css"]  # brand overrides (see _static/custom.css)

# Canonical URL for the docs site. Used by sphinx to write a
# <link rel="canonical"> tag and is also picked up by search engines
# when indexing the site.
#
# The docs live under the ``/docs/`` subpath: the domain root
# (https://vibe-qc.com/) is served by the separate Astro marketing site
# (see ../website/), which links *into* these docs. Keep this in lockstep
# with the ``docs-deploy`` rsync target and ``CANONICAL`` in
# .gitlab-ci.yml, and with the root ``.htaccess`` legacy-URL redirects
# (deploy/htaccess-redirects.conf).
html_baseurl = "https://vibe-qc.com/docs/"

# --- Logo / favicon --------------------------------------------------------
#
# Assets live under ``docs/_static/logo/``. See
# ``docs/_static/README.md`` for the full inventory and naming scheme.
#
# Furo resolves ``light_logo`` / ``dark_logo`` in ``html_theme_options``
# below; we only need ``html_favicon`` explicitly here.
html_favicon = "_static/logo/vibe-qc-favicon.svg"

# Furo accepts both light and dark theme customisation. Keep the
# palette stock until the brand spec lands; drop hex codes into
# ``_static/custom.css`` at that point.
html_theme_options = {
    # Furo's "View source" link only recognises GitHub / GitLab.com /
    # BitBucket URL shapes, not self-hosted GitLab instances. Leave the
    # auto-detection unset; add a footer link manually once we publish
    # under vibe-qc.com.
    "footer_icons": [
        {
            "name": "GitHub",
            "url": "https://github.com/vibe-qc/vibe-qc",
            "html": "",
            "class": "fa-brands fa-solid fa-github fa-2x",
        },
    ],
    # Logo already contains the name; don't print it again in the sidebar.
    "sidebar_hide_name": True,
    # Furo picks a light or dark logo based on the user's theme.
    # Paths are relative to ``html_static_path[0]``, which is "_static".
    "light_logo": "logo/vibe-qc-wordmark-light.svg",
    "dark_logo": "logo/vibe-qc-wordmark-dark.svg",
    "navigation_with_keys": True,
    # Furo's ``source_repository`` feature only parses
    # ``github.com`` / ``gitlab.com`` / ``bitbucket.org`` — self-hosted
    # GitLab URLs are rejected. Keeping this commented out until Furo
    # adds a manual-URL override, or we add a custom footer link.
    # "source_repository": "https://github.com/vibe-qc/vibe-qc",
    # "source_branch": "main",
    # "source_directory": "docs/",
}


# --- Other ----------------------------------------------------------------

# Don't swallow broken references — they're bugs we want to catch.
nitpicky = False  # set True once the API reference is fully populated

# Files / directories to exclude from the build.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "AGENTS.md",
    "CLAUDE.md",
]

# Suppress the specific warnings that mean nothing in our setup.
suppress_warnings = [
    "myst.header",  # lets us start some pages at h2 without an h1
    "autodoc.mocked_object",  # vibeqc._vibeqc_core is INTENTIONALLY mocked
    # at autosummary time (see autodoc_mock_imports
    # in scripts/build_site.sh). Without this
    # suppression Sphinx 9.x emits ~80 warnings on
    # every build — pure noise that drowns out
    # real warnings if any appear.
    # The mock is also why python/vibeqc/__init__.py skips the
    # import-time SKALA registration when the core carries
    # ``__sphinx_mock__`` (#559): a mocked registry query returns
    # a stand-in, which the strict adoption check reads as a
    # collision, and the whole package fails to import.
    # Inline literal / substitution start-string-without-end-string
    # warnings come from Python docstrings that use ``<``, ``>``, or
    # ``|`` characters MyST interprets as markup.  These need fixing
    # in the Python source; suppressing here keeps the build clean.
    "docutils",
    # Autosummary-generated API stub pages are intentionally not
    # listed in any toctree (they are linked from the module page).
    "toc.not_included",
]

# Map non-standard Pygments lexer names used in fenced code blocks to
# built-in ones.  ``jsonc`` (JSON with comments) is not in Pygments;
# fall back to ``json`` which highlights nearly identically.
_pygments_fallback_lexers = {
    "jsonc": "json",
    # No SSH-specific lexer in Pygments; ``ini`` highlights
    # key-value config files acceptably.
    "ssh-config": "ini",
}

def _on_missing_reference(app, env, node, contnode):
    """Suppress unfixable autodoc cross-reference warnings.

    Autodoc generates ``:py:class:`` / ``:py:func:`` roles for every type
    annotation and docstring identifier it encounters.  Many of these
    cannot resolve because:

    * NumPy type aliases (``numpy.float64``, ``numpy.typing.NDArray``)
      are ``TypeAlias`` objects, not classes — they are absent from
      NumPy's intersphinx inventory.
    * ``pybind11_builtins.pybind11_object`` is a pybind11 internal that
      has no documentation inventory.
    * Docstring prose fragments (``Internal``, ``Optional``, ``SPINLOCK``,
      ``READ``, ``ATOMSPIN``, raw dimension numbers like ``3``) are falsely
      parsed as cross-reference targets.
    * Private ``vibeqc._vibeqc_core.*`` types are C++ pybind11 bindings
      whose docstrings the Python-domain resolver cannot navigate.

    Returning the continuation node tells Sphinx to use it as-is
    (plain text, no hyperlink) and **skip the warning**.
    """
    target = node.get("reftarget", "")

    # --- pybind11 internal class ---
    if "pybind11_builtins" in target:
        return contnode

    # --- NumPy type aliases (TypeAlias, not in intersphinx) ---
    if target in ("numpy.float64", "numpy.complex128"):
        return contnode
    if target.startswith("numpy.typing."):
        return contnode

    # --- pybind11-generated C++ bindings under vibeqc._vibeqc_core ---
    if target.startswith("vibeqc._vibeqc_core."):
        return contnode

    # --- Internal / experimental modules (prefix-based) ---
    # These are private Python modules or experimental-dev branches
    # whose types autodoc can't cross-reference.
    if target.startswith("vibeqc.pbc_bipole_common."):
        return contnode
    if target.startswith("vibeqc.periodic.chi."):
        return contnode
    if target.startswith("vibeqc.solvers._"):
        return contnode
    if target.startswith("vibeqc.output.formats.perf."):
        return contnode
    if target.startswith("vibeqc.solvation.cavity."):
        return contnode
    if target.startswith("vibeqc.periodic_k_gdf."):
        return contnode
    if target.startswith("vibeqc.pbc_bipole."):
        return contnode
    if target.startswith("vibeqc.neb."):
        return contnode
    if target.startswith("vibeqc.gcp."):
        return contnode

    # --- vibeqc member references (vibeqc.Module.Class.attr) ---
    # Autosummary generates ``:py:obj:`` roles for every class member.
    # When the C++ extension isn't fully importable during docs builds,
    # these cross-page member references can't resolve.  Suppress them
    # all — they represent real API members that would resolve with a
    # complete build environment.
    if target.startswith("vibeqc.") and target.count(".") >= 2:
        return contnode

    # --- vibeqc module-level references ---
    # ``vibeqc.scf_log``, ``vibeqc.dft_plus_u`` etc. are internal
    # modules that autodoc references but can't cross-reference.
    domain = node.get("refdomain", "")
    reftype = node.get("reftype", "")
    if target.startswith("vibeqc.") and domain == "py" and reftype == "mod":
        return contnode

    # --- Targets containing spaces = docstring prose artefacts ---
    # Real Python identifiers never contain spaces.  These are English
    # sentences that autodoc mistakenly promoted to cross-references.
    if " " in target:
        return contnode

    # --- Bare function names (no module qualifier) ---
    # Autodoc generates unqualified ``:py:func:`` roles for internal
    # helpers mentioned in docstrings.  These never resolve.
    if "." not in target and target not in ("True", "False", "None"):
        domain = node.get("refdomain", "")
        reftype = node.get("reftype", "")
        if domain == "py" and reftype in ("func", "obj"):
            return contnode

    # --- Prose fragments mistakenly parsed as cross-references ---
    # If the target is very long (>60 chars) or contains words that
    # look like English prose, it's not a real identifier.
    if len(target) > 60:
        return contnode

    # --- pybind11_detail (C++ binding internals) ---
    if "pybind11_detail" in target:
        return contnode

    # --- Unqualified short names from docstring prose ---
    # When autodoc encounters a bare class name in a docstring (e.g.
    # "Returns a HubbardSite"), it may generate a ``:py:class:`` role
    # without a module qualifier.  These never resolve and are noise.
    _UNQUALIFIED_PROSE = frozenset(
        {
            "HubbardSite",
            "KPoints",
            "D3BJParams",
            "PerfTracker",
            "BasisSet",
            "Molecule",
            "SolventModel",
            "HessianResult",
            "SpinDet",
            "Crystal",
            "Hamiltonian",
            "StructuredLog",
            "BlochKMesh",
            "BandStructure",
            "PeriodicJKMethod",
            "LevelShiftSchedule",
            "OrbitReducedLatticeMatrix",
            "SmearingResolution",
            "n_ao",
            "n_mo",
            "ndet",
            "n_pts",
            "default True",
            'default ""',
            "default None",
            "optional",
            "True for a range-separated",
            "Human-readable triples selector",
            "Diagnostic",
            "Spin-component-scaled correlation energy",
            "Lebedev algebraic order. Bundled tiers",
            "GAPWExperimentalWarning",
            "D4NativeExperimentalWarning",
            "GCPDataMissing",
            "PeriodicSCFAccelerator",
            "transcorrelated_options / casci_options / caspt2_options",
        }
    )
    if target in _UNQUALIFIED_PROSE:
        return contnode

    # Multi-word prose fragments with a specific prefix.
    if target.startswith(("HubbardSite", "KPoints", "D3BJParams", "PerfTracker")):
        return contnode

    # --- Docstring-prose false positives ---
    # These are English words / internal jargon that autodoc's parser
    # mistakenly promotes to ``:py:class:`` roles.
    _PROSE_ARTIFACTS = frozenset(
        {
            "Internal",
            "Optional",
            "READ",
            "SPINLOCK",
            "ATOMSPIN",
            "Hartree",
            "True",
            "False",
            "None",
            "optional",
            "ndarray",
            "np.ndarray",
            "Path",
            "Molecule",
            "3",
        }
    )
    if target in _PROSE_ARTIFACTS:
        return contnode

    # Multi-word prose fragments that got joined into a single target.
    if target.startswith("SPINLOCK "):
        return contnode
    if target.startswith("open-shell "):
        return contnode
    if target.startswith("READ "):
        return contnode

    # --- Quoted targets (autodoc parsing artefacts) ---
    if target.startswith("'") and target.endswith("'"):
        return contnode

    return None


def _install_duplicate_desc_filter():
    """Add a logging filter that silences known-unfixable Sphinx warnings.

    These come from autosummary artefacts, included root-file
    cross-references, and toctree orphans that are intentional.
    """
    import logging

    sphinx_logger = logging.getLogger("sphinx")

    class _SuppressKnownNoise(logging.Filter):
        def filter(self, record):
            msg = record.getMessage()
            # Duplicate member docs from autosummary (class + module pages).
            if "duplicate object description" in msg:
                return False
            # Autosummary stubs intentionally not in toctrees.
            if "document isn't included in any toctree" in msg:
                return False
            # Root-file cross-refs that resolve relative to repo root
            # (not docs/) when included via MyST {include}.  The stub
            # pages at docs/{CONTRIBUTING,CHANGELOG}.md exist but the
            # included content resolves against the wrong base.
            if "Unknown source document 'CONTRIBUTING'" in msg:
                return False
            if "Unknown source document 'CHANGELOG'" in msg:
                return False
            if "Unknown source document 'CLAUDE'" in msg:
                return False
            if "Unknown source document 'AGENTS'" in msg:
                return False
            # myst.xref_missing for known-broken anchors in deleted docs.
            _KNOWN_MISSING_XREFS = [
                "'docs/license.md'",
            ]
            for xref in _KNOWN_MISSING_XREFS:
                if xref in msg:
                    return False
            return True

    sphinx_logger.addFilter(_SuppressKnownNoise())


def _pinned_qvf_link(source: str, target: str) -> str | None:
    """Adapt known upstream-relative links without altering the pinned pages."""
    source_path = Path(source)
    if source_path.parent != _REPO_ROOT / "docs" / "qvf" / "_vendored":
        return None
    targets = {
        ("GOVERNANCE.md", "conformance/README.md"): "/qvf/conformance",
        ("GOVERNANCE.md", "docs/integration_guide.md"): "/qvf/integration_guide",
        ("integration_guide.md", "../conformance/README.md"): "/qvf/conformance",
        ("library_guide.md", "../cpp/include/qvf/qvf_c.h"): (
            "https://github.com/vibe-qc/qvf/blob/"
            "7660640ce609a1fd3ba03db4dd53df01b798e619/cpp/include/qvf/qvf_c.h"
        ),
    }
    return targets.get((source_path.name, target))


def _resolve_pinned_qvf_links(app, doctree):
    """Keep snapshot links working in both included and standalone pages."""
    from docutils import nodes
    from sphinx import addnodes

    for node in doctree.findall(addnodes.pending_xref):
        target = _pinned_qvf_link(node.source or "", node.get("reftarget", ""))
        if target is None:
            continue
        if target.startswith("https:"):
            node.replace_self(
                nodes.reference("", "", *node.children, refuri=target, internal=False)
            )
        else:
            node["refdomain"] = "std"
            node["reftype"] = "doc"
            node["reftarget"] = target


def setup(app):
    """Register config values + Pygments lexer aliases + warning filter."""
    app.add_config_value("is_dev", is_dev, "env")

    # Adapt only the known upstream paths; every unrelated unresolved link
    # still reaches the standard Sphinx/MyST warning path.
    app.connect("doctree-read", _resolve_pinned_qvf_links)

    # Suppress unfixable autodoc noise — see ``_on_missing_reference``.
    app.connect("missing-reference", _on_missing_reference)

    # Suppress "duplicate object description" warnings.  These come
    # from autosummary generating both a class-level page and a
    # module-level listing that document the same members.
    _install_duplicate_desc_filter()

    # Register fallback Pygments lexer aliases so that fenced code
    # blocks tagged ``jsonc`` / ``ssh-config`` don't produce warnings.
    # We do this inside ``setup()`` because ``_pygments_fallback_lexers``
    # must be defined before the Sphinx builder creates the
    # PygmentsBridge (which happens after ``conf.py`` is imported but
    # before events fire).  ``app.add_lexer`` registers the alias on
    # the existing lexer class without overwriting anything.
    from pygments.lexers import get_lexer_by_name

    for alias, fallback in _pygments_fallback_lexers.items():
        lexer_cls = get_lexer_by_name(fallback).__class__
        app.add_lexer(alias, lexer_cls)
