"""Periodic RIJCOSX SCF driver for Γ-only RHF.

M3: Periodic-correct GDF J (compcell/RSGDF Lpq) + periodic COSX K.
M3a: COSX K sums exchange over the truncated image-cell list -- the
home-bra -> image-ket 1/R exchange class (measured on the H-chain
anchor: ||K|| 1.74 -> 3.94 at D = I).  This is exact for vacuum-padded
cells and a first-order image correction for tight cells; it is NOT
yet the Γ-folded GDF exchange (||K_GDF|| = 16.16 on the same anchor),
which additionally contains the long-range classes generated by the
Γ-only density coupling all cell pairs.  See handovers/HANDOVER_RIJCOSX_M3A.md
Sec. "M3a measured outcome".

Architecture (tight-cell path, default for dim=3 with compact cells):
  1. One-electron integrals: Ewald-3D gauge for 3D, bare lattice sum
     for dim < 3, Γ-folded.
  2. Lpq tensor: built once via ``build_lpq_compcell`` (Sun 2017
     compensated charges + AFT correction). Alternative:
     ``build_lpq_native_fft`` (all-FT Bloch pair-FT) via
     ``gdf_method='rsgdf'``.
  3. JKBuilder: C++ ``PeriodicTightCellCOSXJKBuilder``
     - build_J(D): GDF contraction from Lpq (periodic-correct)
     - build_K(D): periodic COSX on Becke grid, exchange summed over
       image cells within ``lattice_opts.cutoff_bohr`` (M3a;
       single-lattice-sum model -- see module docstring caveat)
     - No exxdiv='ewald' Madelung K-shift (COSX-K is a real-space
       direct-truncated sum)
  4. SCF loop: delegates to ``run_rhf_scf_with_jk`` (production C++
     engine).

Molecular-limit path (vacuum-padded cells, large box):
  Uses ``PeriodicGammaCOSXJKBuilder`` (molecular DensityFitting J +
  home-cell COSX K).  This is the M2 path -- faster setup, correct when
  image-cell AO overlap is negligible.  Every electrostatic term of
  this path is evaluated over the home cell alone: the molecular DF J
  carries no image electrons, so V_ne and E_nuc carry no image nuclei
  and the COSX K carries no image-ket exchange class (see
  ``_home_cell_electrostatics_lat_opts``).  Before #707 the three
  one-electron / exchange terms kept their own image truncations
  (``nuclear_cutoff_bohr`` for V_ne and E_nuc, ``cutoff_bohr`` for K)
  while J had none, and every box shorter than those cutoffs was
  over-bound by the uncompensated bare monopole sums (H atom / STO-3G,
  12-bohr box: -1.6377 Ha instead of -0.4666 Ha).

Reference: handovers/HANDOVER_RIJCOSX_M3A.md (M3a milestone; M3 history in
handovers/HANDOVER_RIJCOSX_PBC.md).
"""

from __future__ import annotations

import os
import warnings
from types import SimpleNamespace
from typing import Optional, Union

import numpy as np

from . import BasisSet, PeriodicRHFOptions, PeriodicSystem, RHFOptions, RHFResult
from ._vibeqc_core import (
    CoulombMethod,
    InitialGuess,
    LatticeSumOptions,
    compute_kinetic_lattice,
    compute_overlap_lattice,
    make_periodic_gamma_cosx_jk_builder,
    make_periodic_tight_cosx_jk_builder,
    nuclear_repulsion_per_cell,
    run_rhf_scf_with_jk,
)
from .aux_basis import (
    build_lpq_compcell,
    build_lpq_native_fft,
    default_aux_for,
    make_aux_basis_set,
    make_modrho_aux_basis,
)
from .pbc_gdf import _gauge_lat_opts_ewald_3d
from .guess import (
    _coerce_periodic_driver_guess,
    initial_densities_open_shell,
    initial_density_closed_shell,
)
from .periodic_gradient import _fold_gamma_real
from .periodic_v_ne import compute_nuclear_lattice_dispatch
from .progress import ProgressLogger, resolve_progress

__all__ = [
    "run_periodic_rijcosx_rhf",
    "run_periodic_rijcosx_rks",
    "run_periodic_rijcosx_uhf",
    "run_periodic_rijcosx_uks",
]


# ---------------------------------------------------------------------------
# Auxiliary basis resolution
# ---------------------------------------------------------------------------


def _resolve_aux_basis(mol, basis: BasisSet, aux_basis: Optional[str]) -> BasisSet:
    """Return an auxiliary basis for the RI-J piece."""
    aux_name = aux_basis or default_aux_for(basis.name)
    aux = make_aux_basis_set(mol, aux_name=aux_name)
    if aux is None:
        raise ValueError(
            f"periodic_rijcosx: no auxiliary basis found for "
            f"{basis.name!r} (tried aux={aux_name!r}). "
            f"Set ri_j_aux_basis explicitly or add a default in "
            f"aux_basis.py:default_aux_for()."
        )
    return aux


# ---------------------------------------------------------------------------
# Tight-cell detection
# ---------------------------------------------------------------------------


def _is_tight_cell(system: PeriodicSystem) -> bool:
    """Return True if the cell is tight enough that image-cell AO overlap
    is non-negligible -- i.e., the molecular DensityFitting J is
    inaccurate.  Heuristic from pbc_gdf.py: Z>1 + cell_vol < 500 bohr^3.
    """
    if int(system.dim) != 3:
        return False
    z_max = max(atom.Z for atom in system.unit_cell)
    if z_max <= 1:
        return False  # pure hydrogen -- compcell handles it, but molecular DF is fine
    cell_vol = float(abs(np.linalg.det(np.asarray(system.lattice))))
    return cell_vol < 500.0


def _clone_lat_opts(src: LatticeSumOptions, **overrides) -> LatticeSumOptions:
    """Return a field-wise copy of ``src`` with ``overrides`` applied."""
    dst = LatticeSumOptions()
    for attr in dir(src):
        if attr.startswith("_"):
            continue
        try:
            value = getattr(src, attr)
        except Exception:
            continue
        if callable(value):
            continue
        try:
            setattr(dst, attr, value)
        except Exception:
            pass
    for attr, value in overrides.items():
        setattr(dst, attr, value)
    return dst


def _home_cell_electrostatics_lat_opts(
    src: LatticeSumOptions,
) -> tuple[LatticeSumOptions, LatticeSumOptions]:
    """Lattice options for the molecular-limit (vacuum-padded) J/K model.

    The molecular-limit RIJCOSX path builds J with the *molecular*
    density-fitting builder, i.e. from the home-cell electrons only.
    In periodic boundary conditions only the total electrostatic
    energy of a neutral cell is well defined; its nuclear-nuclear,
    electron-nuclear and electron-electron image sums individually
    diverge (or, truncated, are O(sum_g 1/|g|)) and cancel only when
    they are evaluated over the same set of image cells (Makov & Payne,
    Phys. Rev. B 51, 4014 (1995), Sec. II; the neutral localized
    system's residual after that cancellation is the multipole tail,
    O(L^-3) and below). Dropping the image electrons alone therefore
    leaves the bare monopole sums -0.5 sum_g sum_AB Z_A Z_B / |R_AB + g|
    in the one-electron terms, and the image-ket exchange class
    sum_g (mu lambda | nu_g sigma_g) -- for a Gamma Bloch orbital the
    electron's Coulomb interaction with its own images, which pairs
    with the image part of J -- in K. Both were present before #707.

    Returns ``(one_electron_opts, exchange_opts)``:

    * ``one_electron_opts`` restricts the nuclear-attraction and
      nuclear-repulsion lattice sums to the home-cell nuclei
      (``nuclear_cutoff_bohr = 0`` selects exactly the zero cell) while
      keeping the ket-image overlap classes of V_ne consistent with the
      S and T lattice sums;
    * ``exchange_opts`` restricts the COSX K image-cell list to the
      home cell (``cutoff_bohr = 0``).

    Within the envelope (every active length >= 12 bohr, no tight
    cell) the neglected image terms are the same neutral-cell multipole
    tail the molecular DF J already neglects, so the path reproduces
    the molecular RIJCOSX oracle independently of the box length and of
    the user's lattice cutoffs (regression:
    ``test_rijcosx_gamma_vacuum_padded_home_cell_electrostatics``).
    """
    one_electron = _clone_lat_opts(src, nuclear_cutoff_bohr=0.0)
    exchange = _clone_lat_opts(src, cutoff_bohr=0.0)
    return one_electron, exchange


from .guess import periodic_guess_capabilities

_RIJCOSX_GUESSES = periodic_guess_capabilities("rijcosx")


def _rijcosx_guess(opts, *, driver):
    """Compatibility selector query using the same explicit capability set."""
    return _coerce_periodic_driver_guess(
        getattr(opts, "initial_guess", InitialGuess.AUTO),
        driver=driver, supported=_RIJCOSX_GUESSES,
    )


def _rijcosx_selection(system, opts, *, driver, open_shell):
    from .guess import select_initial_guess
    from .pbc_gdf import _refuse_ecp_options

    _refuse_ecp_options(opts, driver, system=system)

    from .guess import coerce_initial_guess
    requested = coerce_initial_guess(getattr(opts, "initial_guess", InitialGuess.AUTO))
    if requested == InitialGuess.READ and not getattr(opts, "read_path", ""):
        names = ("read_density_alpha", "read_density_beta") if open_shell else ("read_density",)
        if not all(np.asarray(getattr(opts, name, [])).size for name in names):
            raise ValueError(f"{driver}: READ requires a complete density payload or read_path")
    return select_initial_guess(
        system.unit_cell_molecule(), requested,
        is_periodic=True, is_open_shell=open_shell,
        supported=_RIJCOSX_GUESSES,
        atomic_spins=getattr(opts, "atomic_spins", None), driver=driver,
    )


def _initial_density_closed(system, basis, n_occ, guess, lat_opts, overlap, options=None):
    """Build a shared-framework Gamma density for a RIJCOSX route."""
    if guess == InitialGuess.PATOM:
        # The native preparation seam has the actual Gamma S/Hcore/JK.
        return np.empty((0, 0))
    density = initial_density_closed_shell(
        system.unit_cell_molecule(),
        basis,
        int(n_occ),
        guess,
        is_periodic=True,
        periodic_system=system,
        lattice_opts=lat_opts,
        overlap=overlap,
        read_density=getattr(options, "read_density", None),
        read_path=getattr(options, "read_path", ""),
    )
    # The C++ JK-loop APIs use an empty matrix to request their established
    # Hcore diagonalisation. Every other supported kind produces a density.
    return np.empty((0, 0)) if density is None else density


def _initial_densities_open(
    system, basis, n_alpha, n_beta, guess, lat_opts, overlap, atomic_spins=None, options=None
):
    """Build shared-framework Gamma spin densities for RIJCOSX."""
    if guess == InitialGuess.PATOM:
        return np.empty((0, 0)), np.empty((0, 0))
    densities = initial_densities_open_shell(
        system.unit_cell_molecule(),
        basis,
        int(n_alpha),
        int(n_beta),
        guess,
        is_periodic=True,
        periodic_system=system,
        lattice_opts=lat_opts,
        overlap=overlap,
        atomic_spins=atomic_spins,
        read_density_alpha=getattr(options, "read_density_alpha", None),
        read_density_beta=getattr(options, "read_density_beta", None),
        read_path=getattr(options, "read_path", ""),
    )
    if densities is None:
        empty = np.empty((0, 0))
        return empty, empty.copy()
    return densities


def _validate_atomic_spins(opts, guess):
    """Keep ATOMSPIN coupled to the resolved SAD seed."""
    if getattr(opts, "atomic_spins", None) and guess != InitialGuess.SAD:
        raise RuntimeError(
            "GuessEngine: atomic_spins (ATOMSPIN broken-symmetry seed) "
            f"requires the SAD guess; resolved guess is {guess.name}"
        )


# ---------------------------------------------------------------------------
# Main driver
# ---------------------------------------------------------------------------


def run_periodic_rijcosx_rhf(
    system: PeriodicSystem,
    basis: BasisSet,
    options: Optional[PeriodicRHFOptions] = None,
    *,
    aux_basis: Optional[str] = None,
    gdf_method: str = "compcell",
    compcell_eta: float = 1.0,
    apply_aft_correction: bool = True,
    aft_precision: float = 1e-10,
    aft_ft_convention: str = "libint",
    rcut_strategy: Optional[object] = "pyscf_auto",
    rcut_precision: float = 1e-8,
    gdf_linear_dep_threshold: float = 1e-9,
    rsgdf_ke_cutoff: float = 200.0,
    tight_cell: Optional[bool] = None,
    progress: Union[bool, ProgressLogger, None] = None,
) -> RHFResult:
    """Γ-only periodic RHF via RIJCOSX.

    J: GDF (compcell or RSGDF for tight cells; molecular DF for
       vacuum-padded cells).
    K: periodic COSX on a Becke grid, exchange summed over image
       cells within ``options.lattice_opts.cutoff_bohr`` (M3a).

    Parameters
    ----------
    system
        PeriodicSystem with unit cell + lattice.
    basis
        Orbital (primary) basis set.
    options
        PeriodicRHFOptions. If None, defaults are used.
    aux_basis
        Auxiliary basis name for DF-J. Defaults to
        ``default_aux_for(basis.name)``.
    gdf_method
        Lpq builder for the tight-cell path: ``'compcell'`` (default)
        or ``'rsgdf'`` (all-FT Bloch pair-FT).  Ignored when
        ``tight_cell=False``.
    compcell_eta
        Smooth-Gaussian exponent for the compcell compensating basis.
        Default 1.0.  With AFT on, the answer is η-independent.
    apply_aft_correction
        Apply the analytical-Fourier-transform long-range correction
        (default True).  Makes the compcell answer η-independent.
    aft_precision
        G-mesh precision target for the AFT correction (default 1e-10).
    aft_ft_convention
        FT convention: ``'libint'`` (default, vibe-qc native) or
        ``'libcint'`` (PySCF match).
    rcut_strategy
        Lattice cutoff strategy for the compcell construction
        (default ``'pyscf_auto'``).
    rcut_precision
        Precision target for the per-basis cutoff (default 1e-8).
    gdf_linear_dep_threshold
        Aux metric eigenvalue floor for the GDF fit (default 1e-9).
    rsgdf_ke_cutoff
        Kinetic-energy cutoff (Ha) for the RSGDF dense FFT mesh
        (default 200.0).  Only used when ``gdf_method='rsgdf'``.
    tight_cell
        Force tight-cell or molecular-limit path.  ``None`` (default)
        auto-detects: tight when dim=3, Z>1, and cell volume < 500
        bohr^3.
    progress
        Live progress logging.
    """
    opts = options if options is not None else PeriodicRHFOptions()
    selection = _rijcosx_selection(
        system, opts, driver="run_periodic_rijcosx_rhf", open_shell=False,
    )
    guess = selection.effective
    lat_opts: LatticeSumOptions = opts.lattice_opts
    plog = resolve_progress(progress)

    n_elec = system.n_electrons()
    if n_elec % 2 != 0:
        raise ValueError(
            "run_periodic_rijcosx_rhf: closed-shell RHF requires even "
            f"electron count; got {n_elec}"
        )
    if system.multiplicity != 1:
        raise ValueError(
            "run_periodic_rijcosx_rhf: closed-shell RHF requires "
            f"multiplicity=1; got {system.multiplicity}"
        )

    dim = int(system.dim)
    active_lengths = [
        float(np.linalg.norm(np.asarray(system.lattice, dtype=float)[:, i]))
        for i in range(dim)
    ]

    # ---- Auto-detect tight vs molecular-limit -------------------------
    if tight_cell is None:
        tight_cell = _is_tight_cell(system)

    # ---- Auxiliary basis for DF-J / GDF --------------------------------
    mol = system.unit_cell_molecule()
    aux = _resolve_aux_basis(mol, basis, aux_basis)

    plog.info(
        f"RHF Γ-only RIJCOSX M3 / aux={aux.name}, "
        f"cutoff={lat_opts.cutoff_bohr:.2f} bohr, dim={dim}D, "
        f"tight_cell={tight_cell}, gdf_method={gdf_method}"
    )
    plog.info(
        f"orbital basis: {basis.name}  ({basis.nbasis} BFs / {basis.nshells} shells)"
    )
    plog.info(f"aux basis:     {aux.name}  ({aux.nbasis} BFs / {aux.nshells} shells)")
    plog.info(
        f"periodicity: dim={dim}D, active lengths="
        + ", ".join(f"{x:.3f}" for x in active_lengths)
        + " bohr"
    )

    # ---- One-electron integrals (gauge-consistent with J build) ---------
    # For 3D tight cells with GDF J (which drops G=0), V_ne and E_nuc
    # must also be in the Ewald-3D gauge.  For dim<3, the bare lattice
    # sum is correct.
    # For the molecular-limit path the molecular DF J carries no image
    # electrons, so V_ne / E_nuc must carry no image nuclei and K no
    # image-ket exchange (#707; see _home_cell_electrostatics_lat_opts).
    if tight_cell:
        gauge_lat_opts = _gauge_lat_opts_ewald_3d(lat_opts, system)
        exchange_lat_opts = lat_opts
    else:
        gauge_lat_opts, exchange_lat_opts = _home_cell_electrostatics_lat_opts(
            lat_opts
        )
    if tight_cell and int(system.dim) == 3 and gauge_lat_opts is not lat_opts:
        plog.info(
            "V_ne / e_nuc gauge: Ewald-3D (forced for 3D tight-cell GDF J consistency)"
        )

    with plog.stage("integrals_lattice"):
        S_set = compute_overlap_lattice(basis, system, lat_opts)
        T_set = compute_kinetic_lattice(basis, system, lat_opts)
        V_set = compute_nuclear_lattice_dispatch(basis, system, gauge_lat_opts)

    S = _fold_gamma_real(S_set)
    T = _fold_gamma_real(T_set)
    V_ne = _fold_gamma_real(V_set)
    Hcore = T + V_ne
    E_nuc = nuclear_repulsion_per_cell(system, gauge_lat_opts)

    plog.info(
        f"Γ-folded one-electron matrices: "
        f"{basis.nbasis} x {basis.nbasis}, "
        f"cell cutoff = {lat_opts.cutoff_bohr:.2f} bohr"
    )

    # ---- Build Lpq for tight-cell GDF J ---------------------------------
    if tight_cell:
        with plog.stage("gdf_lpq", detail=f"{gdf_method} aux={aux.nbasis}"):
            if gdf_method == "compcell":
                Lpq = build_lpq_compcell(
                    system,
                    basis,
                    aux,
                    molecule=mol,
                    lat_opts=lat_opts,
                    linear_dep_thr=float(gdf_linear_dep_threshold),
                    compcell_eta=float(compcell_eta),
                    apply_aft_correction=bool(apply_aft_correction),
                    aft_precision=float(aft_precision),
                    aft_ft_convention=str(aft_ft_convention),
                    rcut_strategy=rcut_strategy,
                    rcut_precision=float(rcut_precision),
                )
            elif gdf_method == "rsgdf":
                aux_modrho = make_modrho_aux_basis(aux, mol)
                Lpq = build_lpq_native_fft(
                    system,
                    basis,
                    aux_modrho,
                    ke_cutoff=float(rsgdf_ke_cutoff),
                    lat_opts=lat_opts,
                    linear_dep_thr=float(gdf_linear_dep_threshold),
                )
            else:
                raise ValueError(
                    f"run_periodic_rijcosx_rhf: gdf_method must be "
                    f"'compcell' or 'rsgdf'; got {gdf_method!r}"
                )
        plog.info(
            f"Lpq: {Lpq.shape[0]} fit vectors, "
            f"shape=({Lpq.shape[0]}, {Lpq.shape[1]}, {Lpq.shape[2]})"
        )

    # ---- RIJCOSX JKBuilder ----------------------------------------------
    with plog.stage("rijcosx_builder"):
        if tight_cell:
            # Periodic-correct GDF J from Lpq + COSX-K.
            # Lpq must be C-contiguous float64 for the pybind11 binding.
            Lpq_contig = np.ascontiguousarray(Lpq, dtype=np.float64)
            jk = make_periodic_tight_cosx_jk_builder(
                basis,
                Lpq_contig,
                system,
                lat_opts,
            )
            plog.info(
                f"RIJCOSX JKBuilder: periodic GDF J ({gdf_method} Lpq, "
                f"{Lpq.shape[0]} fit vectors) "
                "+ periodic COSX K (image-cell exchange summation, "
                f"cutoff {lat_opts.cutoff_bohr:.1f} bohr)"
            )
        else:
            # Molecular-limit path: molecular DF J + home-cell COSX-K.
            jk = make_periodic_gamma_cosx_jk_builder(
                basis,
                aux,
                system,
                exchange_lat_opts,
            )
            plog.info(
                "RIJCOSX JKBuilder: molecular DF J + home-cell COSX K "
                "(vacuum-padded box: no image-cell electrostatics)"
            )

    # ---- SCF loop (delegates to the production C++ engine) --------------
    with plog.stage("scf"):
        rhf_opts = RHFOptions()
        rhf_opts.initial_guess = selection.requested
        rhf_opts.max_iter = opts.max_iter
        rhf_opts.conv_tol_energy = opts.conv_tol_energy
        rhf_opts.conv_tol_grad = float(getattr(opts, "conv_tol_grad", 1e-6))
        rhf_opts.damping = float(opts.damping)
        rhf_opts.use_diis = bool(opts.use_diis)
        rhf_opts.diis_start_iter = int(opts.diis_start_iter)
        rhf_opts.diis_subspace_size = int(opts.diis_subspace_size)
        rhf_opts.level_shift = float(getattr(opts, "level_shift", 0.0))
        rhf_opts.dynamic_damping = bool(getattr(opts, "dynamic_damping", False))

        initial_density = _initial_density_closed(
            system, basis, n_elec // 2, guess, lat_opts, S, options=opts
        )
        result = run_rhf_scf_with_jk(
            basis,
            n_elec,
            S,
            Hcore,
            E_nuc,
            jk,
            rhf_opts,
            initial_density,
            molecule=system.unit_cell_molecule(), guess_selection=selection,
        )

    result = SimpleNamespace(
        overlap=np.asarray(S).copy(), hcore=np.asarray(Hcore).copy(),
        restart_lattice=np.asarray(system.lattice).copy(),
        restart_kpoints=np.zeros((1, 3)), restart_weights=np.ones(1),
        restart_basis=result.restart_basis,
        guess_selection=result.guess_selection,
        energy=result.energy,
        e_electronic=result.e_electronic,
        e_nuclear=E_nuc,
        n_iter=result.n_iter,
        converged=result.converged,
        mo_energies=result.mo_energies,
        mo_coeffs=result.mo_coeffs,
        density=result.density,
        fock=result.fock,
        scf_trace=result.scf_trace,
        omega=0.0,
        grid_shape=(0, 0, 0),
    )

    plog.info(f"SCF {'converged' if result.converged else 'NOT converged'}")
    plog.info(f"  E_total = {result.energy:.10f} Ha")
    plog.info(f"  iters   = {result.n_iter}")

    return result


def run_periodic_rijcosx_rks(
    system: PeriodicSystem,
    basis: BasisSet,
    options=None,
    *,
    functional: str,
    aux_basis: Optional[str] = None,
    grid_options=None,
    tight_cell: Optional[bool] = None,
    progress: Union[bool, ProgressLogger, None] = None,
):
    """Γ-only periodic RKS via RIJCOSX -- vacuum-padded envelope only.

    The closed-shell KS sibling of :func:`run_periodic_rijcosx_rhf`,
    restricted to the molecular-limit (vacuum-padded) regime: the
    dedicated Gamma builder supplies molecular DF J + periodic COSX K
    (exact when image-cell AO overlap is negligible), the XC term is
    integrated on the molecular Becke grid (exact in the same regime --
    the density is compactly supported in the box), and the SCF
    delegates to the production C++ ``run_rks_scf_with_jk``, which
    applies the post-convergence COSX one-center replacement through
    the builder's hook exactly as the RHF driver does.

    **Tight cells fail closed**: their XC needs the periodic-density
    grid (the legacy Gamma RKS route or the true multi-k GDF/COSX
    backend); silently integrating molecular XC there would be wrong.

    Parameters
    ----------
    system, basis, aux_basis, tight_cell, progress
        As in :func:`run_periodic_rijcosx_rhf`.
    options
        ``PeriodicKSOptions`` / ``PeriodicRHFOptions``-like object for
        the SCF controls (max_iter, conv tolerances, DIIS, damping).
        ``None`` uses defaults.
    functional
        libxc functional name (required). Hybrids route their exact-
        exchange fraction through the COSX K builder; pure functionals
        never call K.
    grid_options
        :class:`GridOptions` for the XC quadrature grid (``None`` =
        default XC tier).
    """
    from . import GridOptions, RKSOptions, build_grid, run_rks_scf_with_jk

    opts = options if options is not None else PeriodicRHFOptions()
    selection = _rijcosx_selection(
        system, opts, driver="run_periodic_rijcosx_rks", open_shell=False,
    )
    guess = selection.effective
    lat_opts: LatticeSumOptions = opts.lattice_opts
    plog = resolve_progress(progress)

    n_elec = system.n_electrons()
    if n_elec % 2 != 0:
        raise ValueError(
            "run_periodic_rijcosx_rks: closed-shell RKS requires even "
            f"electron count; got {n_elec}"
        )
    if system.multiplicity != 1:
        raise ValueError(
            "run_periodic_rijcosx_rks: closed-shell RKS requires "
            f"multiplicity=1; got {system.multiplicity}"
        )

    # Envelope gate: the XC term is integrated on the MOLECULAR Becke
    # grid with home-cell AOs, which is exact only when the periodic
    # density is compactly supported inside the cell. `_is_tight_cell`
    # alone is not sufficient here -- it deliberately waves pure-H tight
    # chains through for the J build (molecular DF J is fine there), but
    # their XC is NOT molecular-limit. Require genuine vacuum padding:
    # every active lattice length must exceed the threshold below.
    _RKS_MIN_ACTIVE_LENGTH_BOHR = 12.0
    if tight_cell is None:
        tight_cell = _is_tight_cell(system)
    _active_lengths = [
        float(np.linalg.norm(np.asarray(system.lattice, dtype=float)[:, i]))
        for i in range(int(system.dim))
    ]
    if tight_cell or min(_active_lengths) < _RKS_MIN_ACTIVE_LENGTH_BOHR:
        raise NotImplementedError(
            "run_periodic_rijcosx_rks: Gamma RIJCOSX RKS is implemented "
            "for the vacuum-padded (molecular-limit) envelope only "
            f"(every active lattice length >= "
            f"{_RKS_MIN_ACTIVE_LENGTH_BOHR:.0f} bohr and not a tight "
            "cell) -- tight-cell XC needs the periodic-density grid. "
            "Use the legacy Gamma RKS route (jk_method='gdf') or the "
            "true multi-k GDF/COSX backend (kpoints with >= 2 points)."
        )

    mol = system.unit_cell_molecule()
    aux = _resolve_aux_basis(mol, basis, aux_basis)

    plog.info(
        f"RKS Γ-only RIJCOSX (vacuum-padded envelope) / "
        f"functional={functional}, aux={aux.name}, "
        f"cutoff={lat_opts.cutoff_bohr:.2f} bohr, dim={int(system.dim)}D"
    )

    # Home-cell electrostatics throughout: the molecular DF J has no
    # image electrons (#707; see _home_cell_electrostatics_lat_opts).
    one_e_lat_opts, exchange_lat_opts = _home_cell_electrostatics_lat_opts(
        lat_opts
    )
    with plog.stage("integrals_lattice"):
        S_set = compute_overlap_lattice(basis, system, lat_opts)
        T_set = compute_kinetic_lattice(basis, system, lat_opts)
        V_set = compute_nuclear_lattice_dispatch(basis, system, one_e_lat_opts)
    S = _fold_gamma_real(S_set)
    T = _fold_gamma_real(T_set)
    Hcore = T + _fold_gamma_real(V_set)
    E_nuc = nuclear_repulsion_per_cell(system, one_e_lat_opts)

    with plog.stage("rijcosx_builder"):
        jk = make_periodic_gamma_cosx_jk_builder(
            basis, aux, system, exchange_lat_opts
        )
        plog.info(
            "RIJCOSX JKBuilder: molecular DF J + home-cell COSX K "
            "(vacuum-padded envelope: no image-cell electrostatics)"
        )

    xc_grid = build_grid(mol, grid_options or GridOptions())

    with plog.stage("scf"):
        rks_opts = RKSOptions()
        rks_opts.initial_guess = selection.requested
        rks_opts.functional = str(functional)
        rks_opts.max_iter = int(opts.max_iter)
        rks_opts.conv_tol_energy = float(opts.conv_tol_energy)
        rks_opts.conv_tol_grad = float(getattr(opts, "conv_tol_grad", 1e-6))
        rks_opts.damping = float(opts.damping)
        rks_opts.use_diis = bool(opts.use_diis)
        rks_opts.diis_start_iter = int(opts.diis_start_iter)
        rks_opts.diis_subspace_size = int(opts.diis_subspace_size)

        initial_density = _initial_density_closed(
            system, basis, n_elec // 2, guess, lat_opts, S, options=opts
        )
        res = run_rks_scf_with_jk(
            basis,
            n_elec,
            S,
            Hcore,
            E_nuc,
            jk,
            xc_grid,
            rks_opts,
            initial_density,
            molecule=system.unit_cell_molecule(), guess_selection=selection,
        )

    result = SimpleNamespace(
        overlap=np.asarray(S).copy(), hcore=np.asarray(Hcore).copy(),
        restart_lattice=np.asarray(system.lattice).copy(),
        restart_kpoints=np.zeros((1, 3)), restart_weights=np.ones(1),
        restart_basis=res.restart_basis,
        guess_selection=res.guess_selection,
        energy=res.energy,
        e_electronic=res.e_electronic,
        e_nuclear=E_nuc,
        e_xc=float(getattr(res, "e_xc", 0.0)),
        e_coulomb=float(getattr(res, "e_coulomb", 0.0)),
        e_hf_exchange=float(getattr(res, "e_hf_exchange", 0.0)),
        functional=str(functional),
        n_iter=res.n_iter,
        converged=res.converged,
        mo_energies=res.mo_energies,
        mo_coeffs=res.mo_coeffs,
        density=res.density,
        fock=res.fock,
        scf_trace=res.scf_trace,
        omega=0.0,
        grid_shape=(0, 0, 0),
    )
    plog.info(f"SCF {'converged' if result.converged else 'NOT converged'}")
    plog.info(f"  E_total = {result.energy:.10f} Ha")
    return result


# ---------------------------------------------------------------------------
# Gamma UHF / UKS on the vacuum-padded envelope (G-PBC-005 rung)
# ---------------------------------------------------------------------------


def _vacuum_envelope_setup(system, basis, aux_basis, lat_opts, label, plog):
    """Shared vacuum-padded-envelope validation + one-electron setup.

    Raises ``NotImplementedError`` outside the envelope (same criterion
    as the Gamma-RKS rung: every active lattice length >= 12 bohr and
    not a tight cell); returns ``(mol, aux, S, Hcore, E_nuc,
    exchange_lat_opts)``. V_ne and E_nuc carry the home-cell nuclei
    only and ``exchange_lat_opts`` restricts the COSX K to the home
    cell, matching the molecular DF J (#707; see
    ``_home_cell_electrostatics_lat_opts``).
    """
    _MIN_ACTIVE_LENGTH_BOHR = 12.0
    tight = _is_tight_cell(system)
    active_lengths = [
        float(np.linalg.norm(np.asarray(system.lattice, dtype=float)[:, i]))
        for i in range(int(system.dim))
    ]
    if tight or min(active_lengths) < _MIN_ACTIVE_LENGTH_BOHR:
        raise NotImplementedError(
            f"{label}: Gamma RIJCOSX open-shell/KS routes are implemented "
            "for the vacuum-padded (molecular-limit) envelope only "
            f"(every active lattice length >= "
            f"{_MIN_ACTIVE_LENGTH_BOHR:.0f} bohr and not a tight cell). "
            "Use the true multi-k GDF/COSX backend (kpoints with >= 2 "
            "points) or the GDF routes."
        )
    mol = system.unit_cell_molecule()
    aux = _resolve_aux_basis(mol, basis, aux_basis)
    one_e_lat_opts, exchange_lat_opts = _home_cell_electrostatics_lat_opts(
        lat_opts
    )
    with plog.stage("integrals_lattice"):
        S_set = compute_overlap_lattice(basis, system, lat_opts)
        T_set = compute_kinetic_lattice(basis, system, lat_opts)
        V_set = compute_nuclear_lattice_dispatch(basis, system, one_e_lat_opts)
    S = _fold_gamma_real(S_set)
    Hcore = _fold_gamma_real(T_set) + _fold_gamma_real(V_set)
    E_nuc = nuclear_repulsion_per_cell(system, one_e_lat_opts)
    return mol, aux, S, Hcore, E_nuc, exchange_lat_opts


def _spin_counts(system, label):
    n_elec = system.n_electrons()
    mult = int(system.multiplicity)
    if mult < 1:
        raise ValueError(f"{label}: multiplicity must be >= 1, got {mult}")
    if (n_elec + mult - 1) % 2 != 0:
        raise ValueError(
            f"{label}: n_electrons={n_elec} and multiplicity={mult} "
            "cannot be split into integer a/b occupations."
        )
    n_alpha = (n_elec + mult - 1) // 2
    n_beta = (n_elec - mult + 1) // 2
    if n_beta < 0:
        raise ValueError(
            f"{label}: multiplicity={mult} exceeds n_electrons={n_elec}"
        )
    return n_alpha, n_beta


def run_periodic_rijcosx_uhf(
    system: PeriodicSystem,
    basis: BasisSet,
    options=None,
    *,
    aux_basis: Optional[str] = None,
    progress: Union[bool, ProgressLogger, None] = None,
):
    """Γ-only periodic UHF via RIJCOSX -- vacuum-padded envelope only.

    The open-shell sibling of :func:`run_periodic_rijcosx_rhf`,
    restricted to the molecular-limit regime (same criterion as the
    Gamma-RKS rung): molecular DF J from the total density + per-spin
    home-cell COSX K through the dedicated Gamma builder, SCF through
    the production C++ ``run_uhf_scf_with_jk`` (per-spin
    post-convergence one-center replacement through the builder hook).
    Spin counts follow ``system.multiplicity``. Tight or short-axis
    cells fail closed.
    """
    from . import UHFOptions, run_uhf_scf_with_jk

    opts = options if options is not None else PeriodicRHFOptions()
    selection = _rijcosx_selection(
        system, opts, driver="run_periodic_rijcosx_uhf", open_shell=True,
    )
    guess = selection.effective
    _validate_atomic_spins(opts, guess)
    lat_opts: LatticeSumOptions = opts.lattice_opts
    plog = resolve_progress(progress)
    label = "run_periodic_rijcosx_uhf"
    n_alpha, n_beta = _spin_counts(system, label)

    mol, aux, S, Hcore, E_nuc, exchange_lat_opts = _vacuum_envelope_setup(
        system, basis, aux_basis, lat_opts, label, plog
    )
    plog.info(
        f"UHF Γ-only RIJCOSX (vacuum-padded envelope) / aux={aux.name}, "
        f"n_alpha={n_alpha}, n_beta={n_beta}"
    )
    with plog.stage("rijcosx_builder"):
        jk = make_periodic_gamma_cosx_jk_builder(
            basis, aux, system, exchange_lat_opts
        )

    with plog.stage("scf"):
        uhf_opts = UHFOptions()
        uhf_opts.initial_guess = selection.requested
        uhf_opts.max_iter = int(opts.max_iter)
        uhf_opts.conv_tol_energy = float(opts.conv_tol_energy)
        uhf_opts.conv_tol_grad = float(getattr(opts, "conv_tol_grad", 1e-6))
        uhf_opts.damping = float(opts.damping)
        uhf_opts.use_diis = bool(opts.use_diis)
        uhf_opts.diis_start_iter = int(opts.diis_start_iter)
        uhf_opts.diis_subspace_size = int(opts.diis_subspace_size)
        init_alpha, init_beta = _initial_densities_open(
            system,
            basis,
            n_alpha,
            n_beta,
            guess,
            lat_opts,
            atomic_spins=getattr(opts, "atomic_spins", None) or None,
            overlap=S, options=opts,
        )
        res = run_uhf_scf_with_jk(
            basis, n_alpha, n_beta, S, Hcore, E_nuc, jk, uhf_opts,
            init_alpha, init_beta,
            molecule=system.unit_cell_molecule(), guess_selection=selection,
        )

    result = SimpleNamespace(
        overlap=np.asarray(S).copy(), hcore=np.asarray(Hcore).copy(),
        restart_lattice=np.asarray(system.lattice).copy(),
        restart_kpoints=np.zeros((1, 3)), restart_weights=np.ones(1),
        restart_basis=res.restart_basis,
        guess_selection=res.guess_selection,
        energy=res.energy,
        e_electronic=res.e_electronic,
        e_nuclear=E_nuc,
        n_iter=res.n_iter,
        converged=res.converged,
        s_squared=float(getattr(res, "s_squared", 0.0)),
        mo_energies_alpha=res.mo_energies_alpha,
        mo_energies_beta=res.mo_energies_beta,
        mo_coeffs_alpha=res.mo_coeffs_alpha,
        mo_coeffs_beta=res.mo_coeffs_beta,
        density_alpha=res.density_alpha,
        density_beta=res.density_beta,
        fock_alpha=res.fock_alpha,
        fock_beta=res.fock_beta,
        scf_trace=res.scf_trace,
        omega=0.0,
        grid_shape=(0, 0, 0),
    )
    plog.info(f"SCF {'converged' if result.converged else 'NOT converged'}")
    plog.info(f"  E_total = {result.energy:.10f} Ha")
    return result


def run_periodic_rijcosx_uks(
    system: PeriodicSystem,
    basis: BasisSet,
    options=None,
    *,
    functional: str,
    aux_basis: Optional[str] = None,
    grid_options=None,
    progress: Union[bool, ProgressLogger, None] = None,
):
    """Γ-only periodic UKS via RIJCOSX -- vacuum-padded envelope only.

    The spin-polarised KS sibling of :func:`run_periodic_rijcosx_rks`
    (same envelope criterion and XC treatment); SCF through the
    production C++ ``run_uks_scf_with_jk``. Hybrids route their exact-
    exchange fraction through the per-spin COSX K; pure functionals
    never build K. Tight or short-axis cells fail closed.
    """
    from . import GridOptions, UKSOptions, build_grid, run_uks_scf_with_jk

    opts = options if options is not None else PeriodicRHFOptions()
    selection = _rijcosx_selection(
        system, opts, driver="run_periodic_rijcosx_uks", open_shell=True,
    )
    guess = selection.effective
    _validate_atomic_spins(opts, guess)
    lat_opts: LatticeSumOptions = opts.lattice_opts
    plog = resolve_progress(progress)
    label = "run_periodic_rijcosx_uks"
    n_alpha, n_beta = _spin_counts(system, label)

    mol, aux, S, Hcore, E_nuc, exchange_lat_opts = _vacuum_envelope_setup(
        system, basis, aux_basis, lat_opts, label, plog
    )
    plog.info(
        f"UKS Γ-only RIJCOSX (vacuum-padded envelope) / "
        f"functional={functional}, aux={aux.name}, "
        f"n_alpha={n_alpha}, n_beta={n_beta}"
    )
    with plog.stage("rijcosx_builder"):
        jk = make_periodic_gamma_cosx_jk_builder(
            basis, aux, system, exchange_lat_opts
        )
    xc_grid = build_grid(mol, grid_options or GridOptions())

    with plog.stage("scf"):
        uks_opts = UKSOptions()
        uks_opts.initial_guess = selection.requested
        uks_opts.functional = str(functional)
        uks_opts.max_iter = int(opts.max_iter)
        uks_opts.conv_tol_energy = float(opts.conv_tol_energy)
        uks_opts.conv_tol_grad = float(getattr(opts, "conv_tol_grad", 1e-6))
        uks_opts.damping = float(opts.damping)
        uks_opts.use_diis = bool(opts.use_diis)
        uks_opts.diis_start_iter = int(opts.diis_start_iter)
        uks_opts.diis_subspace_size = int(opts.diis_subspace_size)
        init_alpha, init_beta = _initial_densities_open(
            system,
            basis,
            n_alpha,
            n_beta,
            guess,
            lat_opts,
            atomic_spins=getattr(opts, "atomic_spins", None) or None,
            overlap=S, options=opts,
        )
        res = run_uks_scf_with_jk(
            basis, n_alpha, n_beta, S, Hcore, E_nuc, jk, xc_grid,
            uks_opts, init_alpha, init_beta,
            molecule=system.unit_cell_molecule(), guess_selection=selection,
        )

    result = SimpleNamespace(
        overlap=np.asarray(S).copy(), hcore=np.asarray(Hcore).copy(),
        restart_lattice=np.asarray(system.lattice).copy(),
        restart_kpoints=np.zeros((1, 3)), restart_weights=np.ones(1),
        restart_basis=res.restart_basis,
        guess_selection=res.guess_selection,
        energy=res.energy,
        e_electronic=res.e_electronic,
        e_nuclear=E_nuc,
        e_xc=float(getattr(res, "e_xc", 0.0)),
        functional=str(functional),
        n_iter=res.n_iter,
        converged=res.converged,
        s_squared=float(getattr(res, "s_squared", 0.0)),
        mo_energies_alpha=res.mo_energies_alpha,
        mo_energies_beta=res.mo_energies_beta,
        mo_coeffs_alpha=res.mo_coeffs_alpha,
        mo_coeffs_beta=res.mo_coeffs_beta,
        density_alpha=res.density_alpha,
        density_beta=res.density_beta,
        fock_alpha=res.fock_alpha,
        fock_beta=res.fock_beta,
        scf_trace=res.scf_trace,
        omega=0.0,
        grid_shape=(0, 0, 0),
    )
    plog.info(f"SCF {'converged' if result.converged else 'NOT converged'}")
    plog.info(f"  E_total = {result.energy:.10f} Ha")
    return result
